#ifndef STATS_IDS_H
#define STATS_IDS_H

/* Pokémon Typen Deutsch */
#define STATS_TYPE_NORMAL 0
#define STATS_TYPE_KAMPF 1
#define STATS_TYPE_FLUG 2
#define STATS_TYPE_GIFT 3
#define STATS_TYPE_BODEN 4
#define STATS_TYPE_GESTEIN 5
#define STATS_TYPE_KEAFER 6
#define STATS_TYPE_GEIST 7
#define STATS_TYPE_STAHL 8
#define STATS_TYPE_UNKNOWN 9
#define STATS_TYPE_FEUER 10
#define STATS_TYPE_WASSER 11
#define STATS_TYPE_PFLANZE 12
#define STATS_TYPE_ELEKTRO 13
#define STATS_TYPE_PSYCHO 14
#define STATS_TYPE_EIS 15
#define STATS_TYPE_DRACHE 16
#define STATS_TYPE_UNLICHT 17
#define STATS_TYPE_FEE 23

/* Pokémon Ei-Gruppen Deutsch */
#define STATS_EGG_GROUP_MONSTER 1
#define STATS_EGG_GROUP_WASSER_1 2
#define STATS_EGG_GROUP_KEAFER 3
#define STATS_EGG_GROUP_FLUG 4
#define STATS_EGG_GROUP_FELD 5
#define STATS_EGG_GROUP_FEE 6
#define STATS_EGG_GROUP_GRASS 7
#define STATS_EGG_GROUP_HUMANOTYP 8
#define STATS_EGG_GROUP_WASSER_3 9
#define STATS_EGG_GROUP_MINERAL 10
#define STATS_EGG_GROUP_AMORPH 11
#define STATS_EGG_GROUP_WASSER_2 12
#define STATS_EGG_GROUP_DITTO 13
#define STATS_EGG_GROUP_DRACHE 14
#define STATS_EGG_GROUP_UNBEKANNT 15

/* Pokémon Dex-Farben Deutsch */
#define STATS_DEX_COLOR_ROT 0
#define STATS_DEX_COLOR_BLAU 1
#define STATS_DEX_COLOR_GELB 2
#define STATS_DEX_COLOR_GRÜN 3
#define STATS_DEX_COLOR_SCHWARZ 4
#define STATS_DEX_COLOR_BRAUN 5
#define STATS_DEX_COLOR_VIOLETT 6
#define STATS_DEX_COLOR_GRAU 7
#define STATS_DEX_COLOR_WEIß 8
#define STATS_DEX_COLOR_ROSA 9

/* Pokémon Level-Aufstieg-Tempo Deutsch */
#define STATS_EP_LEVEL_UP_SCHNELL 0
#define STATS_EP_LEVEL_UP_SEHR_LANGSAM 1
#define STATS_EP_LEVEL_UP_SEHR_SCHNELL 2
#define STATS_EP_LEVEL_UP_NORMAL 3
#define STATS_EP_LEVEL_UP_SCHNELLER 4
#define STATS_EP_LEVEL_UP_LANGSAM 5

/* Pokémon Geschlechter-Rate Deutsch */
#define STATS_GENDER_M_100 0
#define STATS_GENDER_M_87_F_12 31
#define STATS_GENDER_M_75_F_25 63
#define STATS_GENDER_M_50_F_50 127
#define STATS_GENDER_M_25_F_75 191
#define STATS_GENDER_M_12_F_87 223
#define STATS_GENDER_KEINS 255

#endif /* #define STATS_IDS */