before_script:

  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build-sots:
  stage: build
  only:
    - tags
    - web
    - triggers

  script:
    - echo "Building Pokémon SotS"
    - make -j4 all
