//Pointer
.align 2

.global habitat_header
habitat_header:
.word habitat_gras 
.hword 51, 0
.word habitat_wald 
.hword 52, 0
.word habitat_ufer_und_see 
.hword 25, 0
.word habitat_wasser 
.hword 31, 0
.word habitat_hoehle 
.hword 24, 0
.word habitat_gebirge 
.hword 29, 0
.word habitat_wildniss 
.hword 42, 0
.word habitat_stadt 
.hword 43, 0
.word habitat_selten 
.hword 32, 0

.align 2
habitat_gras:
.word seite_gras1 
.hword 2, 0
.word seite_gras2 
.hword 2, 0
.word seite_gras3 
.hword 2, 0
.word seite_gras4 
.hword 2, 0
.word seite_gras5 
.hword 3, 0
.word seite_gras6 
.hword 3, 0
.word seite_gras7 
.hword 2, 0
.word seite_gras8 
.hword 2, 0
.word seite_gras9 
.hword 2, 0
.word seite_gras10 
.hword 2, 0
.word seite_gras11 
.hword 3, 0
.word seite_gras12 
.hword 3, 0
.word seite_gras13 
.hword 4, 0
.word seite_gras14 
.hword 2, 0
.word seite_gras15 
.hword 3, 0
.word seite_gras16 
.hword 3, 0
.word seite_gras17 
.hword 3, 0
.word seite_gras18 
.hword 2, 0
.word seite_gras19 
.hword 2, 0
.word seite_gras20 
.hword 2, 0
.word seite_gras21 
.hword 2, 0
.word seite_gras22 
.hword 2, 0
.word seite_gras23 
.hword 2, 0
.word seite_gras24 
.hword 3, 0
.word seite_gras25 
.hword 3, 0
.word seite_gras26 
.hword 2, 0
.word seite_gras27 
.hword 2, 0
.word seite_gras28 
.hword 2, 0
.word seite_gras29 
.hword 2, 0
.word seite_gras30 
.hword 1, 0
.word seite_gras31 
.hword 2, 0
.word seite_gras32 
.hword 3, 0
.word seite_gras33 
.hword 3, 0
.word seite_gras34 
.hword 3, 0
.word seite_gras35 
.hword 3, 0
.word seite_gras36 
.hword 3, 0
.word seite_gras37 
.hword 1, 0
.word seite_gras38 
.hword 2, 0
.word seite_gras39 
.hword 3, 0
.word seite_gras40 
.hword 2, 0
.word seite_gras41 
.hword 3, 0
.word seite_gras42 
.hword 1, 0
.word seite_gras43 
.hword 1, 0
.word seite_gras44 
.hword 2, 0
.word seite_gras45 
.hword 2, 0
.word seite_gras46 
.hword 3, 0
.word seite_gras47 
.hword 3, 0
.word seite_gras48 
.hword 2, 0
.word seite_gras49 
.hword 4, 0
.word seite_gras50 
.hword 2, 0
.word seite_gras51 
.hword 1, 0

.align 2
seite_gras1: 
.hword 19 
.hword 20
seite_gras2: 
.hword 161 
.hword 162
seite_gras3: 
.hword 288 
.hword 289
seite_gras4: 
.hword 286 
.hword 287
seite_gras5: 
.hword 29 
.hword 30 
.hword 31
seite_gras6: 
.hword 32 
.hword 33 
.hword 34
seite_gras7: 
.hword 84 
.hword 85
seite_gras8: 
.hword 304 
.hword 305
seite_gras9: 
.hword 114 
.hword 518
seite_gras10: 
.hword 191 
.hword 192
seite_gras11: 
.hword 459 
.hword 363 
.hword 460
seite_gras12: 
.hword 187 
.hword 188 
.hword 189
seite_gras13: 
.hword 43 
.hword 44 
.hword 45 
.hword 182
seite_gras14: 
.hword 23 
.hword 24
seite_gras15: 
.hword 174 
.hword 39 
.hword 40
seite_gras16: 
.hword 179 
.hword 180 
.hword 181
seite_gras17: 
.hword 83 
.hword 108 
.hword 516
seite_gras18: 
.hword 123 
.hword 212
seite_gras19: 
.hword 96 
.hword 97
seite_gras20: 
.hword 367 
.hword 368
seite_gras21: 
.hword 115 
.hword 203
seite_gras22: 
.hword 77 
.hword 78
seite_gras23: 
.hword 37 
.hword 38
seite_gras24: 
.hword 128 
.hword 241 
.hword 679
seite_gras25: 
.hword 239 
.hword 125 
.hword 519
seite_gras26: 
.hword 337 
.hword 338
seite_gras27: 
.hword 353 
.hword 354
seite_gras28: 
.hword 380 
.hword 379
seite_gras29: 
.hword 58 
.hword 59
seite_gras30: 
.hword 385
seite_gras31: 
.hword 486 
.hword 411
seite_gras32: 
.hword 1 
.hword 2 
.hword 3
seite_gras33: 
.hword 152 
.hword 153 
.hword 154
seite_gras34: 
.hword 155 
.hword 156 
.hword 157
seite_gras35: 
.hword 280 
.hword 281 
.hword 282
seite_gras36: 
.hword 456 
.hword 457 
.hword 458
seite_gras37: 
.hword 470
seite_gras38: 
.hword 512 
.hword 513
seite_gras39: 
.hword 548 
.hword 549 
.hword 550
seite_gras40: 
.hword 557 
.hword 558
seite_gras41: 
.hword 559 
.hword 560 
.hword 561
seite_gras42: 
.hword 614
seite_gras43: 
.hword 640
seite_gras44: 
.hword 643 
.hword 644
seite_gras45: 
.hword 712 
.hword 713
seite_gras46: 
.hword 714 
.hword 715 
.hword 716
seite_gras47: 
.hword 722 
.hword 723 
.hword 724
seite_gras48: 
.hword 725 
.hword 726
seite_gras49: 
.hword 735 
.hword 736 
.hword 737 
.hword 738
seite_gras50: 
.hword 747 
.hword 748
seite_gras51: 
.hword 755

.align 2
habitat_wald:
.word seite_wald1 
.hword 3, 0
.word seite_wald2 
.hword 3, 0
.word seite_wald3 
.hword 3, 0
.word seite_wald4 
.hword 2, 0
.word seite_wald5 
.hword 3, 0
.word seite_wald6 
.hword 2, 0
.word seite_wald7 
.hword 2, 0
.word seite_wald8 
.hword 3, 0
.word seite_wald9 
.hword 3, 0
.word seite_wald10 
.hword 2, 0
.word seite_wald11 
.hword 2, 0
.word seite_wald12 
.hword 3, 0
.word seite_wald13 
.hword 2, 0
.word seite_wald14 
.hword 2, 0
.word seite_wald15 
.hword 2, 0
.word seite_wald16 
.hword 4, 0
.word seite_wald17 
.hword 3, 0
.word seite_wald18 
.hword 2, 0
.word seite_wald19 
.hword 2, 0
.word seite_wald20 
.hword 3, 0
.word seite_wald21 
.hword 2, 0
.word seite_wald22 
.hword 2, 0
.word seite_wald23 
.hword 2, 0
.word seite_wald24 
.hword 2, 0
.word seite_wald25 
.hword 2, 0
.word seite_wald26 
.hword 2, 0
.word seite_wald27 
.hword 1, 0
.word seite_wald28 
.hword 1, 0
.word seite_wald29 
.hword 2, 0
.word seite_wald30 
.hword 2, 0
.word seite_wald31 
.hword 1, 0
.word seite_wald32 
.hword 3, 0
.word seite_wald33 
.hword 3, 0
.word seite_wald34 
.hword 3, 0
.word seite_wald35 
.hword 3, 0
.word seite_wald36 
.hword 2, 0
.word seite_wald37 
.hword 3, 0
.word seite_wald38 
.hword 2, 0
.word seite_wald39 
.hword 2, 0
.word seite_wald40 
.hword 2, 0
.word seite_wald41 
.hword 2, 0
.word seite_wald42 
.hword 2, 0
.word seite_wald43 
.hword 3, 0
.word seite_wald44 
.hword 3, 0
.word seite_wald45 
.hword 2, 0
.word seite_wald46 
.hword 2, 0
.word seite_wald47 
.hword 2, 0
.word seite_wald48 
.hword 2, 0
.word seite_wald49 
.hword 3, 0
.word seite_wald50 
.hword 3, 0
.word seite_wald51 
.hword 2, 0
.word seite_wald52 
.hword 2, 0

.align 2
seite_wald1: 
.hword 10 
.hword 11 
.hword 12
seite_wald2: 
.hword 13 
.hword 14 
.hword 15
seite_wald3: 
.hword 290 
.hword 291 
.hword 292
seite_wald4: 
.hword 293 
.hword 294
seite_wald5: 
.hword 16 
.hword 17 
.hword 18
seite_wald6: 
.hword 163 
.hword 164
seite_wald7: 
.hword 177 
.hword 178
seite_wald8: 
.hword 172 
.hword 25 
.hword 26
seite_wald9: 
.hword 69 
.hword 70 
.hword 71
seite_wald10: 
.hword 46 
.hword 47
seite_wald11: 
.hword 306 
.hword 307
seite_wald12: 
.hword 298 
.hword 299 
.hword 300
seite_wald13: 
.hword 48 
.hword 49
seite_wald14: 
.hword 193 
.hword 522
seite_wald15: 
.hword 165 
.hword 166
seite_wald16: 
.hword 167 
.hword 168 
.hword 648 
.hword 649
seite_wald17: 
.hword 301 
.hword 302 
.hword 303
seite_wald18: 
.hword 386 
.hword 387
seite_wald19: 
.hword 204 
.hword 205
seite_wald20: 
.hword 364 
.hword 365 
.hword 366
seite_wald21: 
.hword 315 
.hword 316
seite_wald22: 
.hword 198 
.hword 483
seite_wald23: 
.hword 215 
.hword 514
seite_wald24: 
.hword 102 
.hword 103
seite_wald25: 
.hword 491 
.hword 185
seite_wald26: 
.hword 190 
.hword 477
seite_wald27: 
.hword 234
seite_wald28: 
.hword 317
seite_wald29: 
.hword 127 
.hword 214
seite_wald30: 
.hword 358 
.hword 359
seite_wald31: 
.hword 369
seite_wald32: 
.hword 361 
.hword 362 
.hword 530
seite_wald33: 
.hword 175 
.hword 176 
.hword 521
seite_wald34: 
.hword 277 
.hword 278 
.hword 279
seite_wald35: 
.hword 443 
.hword 444 
.hword 445
seite_wald36: 
.hword 454 
.hword 455
seite_wald37: 
.hword 465 
.hword 466 
.hword 467
seite_wald38: 
.hword 468 
.hword 469
seite_wald39: 
.hword 473 
.hword 474
seite_wald40: 
.hword 564 
.hword 565
seite_wald41: 
.hword 566 
.hword 567
seite_wald42: 
.hword 568 
.hword 569
seite_wald43: 
.hword 593 
.hword 594 
.hword 595
seite_wald44: 
.hword 596 
.hword 597 
.hword 598
seite_wald45: 
.hword 599 
.hword 600
seite_wald46: 
.hword 601 
.hword 602
seite_wald47: 
.hword 669 
.hword 670
seite_wald48: 
.hword 689 
.hword 690
seite_wald49: 
.hword 706 
.hword 707 
.hword 708
seite_wald50: 
.hword 717 
.hword 718 
.hword 719
seite_wald51: 
.hword 761 
.hword 762
seite_wald52: 
.hword 763 
.hword 764

.align 2
habitat_ufer_und_see:
.word seite_ufersee1 
.hword 2, 0
.word seite_ufersee2 
.hword 2, 0
.word seite_ufersee3 
.hword 4, 0
.word seite_ufersee4 
.hword 2, 0
.word seite_ufersee5 
.hword 3, 0
.word seite_ufersee6 
.hword 2, 0
.word seite_ufersee7 
.hword 2, 0
.word seite_ufersee8 
.hword 2, 0
.word seite_ufersee9 
.hword 4, 0
.word seite_ufersee10 
.hword 3, 0
.word seite_ufersee11 
.hword 3, 0
.word seite_ufersee12 
.hword 2, 0
.word seite_ufersee13 
.hword 2, 0
.word seite_ufersee14 
.hword 3, 0
.word seite_ufersee15 
.hword 3, 0
.word seite_ufersee16 
.hword 3, 0
.word seite_ufersee17 
.hword 3, 0
.word seite_ufersee18 
.hword 3, 0
.word seite_ufersee19 
.hword 2, 0
.word seite_ufersee20 
.hword 2, 0
.word seite_ufersee21 
.hword 2, 0
.word seite_ufersee22 
.hword 2, 0
.word seite_ufersee23 
.hword 2, 0
.word seite_ufersee24 
.hword 3, 0
.word seite_ufersee25 
.hword 3, 0

.align 2

seite_ufersee1: 
.hword 118 
.hword 119
seite_ufersee2: 
.hword 129 
.hword 130
seite_ufersee3: 
.hword 98 
.hword 99 
.hword 326 
.hword 327
seite_ufersee4: 
.hword 323 
.hword 324
seite_ufersee5: 
.hword 295 
.hword 296 
.hword 297
seite_ufersee6: 
.hword 311 
.hword 312
seite_ufersee7: 
.hword 54 
.hword 55
seite_ufersee8: 
.hword 194 
.hword 195
seite_ufersee9: 
.hword 60 
.hword 61 
.hword 62 
.hword 186
seite_ufersee10: 
.hword 350 
.hword 183 
.hword 184
seite_ufersee11: 
.hword 79 
.hword 80 
.hword 199
seite_ufersee12: 
.hword 328 
.hword 329
seite_ufersee13: 
.hword 390 
.hword 391
seite_ufersee14: 
.hword 147 
.hword 148 
.hword 149
seite_ufersee15: 
.hword 7 
.hword 8 
.hword 9
seite_ufersee16: 
.hword 158 
.hword 159 
.hword 160
seite_ufersee17: 
.hword 283 
.hword 284 
.hword 285
seite_ufersee18: 
.hword 440 
.hword 441 
.hword 442
seite_ufersee19: 
.hword 452 
.hword 453
seite_ufersee20: 
.hword 471 
.hword 472
seite_ufersee21: 
.hword 475 
.hword 476
seite_ufersee22: 
.hword 633 
.hword 634
seite_ufersee23: 
.hword 666 
.hword 667
seite_ufersee24: 
.hword 709 
.hword 710 
.hword 711
seite_ufersee25: 
.hword 757 
.hword 758 
.hword 759

.align 2

habitat_wasser:
.word seite_wasser1 
.hword 2, 0
.word seite_wasser2 
.hword 2, 0
.word seite_wasser3 
.hword 2, 0
.word seite_wasser4 
.hword 2, 0
.word seite_wasser5 
.hword 2, 0
.word seite_wasser6 
.hword 2, 0
.word seite_wasser7 
.hword 3, 0
.word seite_wasser8 
.hword 1, 0
.word seite_wasser9 
.hword 1, 0
.word seite_wasser10 
.hword 2, 0
.word seite_wasser11 
.hword 1, 0
.word seite_wasser12 
.hword 2, 0
.word seite_wasser13 
.hword 3, 0
.word seite_wasser14 
.hword 2, 0
.word seite_wasser15 
.hword 3, 0
.word seite_wasser16 
.hword 3, 0
.word seite_wasser17 
.hword 1, 0
.word seite_wasser18 
.hword 4, 0
.word seite_wasser19 
.hword 2, 0
.word seite_wasser20 
.hword 3, 0
.word seite_wasser21 
.hword 2, 0
.word seite_wasser22 
.hword 3, 0
.word seite_wasser23 
.hword 3, 0
.word seite_wasser24 
.hword 1, 0
.word seite_wasser25 
.hword 2, 0
.word seite_wasser26 
.hword 2, 0
.word seite_wasser27 
.hword 1, 0
.word seite_wasser28 
.hword 1, 0
.word seite_wasser29 
.hword 2, 0
.word seite_wasser30 
.hword 2, 0
.word seite_wasser31 
.hword 2, 0

.align 2

seite_wasser1: 
.hword 72 
.hword 73
seite_wasser2: 
.hword 309 
.hword 310
seite_wasser3: 
.hword 120 
.hword 121
seite_wasser4: 
.hword 170 
.hword 171
seite_wasser5: 
.hword 223 
.hword 224
seite_wasser6: 
.hword 90 
.hword 91
seite_wasser7: 
.hword 373 
.hword 374 
.hword 375
seite_wasser8: 
.hword 211
seite_wasser9: 
.hword 222
seite_wasser10: 
.hword 511 
.hword 226
seite_wasser11: 
.hword 325
seite_wasser12: 
.hword 86 
.hword 87
seite_wasser13: 
.hword 341 
.hword 342 
.hword 343
seite_wasser14: 
.hword 330 
.hword 331
seite_wasser15: 
.hword 313 
.hword 314 
.hword 381
seite_wasser16: 
.hword 116 
.hword 117 
.hword 230
seite_wasser17: 
.hword 131
seite_wasser18: 
.hword 138 
.hword 139 
.hword 140 
.hword 141
seite_wasser19: 
.hword 388 
.hword 389
seite_wasser20: 
.hword 446 
.hword 447 
.hword 448
seite_wasser21: 
.hword 509 
.hword 510
seite_wasser22: 
.hword 554 
.hword 555 
.hword 556
seite_wasser23: 
.hword 588 
.hword 589 
.hword 590
seite_wasser24: 
.hword 603
seite_wasser25: 
.hword 617 
.hword 618
seite_wasser26: 
.hword 645 
.hword 646
seite_wasser27: 
.hword 647
seite_wasser28: 
.hword 671
seite_wasser29: 
.hword 741 
.hword 742
seite_wasser30: 
.hword 743 
.hword 744
seite_wasser31: 
.hword 745 
.hword 746

.align 2

habitat_hoehle:
.word seite_hoehle1 
.hword 3, 0
.word seite_hoehle2 
.hword 2, 0
.word seite_hoehle3 
.hword 2, 0
.word seite_hoehle4 
.hword 3, 0
.word seite_hoehle5 
.hword 3, 0
.word seite_hoehle6 
.hword 3, 0
.word seite_hoehle7 
.hword 2, 0
.word seite_hoehle8 
.hword 1, 0
.word seite_hoehle9 
.hword 2, 0
.word seite_hoehle10 
.hword 1, 0
.word seite_hoehle11 
.hword 1, 0
.word seite_hoehle12 
.hword 3, 0
.word seite_hoehle13 
.hword 2, 0
.word seite_hoehle14 
.hword 2, 0
.word seite_hoehle15 
.hword 2, 0
.word seite_hoehle16 
.hword 2, 0
.word seite_hoehle17 
.hword 2, 0
.word seite_hoehle18 
.hword 3, 0
.word seite_hoehle19 
.hword 2, 0
.word seite_hoehle20 
.hword 3, 0
.word seite_hoehle21 
.hword 1, 0
.word seite_hoehle22 
.hword 2, 0
.word seite_hoehle23 
.hword 1, 0
.word seite_hoehle24 
.hword 2, 0

seite_hoehle1: 
.hword 41 
.hword 42 
.hword 169
seite_hoehle2: 
.hword 50 
.hword 51
seite_hoehle3: 
.hword 95 
.hword 208
seite_hoehle4: 
.hword 220 
.hword 221 
.hword 526
seite_hoehle5: 
.hword 346 
.hword 347 
.hword 531
seite_hoehle6: 
.hword 370 
.hword 371 
.hword 372
seite_hoehle7: 
.hword 200 
.hword 482
seite_hoehle8: 
.hword 206
seite_hoehle9: 
.hword 320 
.hword 529
seite_hoehle10: 
.hword 322
seite_hoehle11: 
.hword 355
seite_hoehle12: 
.hword 92 
.hword 93 
.hword 94
seite_hoehle13: 
.hword 360 
.hword 202
seite_hoehle14: 
.hword 348 
.hword 349
seite_hoehle15: 
.hword 489 
.hword 490
seite_hoehle16: 
.hword 580 
.hword 581
seite_hoehle17: 
.hword 582 
.hword 583
seite_hoehle18: 
.hword 635 
.hword 636 
.hword 637
seite_hoehle19: 
.hword 658 
.hword 659
seite_hoehle20: 
.hword 660 
.hword 661 
.hword 662
seite_hoehle21: 
.hword 668
seite_hoehle22: 
.hword 675 
.hword 676
seite_hoehle23: 
.hword 756
seite_hoehle24: 
.hword 765 
.hword 766

.align 2

habitat_gebirge:
.word seite_gebirge1 
.hword 3, 0
.word seite_gebirge2 
.hword 2, 0
.word seite_gebirge3 
.hword 2, 0
.word seite_gebirge4 
.hword 3, 0
.word seite_gebirge5 
.hword 3, 0
.word seite_gebirge6 
.hword 2, 0
.word seite_gebirge7 
.hword 2, 0
.word seite_gebirge8 
.hword 3, 0
.word seite_gebirge9 
.hword 2, 0
.word seite_gebirge10 
.hword 2, 0
.word seite_gebirge11 
.hword 1, 0
.word seite_gebirge12 
.hword 2, 0
.word seite_gebirge13 
.hword 1, 0
.word seite_gebirge14 
.hword 2, 0
.word seite_gebirge15 
.hword 1, 0
.word seite_gebirge16 
.hword 3, 0
.word seite_gebirge17 
.hword 3, 0
.word seite_gebirge18 
.hword 3, 0
.word seite_gebirge19 
.hword 2, 0
.word seite_gebirge20 
.hword 1, 0
.word seite_gebirge21 
.hword 1, 0
.word seite_gebirge22 
.hword 3, 0
.word seite_gebirge23 
.hword 4, 0
.word seite_gebirge24 
.hword 3, 0
.word seite_gebirge25 
.hword 3, 0
.word seite_gebirge26 
.hword 2, 0
.word seite_gebirge27 
.hword 1, 0
.word seite_gebirge28 
.hword 3, 0
.word seite_gebirge29 
.hword 2, 0

seite_gebirge1: 
.hword 74 
.hword 75 
.hword 76
seite_gebirge2: 
.hword 56 
.hword 57
seite_gebirge3: 
.hword 351 
.hword 352
seite_gebirge4: 
.hword 66 
.hword 67 
.hword 68
seite_gebirge5: 
.hword 173 
.hword 35 
.hword 36
seite_gebirge6: 
.hword 104 
.hword 105
seite_gebirge7: 
.hword 218 
.hword 219
seite_gebirge8: 
.hword 339 
.hword 340 
.hword 321
seite_gebirge9: 
.hword 335 
.hword 336
seite_gebirge10: 
.hword 356 
.hword 357
seite_gebirge11: 
.hword 213
seite_gebirge12: 
.hword 216 
.hword 217
seite_gebirge13: 
.hword 225
seite_gebirge14: 
.hword 207 
.hword 525
seite_gebirge15: 
.hword 308
seite_gebirge16: 
.hword 240 
.hword 126 
.hword 520
seite_gebirge17: 
.hword 382 
.hword 383 
.hword 384
seite_gebirge18: 
.hword 246 
.hword 247 
.hword 248
seite_gebirge19: 
.hword 499 
.hword 143
seite_gebirge20: 
.hword 376
seite_gebirge21: 
.hword 142
seite_gebirge22: 
.hword 4 
.hword 5 
.hword 6
seite_gebirge23: 
.hword 461 
.hword 462 
.hword 463 
.hword 464
seite_gebirge24: 
.hword 496 
.hword 497 
.hword 498
seite_gebirge25: 
.hword 577 
.hword 578 
.hword 579
seite_gebirge26: 
.hword 619 
.hword 620
seite_gebirge27: 
.hword 674
seite_gebirge28: 
.hword 686 
.hword 687 
.hword 688
seite_gebirge29: 
.hword 751 
.hword 752

.align 2

habitat_wildniss:
.word seite_wildniss1 
.hword 2, 0
.word seite_wildniss2 
.hword 2, 0
.word seite_wildniss3 
.hword 3, 0
.word seite_wildniss4 
.hword 3, 0
.word seite_wildniss5 
.hword 2, 0
.word seite_wildniss6 
.hword 2, 0
.word seite_wildniss7 
.hword 2, 0
.word seite_wildniss8 
.hword 3, 0
.word seite_wildniss9 
.hword 1, 0
.word seite_wildniss10 
.hword 2, 0
.word seite_wildniss11 
.hword 3, 0
.word seite_wildniss12 
.hword 3, 0
.word seite_wildniss13 
.hword 3, 0
.word seite_wildniss14 
.hword 2, 0
.word seite_wildniss15 
.hword 1, 0
.word seite_wildniss16 
.hword 2, 0
.word seite_wildniss17 
.hword 2, 0
.word seite_wildniss18 
.hword 2, 0
.word seite_wildniss19 
.hword 2, 0
.word seite_wildniss20 
.hword 1, 0
.word seite_wildniss21 
.hword 3, 0
.word seite_wildniss22 
.hword 2, 0
.word seite_wildniss23 
.hword 3, 0
.word seite_wildniss24 
.hword 2, 0
.word seite_wildniss25 
.hword 3, 0
.word seite_wildniss26 
.hword 2, 0
.word seite_wildniss27 
.hword 1, 0
.word seite_wildniss28 
.hword 2, 0
.word seite_wildniss29 
.hword 3, 0
.word seite_wildniss30 
.hword 2, 0
.word seite_wildniss31 
.hword 2, 0
.word seite_wildniss32 
.hword 2, 0
.word seite_wildniss33 
.hword 3, 0
.word seite_wildniss34 
.hword 4, 0
.word seite_wildniss35 
.hword 2, 0
.word seite_wildniss36 
.hword 3, 0
.word seite_wildniss37 
.hword 2, 0
.word seite_wildniss38 
.hword 2, 0
.word seite_wildniss39 
.hword 2, 0
.word seite_wildniss40 
.hword 2, 0
.word seite_wildniss41 
.hword 1, 0
.word seite_wildniss42 
.hword 2, 0

.align 2

seite_wildniss1: 
.hword 21 
.hword 22
seite_wildniss2: 
.hword 27 
.hword 28
seite_wildniss3: 
.hword 111 
.hword 112 
.hword 517
seite_wildniss4: 
.hword 81 
.hword 82 
.hword 515
seite_wildniss5: 
.hword 228 
.hword 229
seite_wildniss6: 
.hword 231 
.hword 232
seite_wildniss7: 
.hword 344 
.hword 345
seite_wildniss8: 
.hword 332 
.hword 333 
.hword 334
seite_wildniss9: 
.hword 227
seite_wildniss10: 
.hword 318 
.hword 319
seite_wildniss11: 
.hword 395 
.hword 396 
.hword 397
seite_wildniss12: 
.hword 398 
.hword 399 
.hword 400
seite_wildniss13: 
.hword 449 
.hword 450 
.hword 451
seite_wildniss14: 
.hword 487 
.hword 488
seite_wildniss15: 
.hword 495
seite_wildniss16: 
.hword 500 
.hword 501
seite_wildniss17: 
.hword 502 
.hword 503
seite_wildniss18: 
.hword 504 
.hword 505
seite_wildniss19: 
.hword 506 
.hword 507
seite_wildniss20: 
.hword 508
seite_wildniss21: 
.hword 551 
.hword 552 
.hword 553
seite_wildniss22: 
.hword 570 
.hword 571
seite_wildniss23: 
.hword 572 
.hword 573 
.hword 574
seite_wildniss24: 
.hword 575 
.hword 576
seite_wildniss25: 
.hword 604 
.hword 605 
.hword 606
seite_wildniss26: 
.hword 607 
.hword 608
seite_wildniss27: 
.hword 609
seite_wildniss28: 
.hword 610 
.hword 611
seite_wildniss29: 
.hword 630 
.hword 631 
.hword 632
seite_wildniss30: 
.hword 638 
.hword 639
seite_wildniss31: 
.hword 641 
.hword 642
seite_wildniss32: 
.hword 650 
.hword 651
seite_wildniss33: 
.hword 663 
.hword 664 
.hword 665
seite_wildniss34: 
.hword 680 
.hword 681 
.hword 682 
.hword 683
seite_wildniss35: 
.hword 684 
.hword 685
seite_wildniss36: 
.hword 703 
.hword 704 
.hword 705
seite_wildniss37: 
.hword 720 
.hword 721
seite_wildniss38: 
.hword 727 
.hword 728
seite_wildniss39: 
.hword 739 
.hword 740
seite_wildniss40: 
.hword 749 
.hword 750
seite_wildniss41: 
.hword 754
seite_wildniss42: 
.hword 767 
.hword 768

.align 2

habitat_stadt:
.word seite_stadt1 
.hword 4, 0
.word seite_stadt2 
.hword 2, 0
.word seite_stadt3 
.hword 2, 0
.word seite_stadt4 
.hword 2, 0
.word seite_stadt5 
.hword 2, 0
.word seite_stadt6 
.hword 3, 0
.word seite_stadt7 
.hword 4, 0
.word seite_stadt8 
.hword 2, 0
.word seite_stadt9 
.hword 2, 0
.word seite_stadt10 
.hword 1, 0
.word seite_stadt11 
.hword 4, 0
.word seite_stadt12 
.hword 3, 0
.word seite_stadt13 
.hword 2, 0
.word seite_stadt14 
.hword 3, 0
.word seite_stadt15 
.hword 1, 0
.word seite_stadt16 
.hword 4, 0
.word seite_stadt17 
.hword 2, 0
.word seite_stadt18 
.hword 2, 0
.word seite_stadt19 
.hword 1, 0
.word seite_stadt20 
.hword 2, 0
.word seite_stadt21 
.hword 2, 0
.word seite_stadt22 
.hword 1, 0
.word seite_stadt23 
.hword 1, 0
.word seite_stadt24 
.hword 2, 0
.word seite_stadt25 
.hword 1, 0
.word seite_stadt26 
.hword 3, 0
.word seite_stadt27 
.hword 2, 0
.word seite_stadt28 
.hword 2, 0
.word seite_stadt29 
.hword 2, 0
.word seite_stadt30 
.hword 2, 0
.word seite_stadt31 
.hword 2, 0
.word seite_stadt32 
.hword 2, 0
.word seite_stadt33 
.hword 3, 0
.word seite_stadt34 
.hword 3, 0
.word seite_stadt35 
.hword 3, 0
.word seite_stadt36 
.hword 2, 0
.word seite_stadt37 
.hword 3, 0
.word seite_stadt38 
.hword 2, 0
.word seite_stadt39 
.hword 2, 0
.word seite_stadt40 
.hword 1, 0
.word seite_stadt41 
.hword 2, 0
.word seite_stadt42 
.hword 3, 0
.word seite_stadt43 
.hword 1, 0

.align 2

seite_stadt1: 
.hword 52 
.hword 53 
.hword 484 
.hword 485
seite_stadt2: 
.hword 209 
.hword 210
seite_stadt3: 
.hword 88 
.hword 89
seite_stadt4: 
.hword 109 
.hword 110
seite_stadt5: 
.hword 377 
.hword 378
seite_stadt6: 
.hword 63 
.hword 64 
.hword 65
seite_stadt7: 
.hword 392 
.hword 393 
.hword 394 
.hword 528
seite_stadt8: 
.hword 238 
.hword 124
seite_stadt9: 
.hword 492 
.hword 122
seite_stadt10: 
.hword 235
seite_stadt11: 
.hword 236 
.hword 106 
.hword 107 
.hword 237
seite_stadt12: 
.hword 493 
.hword 113 
.hword 242
seite_stadt13: 
.hword 100 
.hword 101
seite_stadt14: 
.hword 137 
.hword 233 
.hword 527
seite_stadt15: 
.hword 132
seite_stadt16: 
.hword 133 
.hword 134 
.hword 135 
.hword 136
seite_stadt17: 
.hword 196 
.hword 197
seite_stadt18: 
.hword 523 
.hword 524
seite_stadt19: 
.hword 753
seite_stadt20: 
.hword 478 
.hword 479
seite_stadt21: 
.hword 480 
.hword 481
seite_stadt22: 
.hword 494
seite_stadt23: 
.hword 532
seite_stadt24: 
.hword 562 
.hword 563
seite_stadt25: 
.hword 584
seite_stadt26: 
.hword 585 
.hword 586 
.hword 587
seite_stadt27: 
.hword 591 
.hword 592
seite_stadt28: 
.hword 612 
.hword 613
seite_stadt29: 
.hword 615 
.hword 616
seite_stadt30: 
.hword 621 
.hword 622
seite_stadt31: 
.hword 623 
.hword 624
seite_stadt32: 
.hword 625 
.hword 626
seite_stadt33: 
.hword 627 
.hword 628 
.hword 629
seite_stadt34: 
.hword 652 
.hword 653 
.hword 654
seite_stadt35: 
.hword 655 
.hword 656 
.hword 657
seite_stadt36: 
.hword 658 
.hword 659
seite_stadt37: 
.hword 660 
.hword 661 
.hword 662
seite_stadt38: 
.hword 672 
.hword 673
seite_stadt39: 
.hword 677 
.hword 678
seite_stadt40: 
.hword 729
seite_stadt41: 
.hword 730 
.hword 731
seite_stadt42: 
.hword 732 
.hword 733 
.hword 734
seite_stadt43: 
.hword 760

.align 2

habitat_selten:
.word seite_selten1 
.hword 1, 0
.word seite_selten2 
.hword 3, 0
.word seite_selten3 
.hword 2, 0
.word seite_selten4 
.hword 3, 0
.word seite_selten5 
.hword 1, 0
.word seite_selten6 
.hword 1, 0
.word seite_selten7 
.hword 1, 0
.word seite_selten8 
.hword 4, 0
.word seite_selten9 
.hword 2, 0
.word seite_selten10 
.hword 3, 0
.word seite_selten11 
.hword 1, 0
.word seite_selten12 
.hword 1, 0
.word seite_selten13 
.hword 3, 0
.word seite_selten14 
.hword 2, 0
.word seite_selten15 
.hword 1, 0
.word seite_selten16 
.hword 1, 0
.word seite_selten17 
.hword 2, 0
.word seite_selten18 
.hword 2, 0
.word seite_selten19 
.hword 1, 0
.word seite_selten20 
.hword 1, 0
.word seite_selten21 
.hword 1, 0
.word seite_selten22 
.hword 1, 0
.word seite_selten23 
.hword 3, 0
.word seite_selten24 
.hword 3, 0
.word seite_selten25 
.hword 3, 0
.word seite_selten26 
.hword 1, 0
.word seite_selten27 
.hword 1, 0
.word seite_selten28 
.hword 1, 0
.word seite_selten29 
.hword 3, 0
.word seite_selten30 
.hword 1, 0
.word seite_selten31 
.hword 1, 0
.word seite_selten32 
.hword 1, 0

.align 2

seite_selten1: 
.hword 201
seite_selten2: 
.hword 144 
.hword 145 
.hword 146
seite_selten3: 
.hword 151 
.hword 150
seite_selten4: 
.hword 243 
.hword 244 
.hword 245
seite_selten5: 
.hword 249
seite_selten6: 
.hword 250
seite_selten7: 
.hword 251
seite_selten8: 
.hword 401 
.hword 402 
.hword 403 
.hword 539
seite_selten9: 
.hword 407 
.hword 408
seite_selten10: 
.hword 405 
.hword 404 
.hword 406
seite_selten11: 
.hword 410
seite_selten12: 
.hword 409
seite_selten13: 
.hword 533 
.hword 534 
.hword 535
seite_selten14: 
.hword 536 
.hword 537
seite_selten15: 
.hword 540
seite_selten16: 
.hword 540
seite_selten17: 
.hword 541 
.hword 544
seite_selten18: 
.hword 542 
.hword 543
seite_selten19: 
.hword 538
seite_selten20: 
.hword 545
seite_selten21: 
.hword 546
seite_selten22: 
.hword 547
seite_selten23: 
.hword 691 
.hword 692 
.hword 693
seite_selten24: 
.hword 694 
.hword 695 
.hword 698
seite_selten25: 
.hword 696 
.hword 697 
.hword 699
seite_selten26: 
.hword 700
seite_selten27: 
.hword 701
seite_selten28: 
.hword 702
seite_selten29: 
.hword 769 
.hword 770 
.hword 771
seite_selten30: 
.hword 772
seite_selten31: 
.hword 773
seite_selten32: 
.hword 774