#ifndef BATTLESCREEN_IDS_H_
#define BATTLESCREEN_IDS_H_IDS_H_

#define BATTLESCREEN_GRASS 0x0
#define BATTLESCREEN_STRAND 0x1
#define BATTLESCREEN_UNTERWASSER 0x2
#define BATTLESCREEN_MEER 0x3
#define BATTLESCREEN_SEE 0x4
#define BATTLESCREEN_GEBIRGE 0x5
#define BATTLESCREEN_HOEHLE_1 0x6
#define BATTLESCREEN_INNEN 0x7
#define BATTLESCREEN_DORF 0x8
#define BATTLESCREEN_WALD1 0x9
#define BATTLESCREEN_STADT 0xA
#define BATTLESCREEN_SCHNEESTADT 0xB
#define BATTLESCREEN_SCHNEEDORF 0xC
#define BATTLESCREEN_SCHNEESEE 0xD
#define BATTLESCREEN_WUESTE 0xE
#define BATTLESCREEN_WUESTENSEE 0xF
#define BATTLESCREEN_BRUECKE 0x10
#define BATTLESCREEN_HIMMEL 0x11
#define BATTLESCREEN_WALD2 0x12
#define BATTLESCREEN_HOEHLE 0x13
#define BATTLESCREEN_SANDHOEHLE 0x14
#define BATTLESCREEN_EISHOEHLE 0x15
#define BATTLESCREEN_KRISTALLHOEHLE 0x16
#define BATTLESCREEN_FEUERHOEHLE 0x17
#define BATTLESCREEN_WASSERHOEHLE 0x18

#endif /* MUG_IDS_H */