#ifndef MUG_IDS_H_
#define MUG_IDS_H_

#define MUG_NOAH 1
#define MUG_EMMA 9
#define MUG_LINDA 17
#define MUG_IDAN 20
#define MUG_ACHIM 24
#define MUG_NORMAN 27
#define MUG_JANA 30
#define MUG_MARKUS 33
#define MUG_ISABELLE 35
#define MUG_DIANA 37

#define MUG_NOAH_NORMAL 1
#define MUG_NOAH_LACHEN 2
#define MUG_NOAH_BESCHEIDEN 3
#define MUG_NOAH_ERSTAUNT 4
#define MUG_NOAH_TRAURIG 5
#define MUG_NOAH_SAUER 6
#define MUG_NOAH_WUT 7
#define MUG_NOAH_GRINSEN 8
#define MUG_EMMA_NORMAL 9
#define MUG_EMMA_LACHEN 10
#define MUG_EMMA_BESCHEIDEN 11
#define MUG_EMMA_ERSTAUNT 12
#define MUG_EMMA_TRAURIG 13
#define MUG_EMMA_SAUER 14
#define MUG_EMMA_WUT 15
#define MUG_EMMA_GRINSEN 16
#define MUG_LINDA_NORMAL 17
#define MUG_LINDA_LACHEN 18
#define MUG_LINDA_BESCHEIDEN 19
#define MUG_IDAN_NORMAL 20
#define MUG_IDAN_ERSTAUNT 21
#define MUG_IDAN_STUTZIG 22
#define MUG_IDAN_TRAURIG 23
#define MUG_ACHIM_NORMAL 24
#define MUG_ACHIM_GRINSEN 25
#define MUG_ACHIM_TRAURIG 26
#define MUG_NORMAN_NORMAL 27
#define MUG_NORMAN_GRINSEN 28
#define MUG_NORMAN_LACHEN 29
#define MUG_JANA_NORMAL 30
#define MUG_JANA_GRINSEN 31
#define MUG_JANA_LACHEN 32
#define MUG_MARKUS_NORMAL 33
#define MUG_MARKUS_NACHDENKEN 34
#define MUG_ISABELLE_NORMAL 35
#define MUG_ISABELLE_NACHDENKEN 36
#define MUG_DIANA_NORMAL 37

#endif /* MUG_IDS_H */