#ifndef TRAINERID_IDS_H_
#define TRAINERID_IDS_H_

#define TRAINER_RIVALE_M_KAMPF_1  0x1
#define TRAINER_RIVALE_F_KAMPF_1  0x4
#define TRAINER_TT_NADINE_KAMPF_1 0x7


#endif /* TRAINERID_IDS_H */