@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_008
	.align	2

bank_008:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_051
	.byte	255, 0, 224, 165

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_035
	.byte	255, 0, 218, 165

@**************** Voice 002 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 003 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_006
	.word	map_002

@**************** Voice 004 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_020
	.byte	255, 178, 180, 165

@**************** Voice 005 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 006 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 007 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 008 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 009 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 010 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 011 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_008
	.byte	255, 165, 51, 235

@**************** Voice 012 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 013 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 014 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 015 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_030
	.byte	255, 235, 0, 204

@**************** Voice 016 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 017 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 018 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 019 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 020 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 021 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 022 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 023 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 024 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 025 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 026 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 027 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 028 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 029 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 030 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 031 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 032 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 033 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 034 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 035 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 036 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 037 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 038 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 039 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 040 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 041 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 042 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 043 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 044 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 045 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 046 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 047 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 048 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_029
	.byte	255, 242, 0, 204

@**************** Voice 049 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_002
	.byte	255, 246, 0, 226

@**************** Voice 050 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_001
	.word	map_000

@**************** Voice 051 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 052 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 053 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 054 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 055 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 056 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 057 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 058 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_007
	.word	map_003

@**************** Voice 059 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 060 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_004
	.word	map_001

@**************** Voice 061 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 062 ****************@

	.byte	KeySplit
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	bank_008
	.word	map_004

@**************** Voice 063 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 064 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 065 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 066 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 067 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 068 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 069 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 070 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 071 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 072 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 073 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 074 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 075 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_076
	.byte	255, 127, 231, 127

@**************** Voice 076 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 077 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 078 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 079 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 080 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 081 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 082 ****************@

	.byte	ASquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 7, 1

@**************** Voice 083 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 7, 1

@**************** Voice 084 ****************@

	.byte	ASquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 1, 7, 1

@**************** Voice 085 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 1, 7, 1

@**************** Voice 086 ****************@

	.byte	ASquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 4, 1

@**************** Voice 087 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 4, 1

@**************** Voice 088 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 089 ****************@

	.byte	AProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 7, 15, 2

@**************** Voice 090 ****************@

	.byte	AProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 7, 15, 2

@**************** Voice 091 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 092 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 4, 1

@**************** Voice 093 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 4, 1

@**************** Voice 094 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 095 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 096 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 097 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 098 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 099 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0



	.end
