@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	drums_000
	.align	2

drums_000:

@**************** Voice 000 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 001 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 002 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 003 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 004 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 005 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 006 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 007 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 008 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 6, 0

@**************** Voice 009 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 010 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 011 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_004
	.byte	0, 7, 15, 1

@**************** Voice 012 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 013 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 014 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 015 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 016 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 017 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 018 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 6, 0

@**************** Voice 019 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_002
	.byte	0, 7, 15, 1

@**************** Voice 020 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 6, 0

@**************** Voice 021 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 1, 6, 0

@**************** Voice 022 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 023 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 024 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 025 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 1, 6, 0

@**************** Voice 026 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 027 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 028 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_052
	.byte	255, 0, 255, 0

@**************** Voice 029 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_053
	.byte	255, 165, 154, 127

@**************** Voice 030 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_054
	.byte	255, 165, 154, 127

@**************** Voice 031 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_055
	.byte	255, 165, 206, 127

@**************** Voice 032 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_056
	.byte	255, 165, 206, 127

@**************** Voice 033 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_057
	.byte	255, 0, 255, 0

@**************** Voice 034 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_045
	.byte	255, 0, 255, 0

@**************** Voice 035 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_046
	.byte	255, 0, 255, 0

@**************** Voice 036 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_058
	.byte	255, 0, 255, 242

@**************** Voice 037 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 038 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_017
	.byte	255, 0, 255, 242

@**************** Voice 039 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_033
	.byte	255, 255, 255, 127

@**************** Voice 040 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_014
	.byte	255, 0, 255, 242

@**************** Voice 041 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 042 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 043 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 044 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 045 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 046 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 047 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 048 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 049 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 050 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 051 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 052 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 053 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 054 ****************@

	.byte	DirectSoundFix
	.byte	Gs0 
	.byte	0x00
	.byte	c_v-30
	.word	wave_059
	.byte	255, 127, 77, 204

@**************** Voice 055 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-50
	.word	wave_060
	.byte	255, 235, 0, 165

@**************** Voice 056 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 057 ****************@

	.byte	DirectSoundFix
	.byte	Fs0 
	.byte	0x00
	.byte	c_v-10
	.word	wave_031
	.byte	255, 246, 0, 216

@**************** Voice 058 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 059 ****************@

	.byte	DirectSoundFix
	.byte	Fs0 
	.byte	0x00
	.byte	c_v-10
	.word	wave_031
	.byte	255, 246, 0, 216

@**************** Voice 060 ****************@

	.byte	DirectSoundFix
	.byte	Fs0 
	.byte	0x00
	.byte	c_v+0
	.word	wave_031
	.byte	8, 0, 255, 216

@**************** Voice 061 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 062 ****************@

	.byte	DirectSoundFix
	.byte	Cn4 
	.byte	0x00
	.byte	c_v+40
	.word	wave_039
	.byte	255, 0, 255, 0

@**************** Voice 063 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 064 ****************@

	.byte	DirectSoundFix
	.byte	Cn4 
	.byte	0x00
	.byte	c_v+30
	.word	wave_040
	.byte	255, 0, 255, 0

@**************** Voice 065 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_061
	.byte	255, 0, 255, 0

@**************** Voice 066 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_062
	.byte	255, 180, 175, 228

@**************** Voice 067 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_062
	.byte	255, 0, 255, 242

@**************** Voice 068 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-10
	.word	wave_033
	.byte	255, 255, 255, 127

@**************** Voice 069 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_014
	.byte	255, 0, 255, 242

@**************** Voice 070 ****************@

	.byte	DirectSound
	.byte	En3 
	.byte	0x00
	.byte	c_v-40
	.word	wave_063
	.byte	255, 0, 255, 226

@**************** Voice 071 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+16
	.word	wave_014
	.byte	255, 0, 255, 242

@**************** Voice 072 ****************@

	.byte	DirectSound
	.byte	Gs3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_063
	.byte	255, 0, 255, 226

@**************** Voice 073 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_017
	.byte	255, 0, 255, 242

@**************** Voice 074 ****************@

	.byte	DirectSound
	.byte	Cn4 
	.byte	0x00
	.byte	c_v-20
	.word	wave_063
	.byte	255, 0, 255, 226

@**************** Voice 075 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 076 ****************@

	.byte	DirectSound
	.byte	En4 
	.byte	0x00
	.byte	c_v+20
	.word	wave_063
	.byte	255, 0, 255, 226

@**************** Voice 077 ****************@

	.byte	DirectSound
	.byte	Gs4 
	.byte	0x00
	.byte	c_v+30
	.word	wave_063
	.byte	255, 0, 255, 226

@**************** Voice 078 ****************@

	.byte	DirectSoundFix
	.byte	An0 
	.byte	0x00
	.byte	c_v+25
	.word	wave_031
	.byte	255, 235, 0, 231

@**************** Voice 079 ****************@

	.byte	DirectSound
	.byte	Cn5 
	.byte	0x00
	.byte	c_v+40
	.word	wave_063
	.byte	255, 0, 255, 235

@**************** Voice 080 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 081 ****************@

	.byte	DirectSound
	.byte	Ds3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_031
	.byte	255, 235, 0, 231

@**************** Voice 082 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-40
	.word	wave_041
	.byte	255, 165, 103, 231

@**************** Voice 083 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_059
	.byte	255, 127, 77, 204

@**************** Voice 084 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-50
	.word	wave_060
	.byte	255, 231, 0, 188

@**************** Voice 085 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_064
	.byte	255, 0, 255, 242

@**************** Voice 086 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-35
	.word	wave_031
	.byte	255, 235, 0, 231

@**************** Voice 087 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 088 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-10
	.word	wave_031
	.byte	255, 235, 0, 231

@**************** Voice 089 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-10
	.word	wave_031
	.byte	8, 0, 255, 216

@**************** Voice 090 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+30
	.word	wave_065
	.byte	255, 0, 255, 0

@**************** Voice 091 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_039
	.byte	255, 0, 255, 0

@**************** Voice 092 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_040
	.byte	255, 0, 255, 0

@**************** Voice 093 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+26
	.word	wave_040
	.byte	255, 0, 255, 0

@**************** Voice 094 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 095 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 096 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 097 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 098 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 099 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 100 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 101 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 102 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 103 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 104 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 105 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 106 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 107 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 108 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 109 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-25
	.word	wave_042
	.byte	255, 242, 103, 188

@**************** Voice 110 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+15
	.word	wave_042
	.byte	255, 242, 103, 188

@**************** Voice 111 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-25
	.word	wave_042
	.byte	255, 165, 103, 188

@**************** Voice 112 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v-40
	.word	wave_066
	.byte	255, 0, 255, 0

@**************** Voice 113 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 114 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 115 ****************@

	.byte	DirectSoundFix
	.byte	En3 
	.byte	0x00
	.byte	c_v+40
	.word	wave_067
	.byte	255, 0, 255, 0

@**************** Voice 116 ****************@

	.byte	DirectSound
	.byte	Ds3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_068
	.byte	255, 0, 255, 0

@**************** Voice 117 ****************@

	.byte	DirectSound
	.byte	Dn2 
	.byte	0x00
	.byte	c_v+20
	.word	wave_069
	.byte	255, 0, 255, 0

@**************** Voice 118 ****************@

	.byte	DirectSound
	.byte	En3 
	.byte	0x00
	.byte	c_v+20
	.word	wave_069
	.byte	255, 0, 255, 0

@**************** Voice 119 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_070
	.byte	255, 252, 0, 239

@**************** Voice 120 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_071
	.byte	255, 250, 0, 221

@**************** Voice 121 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_072
	.byte	255, 250, 0, 221

@**************** Voice 122 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_073
	.byte	255, 247, 0, 221

@**************** Voice 123 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_003
	.byte	255, 0, 255, 196

@**************** Voice 124 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_004
	.byte	255, 0, 255, 196

@**************** Voice 125 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_005
	.byte	255, 0, 255, 196

@**************** Voice 126 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_006
	.byte	255, 0, 193, 127

@**************** Voice 127 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_074
	.byte	255, 0, 193, 127



	.end
