#ifndef EGGGROUP_S_
#define EGGGROUP_S_

#define EGGGROUP_MONSTER 0x1
#define EGGGROUP_WASSER1 0x2
#define EGGGROUP_KAEFER 0x3
#define EGGGROUP_FLUG 0x4
#define EGGGROUP_FELD 0x5
#define EGGGROUP_FEE 0x6
#define EGGGROUP_GRASS 0x7
#define EGGGROUP_HUMANOTYP 0x8
#define EGGGROUP_WASSER3 0x9
#define EGGGROUP_MINERAL 0xA
#define EGGGROUP_AMORPH 0xB
#define EGGGROUP_WASSER2 0xC
#define EGGGROUP_DITTO 0xD
#define EGGGROUP_DRACHE 0xE
#define EGGGROUP_UNBEKANNT 0xF

#endif