@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_010_grp, bank_000
	.equ	seq_010_pri, 4
	.equ	seq_010_rev, 178
	.equ	seq_010_mvl, 127
	.equ	seq_010_key, 0

	.section .rodata
	.global	seq_010
	.align	2

@*********************** Track 01 ***********************@

seq_010_0:
	.byte	KEYSH , seq_010_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 85
	.byte		VOL   , 100*seq_010_mvl/mxv
	.byte		BEND  , c_v-6
	.byte		N02   , Ds2 , v052
	.byte	W02
	.byte		VOICE , 86
	.byte		N06   , Gn3 , v092
	.byte	W01
	.byte	W03
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_010:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_010_pri	@ Priority
	.byte	seq_010_rev	@ Reverb

	.word	seq_010_grp

	.word	seq_010_0

	.end
