@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_187_grp, bank_002
	.equ	seq_187_pri, 4
	.equ	seq_187_rev, 178
	.equ	seq_187_mvl, 127
	.equ	seq_187_key, 0

	.section .rodata
	.global	seq_187
	.align	2

@*********************** Track 01 ***********************@

seq_187_0:
	.byte	KEYSH , seq_187_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 56
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 65*seq_187_mvl/mxv
	.byte		BEND  , c_v+8
	.byte		N01   , Cs6 , v112
	.byte	W01
	.byte		BEND  , c_v+0
	.byte		N01   , Dn6 , v100
	.byte	W01
	.byte		        Dn6 , v060
	.byte	W04
	.byte		BEND  , c_v-8
	.byte		N01   , Ds6 , v112
	.byte	W01
	.byte		BEND  , c_v+0
	.byte		N01   , En6 , v100
	.byte	W01
	.byte		        En6 , v060
	.byte	W04
	.byte	FINE

@******************************************************@

	.align	2

seq_187:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_187_pri	@ Priority
	.byte	seq_187_rev	@ Reverb

	.word	seq_187_grp

	.word	seq_187_0

	.end
