@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_045_grp, bank_000
	.equ	seq_045_pri, 4
	.equ	seq_045_rev, 178
	.equ	seq_045_mvl, 127
	.equ	seq_045_key, 0

	.section .rodata
	.global	seq_045
	.align	2

@*********************** Track 01 ***********************@

seq_045_0:
	.byte	KEYSH , seq_045_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 120
	.byte		VOL   , 127*seq_045_mvl/mxv
	.byte		N06   , Bn3 , v028
	.byte	W03
	.byte	W03
	.byte		N21   , Gs4 
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_045:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_045_pri	@ Priority
	.byte	seq_045_rev	@ Reverb

	.word	seq_045_grp

	.word	seq_045_0

	.end
