@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_078_grp, bank_002
	.equ	seq_078_pri, 2
	.equ	seq_078_rev, 178
	.equ	seq_078_mvl, 127
	.equ	seq_078_key, 0

	.section .rodata
	.global	seq_078
	.align	2

@*********************** Track 01 ***********************@

seq_078_0:
	.byte	KEYSH , seq_078_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 36
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 15*seq_078_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N24   , Bn3 , v052
	.byte	W03
	.byte		VOL   , 27*seq_078_mvl/mxv
	.byte	W03
	.byte		        39*seq_078_mvl/mxv
	.byte	W03
	.byte		        44*seq_078_mvl/mxv
	.byte	W03
	.byte		        52*seq_078_mvl/mxv
	.byte	W03
	.byte		        59*seq_078_mvl/mxv
	.byte	W03
	.byte		        68*seq_078_mvl/mxv
	.byte	W03
	.byte		        80*seq_078_mvl/mxv
	.byte	W03
	.byte		N60   , Bn3 , v052
	.byte	W24
	.byte	W24
	.byte	W12
	.byte	GOTO
	 .word	seq_078_0 + 0x21
	.byte	FINE

@******************************************************@

	.align	2

seq_078:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_078_pri	@ Priority
	.byte	seq_078_rev	@ Reverb

	.word	seq_078_grp

	.word	seq_078_0

	.end
