@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_042_grp, bank_002
	.equ	seq_042_pri, 4
	.equ	seq_042_rev, 178
	.equ	seq_042_mvl, 127
	.equ	seq_042_key, 0

	.section .rodata
	.global	seq_042
	.align	2

@*********************** Track 01 ***********************@

seq_042_0:
	.byte	KEYSH , seq_042_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 9
	.byte		VOL   , 90*seq_042_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N03   , Gn4 , v112
	.byte	W03
	.byte		        Dn4 
	.byte	W03
	.byte		        Gn4 
	.byte	W03
	.byte		N21   , Gn5 
	.byte	W03
	.byte	W03
	.byte		VOL   , 81*seq_042_mvl/mxv
	.byte		BEND  , c_v+6
	.byte	W03
	.byte		VOL   , 72*seq_042_mvl/mxv
	.byte		BEND  , c_v+20
	.byte	W03
	.byte		VOL   , 46*seq_042_mvl/mxv
	.byte		BEND  , c_v+37
	.byte	W03
	.byte		VOL   , 24*seq_042_mvl/mxv
	.byte		BEND  , c_v+63
	.byte	W03
	.byte		VOL   , 7*seq_042_mvl/mxv
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_042:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_042_pri	@ Priority
	.byte	seq_042_rev	@ Reverb

	.word	seq_042_grp

	.word	seq_042_0

	.end
