@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_107_grp, bank_002
	.equ	seq_107_pri, 5
	.equ	seq_107_rev, 178
	.equ	seq_107_mvl, 127
	.equ	seq_107_key, 0

	.section .rodata
	.global	seq_107
	.align	2

@*********************** Track 01 ***********************@

seq_107_0:
	.byte	KEYSH , seq_107_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 36
	.byte		BENDR , 12
	.byte		PAN   , c_v-32
	.byte		VOL   , 16*seq_107_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		N09   , Gn5 , v032
	.byte	W01
	.byte		VOL   , 63*seq_107_mvl/mxv
	.byte	W01
	.byte		        98*seq_107_mvl/mxv
	.byte	W01
	.byte		        110*seq_107_mvl/mxv
	.byte	W01
	.byte		        99*seq_107_mvl/mxv
	.byte		BEND  , c_v+5
	.byte	W02
	.byte		VOL   , 63*seq_107_mvl/mxv
	.byte		BEND  , c_v+13
	.byte	W01
	.byte		VOL   , 22*seq_107_mvl/mxv
	.byte		BEND  , c_v+21
	.byte	W01
	.byte		VOL   , 9*seq_107_mvl/mxv
	.byte		BEND  , c_v+33
	.byte	W04
	.byte	FINE

@*********************** Track 02 ***********************@

seq_107_1:
	.byte	KEYSH , seq_107_key+0
	.byte		VOICE , 71
	.byte		PAN   , c_v+32
	.byte		VOL   , 110*seq_107_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		N09   , Fs4 , v060
	.byte	W06
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_107:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_107_pri	@ Priority
	.byte	seq_107_rev	@ Reverb

	.word	seq_107_grp

	.word	seq_107_0
	.word	seq_107_1

	.end
