@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_186_grp, bank_002
	.equ	seq_186_pri, 4
	.equ	seq_186_rev, 178
	.equ	seq_186_mvl, 127
	.equ	seq_186_key, 0

	.section .rodata
	.global	seq_186
	.align	2

@*********************** Track 01 ***********************@

seq_186_0:
	.byte	KEYSH , seq_186_key+0
	.byte	TEMPO , 190/2
	.byte		VOICE , 2
	.byte		BENDR , 8
	.byte		PAN   , c_v+0
	.byte		VOL   , 28*seq_186_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N15   , An1 , v127
	.byte	W01
	.byte		VOL   , 60*seq_186_mvl/mxv
	.byte	W01
	.byte		        111*seq_186_mvl/mxv
	.byte	W01
	.byte		        120*seq_186_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-3
	.byte	W02
	.byte		PAN   , c_v+5
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		VOL   , 109*seq_186_mvl/mxv
	.byte		PAN   , c_v+9
	.byte		BEND  , c_v-10
	.byte	W01
	.byte		PAN   , c_v-9
	.byte		BEND  , c_v-14
	.byte	W01
	.byte		VOL   , 95*seq_186_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v-19
	.byte	W02
	.byte		VOL   , 71*seq_186_mvl/mxv
	.byte		BEND  , c_v-29
	.byte	W01
	.byte		VOL   , 41*seq_186_mvl/mxv
	.byte		BEND  , c_v-38
	.byte	W01
	.byte		VOL   , 15*seq_186_mvl/mxv
	.byte		BEND  , c_v-52
	.byte	W04
	.byte	FINE

@******************************************************@

	.align	2

seq_186:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_186_pri	@ Priority
	.byte	seq_186_rev	@ Reverb

	.word	seq_186_grp

	.word	seq_186_0

	.end
