@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_064_grp, bank_002
	.equ	seq_064_pri, 4
	.equ	seq_064_rev, 178
	.equ	seq_064_mvl, 127
	.equ	seq_064_key, 0

	.section .rodata
	.global	seq_064
	.align	2

@*********************** Track 01 ***********************@

seq_064_0:
	.byte	KEYSH , seq_064_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 26
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 95*seq_064_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N01   , Cn3 , v127
	.byte	W03
	.byte	W03
	.byte		        Gn3 
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_064:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_064_pri	@ Priority
	.byte	seq_064_rev	@ Reverb

	.word	seq_064_grp

	.word	seq_064_0

	.end
