@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_003_grp, bank_000
	.equ	seq_003_pri, 5
	.equ	seq_003_rev, 178
	.equ	seq_003_mvl, 127
	.equ	seq_003_key, 0

	.section .rodata
	.global	seq_003
	.align	2

@*********************** Track 01 ***********************@

seq_003_0:
	.byte	KEYSH , seq_003_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 6
	.byte		VOL   , 100*seq_003_mvl/mxv
	.byte		BEND  , c_v-8
	.byte		N04   , Cn3 , v112
	.byte	W04
	.byte		        Cn2 
	.byte	W02
	.byte	W02
	.byte		        Cn1 
	.byte	W04
	.byte		        Cn1 , v024
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_003:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_003_pri	@ Priority
	.byte	seq_003_rev	@ Reverb

	.word	seq_003_grp

	.word	seq_003_0

	.end
