@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_180_grp, bank_002
	.equ	seq_180_pri, 4
	.equ	seq_180_rev, 178
	.equ	seq_180_mvl, 127
	.equ	seq_180_key, 0

	.section .rodata
	.global	seq_180
	.align	2

@*********************** Track 01 ***********************@

seq_180_0:
	.byte	KEYSH , seq_180_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 24
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 110*seq_180_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N01   , Cn5 , v127
	.byte	W01
	.byte		PAN   , c_v+10
	.byte		N01   , Cn6 
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		N01   , Cn5 
	.byte	W04
	.byte		N01
	.byte	W01
	.byte		PAN   , c_v-11
	.byte		N01   , Cn6 
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		N01   , Cn5 
	.byte	W04
	.byte	FINE

@******************************************************@

	.align	2

seq_180:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_180_pri	@ Priority
	.byte	seq_180_rev	@ Reverb

	.word	seq_180_grp

	.word	seq_180_0

	.end
