@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_174_grp, bank_002
	.equ	seq_174_pri, 4
	.equ	seq_174_rev, 178
	.equ	seq_174_mvl, 127
	.equ	seq_174_key, 0

	.section .rodata
	.global	seq_174
	.align	2

@*********************** Track 01 ***********************@

seq_174_0:
	.byte		VOL   , 110*seq_174_mvl/mxv
	.byte	KEYSH , seq_174_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 44
	.byte		BENDR , 2
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N21   , Fs5 , v112
	.byte	W01
	.byte		PAN   , c_v-5
	.byte	W01
	.byte		        c_v-10
	.byte		VOL   , 15*seq_174_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v-4
	.byte		VOL   , 41*seq_174_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		VOL   , 69*seq_174_mvl/mxv
	.byte	W02
	.byte		PAN   , c_v+4
	.byte	W01
	.byte		        c_v+10
	.byte		VOL   , 84*seq_174_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+4
	.byte	W01
	.byte		VOL   , 97*seq_174_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		        c_v-5
	.byte	W02
	.byte		VOL   , 110*seq_174_mvl/mxv
	.byte		PAN   , c_v-10
	.byte	W01
	.byte		        c_v-4
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+10
	.byte	W02
	.byte		VOL   , 100*seq_174_mvl/mxv
	.byte		PAN   , c_v+4
	.byte	W01
	.byte		VOL   , 84*seq_174_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		VOL   , 55*seq_174_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+0
	.byte	W02
	.byte	FINE

@*********************** Track 02 ***********************@

seq_174_1:
	.byte		VOL   , 110*seq_174_mvl/mxv
	.byte	KEYSH , seq_174_key+0
	.byte		VOICE , 42
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N21   , Fn6 , v064
	.byte	W06
	.byte		PAN   , c_v+0
	.byte	W03
	.byte		        c_v+0
	.byte	W03
	.byte	W03
	.byte		        c_v+0
	.byte	W03
	.byte	W01
	.byte		        c_v+0
	.byte	W03
	.byte		BEND  , c_v+0
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_174:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_174_pri	@ Priority
	.byte	seq_174_rev	@ Reverb

	.word	seq_174_grp

	.word	seq_174_0
	.word	seq_174_1

	.end
