@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_022_grp, bank_000
	.equ	seq_022_pri, 4
	.equ	seq_022_rev, 178
	.equ	seq_022_mvl, 127
	.equ	seq_022_key, 0

	.section .rodata
	.global	seq_022
	.align	2

@*********************** Track 01 ***********************@

seq_022_0:
	.byte	KEYSH , seq_022_key+0
	.byte	TEMPO , 100/2
	.byte		VOICE , 5
	.byte		BENDR , 12
	.byte		VOL   , 110*seq_022_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N03   , Cn3 , v127
	.byte	W03
	.byte		        Cn2 , v112
	.byte	W03
	.byte	W03
	.byte		        Cn2 , v024
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_022:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_022_pri	@ Priority
	.byte	seq_022_rev	@ Reverb

	.word	seq_022_grp

	.word	seq_022_0

	.end
