@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_129_grp, bank_002
	.equ	seq_129_pri, 4
	.equ	seq_129_rev, 178
	.equ	seq_129_mvl, 127
	.equ	seq_129_key, 0

	.section .rodata
	.global	seq_129
	.align	2

@*********************** Track 01 ***********************@

seq_129_0:
	.byte	KEYSH , seq_129_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 18
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 110*seq_129_mvl/mxv
	.byte		PAN   , c_v+14
	.byte		BEND  , c_v+0
	.byte		N09   , Cn5 , v092
	.byte	W03
	.byte		PAN   , c_v-15
	.byte		BEND  , c_v-32
	.byte	W03
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+28
	.byte	W03
	.byte		VOICE , 2
	.byte		BEND  , c_v-64
	.byte		N21   , Bn2 , v108
	.byte	W03
	.byte		BEND  , c_v-55
	.byte	W03
	.byte		PAN   , c_v+4
	.byte		BEND  , c_v-45
	.byte	W03
	.byte		PAN   , c_v-5
	.byte		BEND  , c_v+30
	.byte	W03
	.byte		PAN   , c_v+15
	.byte		BEND  , c_v+39
	.byte	W03
	.byte		PAN   , c_v-15
	.byte		BEND  , c_v+54
	.byte	W03
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+63
	.byte	W21
	.byte	FINE

@*********************** Track 02 ***********************@

seq_129_1:
	.byte	KEYSH , seq_129_key+0
	.byte		VOICE , 5
	.byte		PAN   , c_v+0
	.byte		VOL   , 110*seq_129_mvl/mxv
	.byte		N06   , Fn3 , v040
	.byte	W09
	.byte		N24   , Gn3 
	.byte	W15
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_129:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_129_pri	@ Priority
	.byte	seq_129_rev	@ Reverb

	.word	seq_129_grp

	.word	seq_129_0
	.word	seq_129_1

	.end
