@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_102_grp, bank_000
	.equ	seq_102_pri, 5
	.equ	seq_102_rev, 178
	.equ	seq_102_mvl, 127
	.equ	seq_102_key, 0

	.section .rodata
	.global	seq_102
	.align	2

@*********************** Track 01 ***********************@

seq_102_0:
	.byte	KEYSH , seq_102_key+0
	.byte	TEMPO , 100/2
	.byte		VOICE , 4
	.byte		BENDR , 12
	.byte		XCMD  , xIECV , 10
	.byte		        xIECL , 8
	.byte		VOL   , 90*seq_102_mvl/mxv
	.byte		BEND  , c_v+4
	.byte		N01   , Cn5 , v064
	.byte	W01
	.byte		        Cn5 , v020
	.byte	W01
	.byte		        Cn5 , v064
	.byte	W01
	.byte		        Cn5 , v020
	.byte	W01
	.byte		        Cn6 , v064
	.byte	W02
	.byte		        Cn6 , v020
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_102:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_102_pri	@ Priority
	.byte	seq_102_rev	@ Reverb

	.word	seq_102_grp

	.word	seq_102_0

	.end
