@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_325_grp, bank_062
	.equ	seq_325_pri, 0
	.equ	seq_325_rev, 178
	.equ	seq_325_mvl, 127
	.equ	seq_325_key, 0

	.section .rodata
	.global	seq_325
	.align	2

@*********************** Track 01 ***********************@

seq_325_0:
	.byte	KEYSH , seq_325_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 56
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		PAN   , c_v+28
	.byte		VOL   , 67*seq_325_mvl/mxv
	.byte	W24
	.byte		N06   , Gn3 , v120
	.byte	W24
	.byte	W48
	.byte	FINE

@*********************** Track 02 ***********************@

seq_325_1:
	.byte	KEYSH , seq_325_key+0
	.byte		VOICE , 60
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 81*seq_325_mvl/mxv
	.byte	W24
	.byte		N06   , Bn3 , v120
	.byte	W24
	.byte	W48
	.byte	FINE

@*********************** Track 03 ***********************@

seq_325_2:
	.byte	KEYSH , seq_325_key+0
	.byte		VOICE , 58
	.byte		BENDR , 12
	.byte		LFOS  , 44
	.byte		VOL   , 88*seq_325_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N24   , Fs1 , v120
	.byte	W48
	.byte	W48
	.byte	FINE

@*********************** Track 04 ***********************@

seq_325_3:
	.byte	KEYSH , seq_325_key+0
	.byte		VOICE , 48
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		PAN   , c_v-24
	.byte		VOL   , 67*seq_325_mvl/mxv
	.byte	W24
	.byte		N06   , Bn2 , v120
	.byte	W24
	.byte	W48
	.byte	FINE

@*********************** Track 05 ***********************@

seq_325_4:
	.byte	KEYSH , seq_325_key+0
	.byte		VOICE , 47
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		VOL   , 86*seq_325_mvl/mxv
	.byte		PAN   , c_v+2
	.byte	W24
	.byte		N15   , Gn2 , v120
	.byte	W24
	.byte	W48
	.byte	FINE

@*********************** Track 06 ***********************@

seq_325_5:
	.byte	KEYSH , seq_325_key+0
	.byte		VOICE , 81
	.byte		LFOS  , 44
	.byte		XCMD  , xIECV , 18
	.byte		        xIECV , 16
	.byte		BENDR , 12
	.byte		VOL   , 50*seq_325_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N24   , Fs1 , v120
	.byte	W24
	.byte		N06   , Gn1 
	.byte	W24
	.byte	W48
	.byte	FINE

@*********************** Track 07 ***********************@

seq_325_6:
	.byte	KEYSH , seq_325_key+0
	.byte		VOICE , 0
	.byte		VOL   , 86*seq_325_mvl/mxv
	.byte		N03   , En1 , v120
	.byte	W03
	.byte		        En1 , v048
	.byte	W03
	.byte		N03
	.byte	W03
	.byte		N03
	.byte	W03
	.byte		N03
	.byte	W03
	.byte		N03
	.byte	W03
	.byte		N03
	.byte	W03
	.byte		N03
	.byte	W03
	.byte		N06   , En1 , v120
	.byte		N48   , An2 , v096
	.byte	W24
	.byte	W48
	.byte	FINE

@******************************************************@

	.align	2

seq_325:
	.byte	7	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_325_pri	@ Priority
	.byte	seq_325_rev	@ Reverb

	.word	seq_325_grp

	.word	seq_325_0
	.word	seq_325_1
	.word	seq_325_2
	.word	seq_325_3
	.word	seq_325_4
	.word	seq_325_5
	.word	seq_325_6

	.end
