@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_130_grp, bank_002
	.equ	seq_130_pri, 4
	.equ	seq_130_rev, 178
	.equ	seq_130_mvl, 127
	.equ	seq_130_key, 0

	.section .rodata
	.global	seq_130
	.align	2

@*********************** Track 01 ***********************@

seq_130_0:
	.byte	KEYSH , seq_130_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 3
	.byte		VOL   , 100*seq_130_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N01   , Ds4 , v112
	.byte	W04
	.byte		PAN   , c_v+6
	.byte		N01   , Bn4 , v040
	.byte	W04
	.byte		PAN   , c_v-5
	.byte		N01   , Ds4 , v112
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		N01   , Bn4 
	.byte	W03
	.byte	FINE

@*********************** Track 02 ***********************@

seq_130_1:
	.byte	KEYSH , seq_130_key+0
	.byte		VOICE , 5
	.byte		VOL   , 100*seq_130_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N01   , Dn4 , v040
	.byte	W04
	.byte		        Bn3 
	.byte	W02
	.byte		PAN   , c_v-7
	.byte	W02
	.byte		        c_v+9
	.byte	W01
	.byte		N01   , Dn4 
	.byte	W01
	.byte		PAN   , c_v-7
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_130:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_130_pri	@ Priority
	.byte	seq_130_rev	@ Reverb

	.word	seq_130_grp

	.word	seq_130_0
	.word	seq_130_1

	.end
