@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_126_grp, bank_002
	.equ	seq_126_pri, 4
	.equ	seq_126_rev, 178
	.equ	seq_126_mvl, 127
	.equ	seq_126_key, 0

	.section .rodata
	.global	seq_126
	.align	2

@*********************** Track 01 ***********************@

seq_126_0:
	.byte	KEYSH , seq_126_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 22
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 110*seq_126_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N24   , Cn3 , v108
	.byte	W02
	.byte		PAN   , c_v-19
	.byte	W04
	.byte		        c_v+0
	.byte	W01
	.byte		VOL   , 97*seq_126_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+16
	.byte	W01
	.byte		VOL   , 84*seq_126_mvl/mxv
	.byte	W03
	.byte		        76*seq_126_mvl/mxv
	.byte		PAN   , c_v+2
	.byte	W02
	.byte		VOL   , 55*seq_126_mvl/mxv
	.byte		PAN   , c_v-8
	.byte	W02
	.byte		VOL   , 39*seq_126_mvl/mxv
	.byte	W02
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		VOL   , 25*seq_126_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+8
	.byte	W01
	.byte		VOL   , 13*seq_126_mvl/mxv
	.byte	W03
	.byte		        7*seq_126_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_126:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_126_pri	@ Priority
	.byte	seq_126_rev	@ Reverb

	.word	seq_126_grp

	.word	seq_126_0

	.end
