@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_035_grp, bank_002
	.equ	seq_035_pri, 4
	.equ	seq_035_rev, 178
	.equ	seq_035_mvl, 127
	.equ	seq_035_key, 0

	.section .rodata
	.global	seq_035
	.align	2

@*********************** Track 01 ***********************@

seq_035_0:
	.byte	KEYSH , seq_035_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 3
	.byte		VOL   , 100*seq_035_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N01   , Gn3 , v120
	.byte	W03
	.byte	W01
	.byte		        Cn4 
	.byte	W01
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		        c_v+22
	.byte	W01
	.byte		N01   , Cn5 , v112
	.byte	W01
	.byte		BEND  , c_v+35
	.byte	W01
	.byte	W01
	.byte		        c_v+46
	.byte	W01
	.byte		        c_v+54
	.byte		N01   , Cn4 , v104
	.byte	W01
	.byte	W01
	.byte		BEND  , c_v+63
	.byte	W01
	.byte		N01   , Cn5 , v096
	.byte	W01
	.byte	FINE

@*********************** Track 02 ***********************@

seq_035_1:
	.byte	KEYSH , seq_035_key+0
	.byte		VOICE , 4
	.byte		VOL   , 100*seq_035_mvl/mxv
	.byte		N01   , Gs3 , v064
	.byte	W03
	.byte	W01
	.byte		N01
	.byte	W02
	.byte		        Fn4 
	.byte	W03
	.byte		        Gs3 
	.byte	W03
	.byte		        Fn4 
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_035:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_035_pri	@ Priority
	.byte	seq_035_rev	@ Reverb

	.word	seq_035_grp

	.word	seq_035_0
	.word	seq_035_1

	.end
