@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_101_grp, bank_000
	.equ	seq_101_pri, 5
	.equ	seq_101_rev, 178
	.equ	seq_101_mvl, 127
	.equ	seq_101_key, 0

	.section .rodata
	.global	seq_101
	.align	2

@*********************** Track 01 ***********************@

seq_101_0:
	.byte	KEYSH , seq_101_key+0
	.byte	TEMPO , 100/2
	.byte		VOICE , 4
	.byte		BENDR , 12
	.byte		XCMD  , xIECV , 10
	.byte		        xIECL , 8
	.byte		VOL   , 40*seq_101_mvl/mxv
	.byte		BEND  , c_v+4
	.byte		N01   , Gn4 , v127
	.byte	W01
	.byte		        Gn4 , v020
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_101:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_101_pri	@ Priority
	.byte	seq_101_rev	@ Reverb

	.word	seq_101_grp

	.word	seq_101_0

	.end
