@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_002_grp, bank_000
	.equ	seq_002_pri, 5
	.equ	seq_002_rev, 178
	.equ	seq_002_mvl, 127
	.equ	seq_002_key, 0

	.section .rodata
	.global	seq_002
	.align	2

@*********************** Track 01 ***********************@

seq_002_0:
	.byte	KEYSH , seq_002_key+0
	.byte	TEMPO , 144/2
	.byte		VOICE , 4
	.byte		XCMD  , xIECV , 10
	.byte		        xIECL , 8
	.byte		VOL   , 100*seq_002_mvl/mxv
	.byte		BEND  , c_v-6
	.byte		N08   , Cn4 , v112
	.byte	W08
	.byte		N04   , Cn4 , v028
	.byte	W04
	.byte		N08   , Cn4 , v112
	.byte	W08
	.byte		N04   , Cn4 , v024
	.byte	W04
	.byte	FINE

@******************************************************@

	.align	2

seq_002:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_002_pri	@ Priority
	.byte	seq_002_rev	@ Reverb

	.word	seq_002_grp

	.word	seq_002_0

	.end
