@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_025_grp, bank_000
	.equ	seq_025_pri, 4
	.equ	seq_025_rev, 178
	.equ	seq_025_mvl, 127
	.equ	seq_025_key, 0

	.section .rodata
	.global	seq_025
	.align	2

@*********************** Track 01 ***********************@

seq_025_0:
	.byte	KEYSH , seq_025_key+0
	.byte	TEMPO , 240/2
	.byte		VOICE , 5
	.byte		BENDR , 12
	.byte		VOL   , 80*seq_025_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N06   , Gn5 , v127
	.byte	W06
	.byte		N18   , Ds5 
	.byte	W18
	.byte	FINE

@******************************************************@

	.align	2

seq_025:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_025_pri	@ Priority
	.byte	seq_025_rev	@ Reverb

	.word	seq_025_grp

	.word	seq_025_0

	.end
