@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_072_grp, bank_000
	.equ	seq_072_pri, 5
	.equ	seq_072_rev, 178
	.equ	seq_072_mvl, 127
	.equ	seq_072_key, 0

	.section .rodata
	.global	seq_072
	.align	2

@*********************** Track 01 ***********************@

seq_072_0:
	.byte	KEYSH , seq_072_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 16
	.byte		BENDR , 12
	.byte		VOL   , 110*seq_072_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N02   , Ds3 , v100
	.byte	W04
	.byte		N02
	.byte	W05
	.byte		N02
	.byte	W05
	.byte		N02
	.byte	W05
	.byte		N02
	.byte	W05
	.byte	FINE

@******************************************************@

	.align	2

seq_072:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_072_pri	@ Priority
	.byte	seq_072_rev	@ Reverb

	.word	seq_072_grp

	.word	seq_072_0

	.end
