@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_256_grp, bank_005
	.equ	seq_256_pri, 5
	.equ	seq_256_rev, 178
	.equ	seq_256_mvl, 127
	.equ	seq_256_key, 0

	.section .rodata
	.global	seq_256
	.align	2

@*********************** Track 01 ***********************@

seq_256_0:
	.byte	KEYSH , seq_256_key+0
	.byte	TEMPO , 132/2
	.byte		VOICE , 46
	.byte		VOL   , 90*seq_256_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N12   , Bn4 , v112
	.byte	W12
	.byte		N06   , Bn4 , v052
	.byte	W12
	.byte		N12   , Bn4 , v112
	.byte	W12
	.byte		N06   , Bn4 , v052
	.byte	W12
	.byte		N12   , Bn4 , v112
	.byte	W12
	.byte		        Gs4 
	.byte	W12
	.byte		        En5 
	.byte	W12
	.byte		N06   , En5 , v052
	.byte	W12
	.byte	W24
	.byte	FINE

@*********************** Track 02 ***********************@

seq_256_1:
	.byte	KEYSH , seq_256_key+0
	.byte		VOICE , 46
	.byte		VOL   , 90*seq_256_mvl/mxv
	.byte		PAN   , c_v+48
	.byte		N06   , En4 , v080
	.byte	W12
	.byte		        En4 , v020
	.byte	W12
	.byte		        En4 , v080
	.byte	W12
	.byte		        En4 , v020
	.byte	W12
	.byte		        En4 , v080
	.byte	W12
	.byte		        En4 , v020
	.byte	W12
	.byte		        Bn4 , v080
	.byte	W12
	.byte		        Bn4 , v020
	.byte	W12
	.byte	W24
	.byte	FINE

@*********************** Track 03 ***********************@

seq_256_2:
	.byte	KEYSH , seq_256_key+0
	.byte		VOICE , 46
	.byte		VOL   , 90*seq_256_mvl/mxv
	.byte		PAN   , c_v-47
	.byte	W12
	.byte		N06   , Gs3 , v080
	.byte	W12
	.byte		        Gs3 , v024
	.byte	W12
	.byte		        Gs3 , v080
	.byte	W12
	.byte		        Gs3 , v024
	.byte	W12
	.byte		        Gs3 , v080
	.byte	W12
	.byte		        En3 
	.byte	W12
	.byte		        En3 , v024
	.byte	W12
	.byte	W24
	.byte	FINE

@*********************** Track 04 ***********************@

seq_256_3:
	.byte		VOL   , 90*seq_256_mvl/mxv
	.byte	KEYSH , seq_256_key+0
	.byte		VOICE , 100
	.byte		PAN   , c_v+0
	.byte	W12
	.byte		N03   , En5 , v080
	.byte	W06
	.byte		PAN   , c_v-48
	.byte		N03   , En5 , v024
	.byte	W06
	.byte		PAN   , c_v+0
	.byte		N03   , En5 , v080
	.byte	W06
	.byte		PAN   , c_v+48
	.byte		N03   , En5 , v024
	.byte	W06
	.byte		VOICE , 101
	.byte		PAN   , c_v+0
	.byte		N03   , En4 , v080
	.byte	W06
	.byte		PAN   , c_v-48
	.byte		N03   , En4 , v024
	.byte	W30
	.byte		VOICE , 100
	.byte		PAN   , c_v+0
	.byte		N03   , En5 , v080
	.byte	W06
	.byte		PAN   , c_v+48
	.byte		N03   , En5 , v024
	.byte	W18
	.byte		PAN   , c_v+0
	.byte		N03   , En5 , v072
	.byte	W06
	.byte		        En5 , v028
	.byte	W18
	.byte	FINE

@******************************************************@

	.align	2

seq_256:
	.byte	4	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_256_pri	@ Priority
	.byte	seq_256_rev	@ Reverb

	.word	seq_256_grp

	.word	seq_256_0
	.word	seq_256_1
	.word	seq_256_2
	.word	seq_256_3

	.end
