@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_053_grp, bank_000
	.equ	seq_053_pri, 5
	.equ	seq_053_rev, 178
	.equ	seq_053_mvl, 127
	.equ	seq_053_key, 0

	.section .rodata
	.global	seq_053
	.align	2

@*********************** Track 01 ***********************@

seq_053_0:
	.byte	KEYSH , seq_053_key+0
	.byte		VOICE , 13
	.byte		BENDR , 12
	.byte		VOL   , 12*seq_053_mvl/mxv
	.byte		BEND  , c_v+49
	.byte		N06   , Gn4 , v080
	.byte	W01
	.byte		VOL   , 44*seq_053_mvl/mxv
	.byte		BEND  , c_v+22
	.byte	W01
	.byte		VOL   , 75*seq_053_mvl/mxv
	.byte		BEND  , c_v+20
	.byte	W01
	.byte		VOL   , 87*seq_053_mvl/mxv
	.byte		BEND  , c_v+33
	.byte	W01
	.byte		VOL   , 100*seq_053_mvl/mxv
	.byte		BEND  , c_v+54
	.byte	W01
	.byte		        c_v+63
	.byte	W01
	.byte	W03
	.byte		N03   , Gn4 , v040
	.byte	W03
	.byte	FINE

@*********************** Track 02 ***********************@

seq_053_1:
	.byte	KEYSH , seq_053_key+0
	.byte		VOICE , 123
	.byte		VOL   , 59*seq_053_mvl/mxv
	.byte		N06   , Gs4 , v052
	.byte	W01
	.byte		VOL   , 72*seq_053_mvl/mxv
	.byte	W01
	.byte		        90*seq_053_mvl/mxv
	.byte	W01
	.byte		        100*seq_053_mvl/mxv
	.byte	W03
	.byte	W03
	.byte		N03   , Gs4 , v024
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_053:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_053_pri	@ Priority
	.byte	seq_053_rev	@ Reverb

	.word	seq_053_grp

	.word	seq_053_0
	.word	seq_053_1

	.end
