@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_167_grp, bank_002
	.equ	seq_167_pri, 4
	.equ	seq_167_rev, 178
	.equ	seq_167_mvl, 127
	.equ	seq_167_key, 0

	.section .rodata
	.global	seq_167
	.align	2

@*********************** Track 01 ***********************@

seq_167_0:
	.byte	KEYSH , seq_167_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 39
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 95*seq_167_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N01   , An5 , v100
	.byte	W01
	.byte		        Fn5 , v064
	.byte	W01
	.byte		N06   , Gn5 , v100
	.byte	W01
	.byte		VOL   , 85*seq_167_mvl/mxv
	.byte		PAN   , c_v-13
	.byte	W01
	.byte		VOL   , 59*seq_167_mvl/mxv
	.byte		PAN   , c_v+11
	.byte	W02
	.byte		VOL   , 33*seq_167_mvl/mxv
	.byte		PAN   , c_v-14
	.byte	W01
	.byte		VOL   , 5*seq_167_mvl/mxv
	.byte		PAN   , c_v+11
	.byte	W03
	.byte		VOL   , 95*seq_167_mvl/mxv
	.byte		PAN   , c_v+1
	.byte		N01   , An5 
	.byte	W02
	.byte		        Fn5 , v064
	.byte	W01
	.byte		N19   , Gn5 , v100
	.byte	W01
	.byte		PAN   , c_v-13
	.byte	W01
	.byte		        c_v+11
	.byte	W01
	.byte		        c_v-14
	.byte	W02
	.byte		        c_v+11
	.byte	W01
	.byte		        c_v-13
	.byte	W01
	.byte		        c_v+11
	.byte		VOL   , 85*seq_167_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v-14
	.byte		VOL   , 77*seq_167_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+11
	.byte		VOL   , 69*seq_167_mvl/mxv
	.byte	W02
	.byte		PAN   , c_v-13
	.byte		VOL   , 59*seq_167_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+11
	.byte		VOL   , 52*seq_167_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v-14
	.byte		VOL   , 41*seq_167_mvl/mxv
	.byte	W01
	.byte		        33*seq_167_mvl/mxv
	.byte		PAN   , c_v+11
	.byte	W01
	.byte		VOL   , 23*seq_167_mvl/mxv
	.byte		PAN   , c_v-14
	.byte	W02
	.byte		VOL   , 14*seq_167_mvl/mxv
	.byte		PAN   , c_v+11
	.byte	W01
	.byte		VOL   , 5*seq_167_mvl/mxv
	.byte		PAN   , c_v-13
	.byte	W05
	.byte	FINE

@******************************************************@

	.align	2

seq_167:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_167_pri	@ Priority
	.byte	seq_167_rev	@ Reverb

	.word	seq_167_grp

	.word	seq_167_0

	.end
