@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_141_grp, bank_002
	.equ	seq_141_pri, 4
	.equ	seq_141_rev, 178
	.equ	seq_141_mvl, 127
	.equ	seq_141_key, 0

	.section .rodata
	.global	seq_141
	.align	2

@*********************** Track 01 ***********************@

seq_141_0:
	.byte	KEYSH , seq_141_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 31
	.byte		VOL   , 110*seq_141_mvl/mxv
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N02   , Dn2 , v127
	.byte	W01
	.byte		BEND  , c_v+32
	.byte	W01
	.byte		VOICE , 23
	.byte		BEND  , c_v+0
	.byte		N02   , Gn1 , v112
	.byte	W01
	.byte		PAN   , c_v+8
	.byte		BEND  , c_v+63
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N02   , Cn2 
	.byte	W02
	.byte		PAN   , c_v-7
	.byte		BEND  , c_v+16
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		N01
	.byte	W01
	.byte		PAN   , c_v+8
	.byte		N01   , Cn3 
	.byte	W01
	.byte		VOICE , 31
	.byte		PAN   , c_v-16
	.byte		N01   , Dn2 
	.byte	W02
	.byte		VOICE , 23
	.byte		PAN   , c_v+0
	.byte		N01   , Cn2 
	.byte	W01
	.byte		VOICE , 31
	.byte		PAN   , c_v+16
	.byte		N01   , Dn2 , v096
	.byte	W01
	.byte		VOICE , 23
	.byte		PAN   , c_v-8
	.byte		BEND  , c_v+16
	.byte		N01   , Cn3 
	.byte	W02
	.byte		PAN   , c_v+8
	.byte		N01   , Cn2 
	.byte	W08
	.byte	FINE

@******************************************************@

	.align	2

seq_141:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_141_pri	@ Priority
	.byte	seq_141_rev	@ Reverb

	.word	seq_141_grp

	.word	seq_141_0

	.end
