@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_153_grp, bank_002
	.equ	seq_153_pri, 4
	.equ	seq_153_rev, 178
	.equ	seq_153_mvl, 127
	.equ	seq_153_key, 0

	.section .rodata
	.global	seq_153
	.align	2

@*********************** Track 01 ***********************@

seq_153_0:
	.byte	KEYSH , seq_153_key+0
	.byte	TEMPO , 250/2
	.byte		VOICE , 22
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 90*seq_153_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N14   , An4 , v108
	.byte	W03
	.byte		PAN   , c_v+5
	.byte		BEND  , c_v+6
	.byte	W01
	.byte		VOL   , 80*seq_153_mvl/mxv
	.byte	W02
	.byte		PAN   , c_v+15
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		VOL   , 64*seq_153_mvl/mxv
	.byte	W02
	.byte		PAN   , c_v+6
	.byte		VOL   , 38*seq_153_mvl/mxv
	.byte		BEND  , c_v-9
	.byte	W02
	.byte		        c_v-34
	.byte	W01
	.byte		PAN   , c_v-1
	.byte		VOL   , 11*seq_153_mvl/mxv
	.byte	W12
	.byte	FINE

@******************************************************@

	.align	2

seq_153:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_153_pri	@ Priority
	.byte	seq_153_rev	@ Reverb

	.word	seq_153_grp

	.word	seq_153_0

	.end
