@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_037_grp, bank_002
	.equ	seq_037_pri, 4
	.equ	seq_037_rev, 178
	.equ	seq_037_mvl, 127
	.equ	seq_037_key, 0

	.section .rodata
	.global	seq_037
	.align	2

@*********************** Track 01 ***********************@

seq_037_0:
	.byte	KEYSH , seq_037_key+0
	.byte	TEMPO , 170/2
	.byte		VOICE , 22
	.byte		VOL   , 110*seq_037_mvl/mxv
	.byte		BEND  , c_v+60
	.byte		N44   , Gn3 , v080
	.byte	W03
	.byte		BEND  , c_v+57
	.byte	W03
	.byte		        c_v+52
	.byte	W03
	.byte		        c_v+43
	.byte	W03
	.byte		        c_v+36
	.byte	W03
	.byte		        c_v+30
	.byte	W03
	.byte		        c_v+22
	.byte	W03
	.byte		        c_v+16
	.byte	W03
	.byte		VOL   , 104*seq_037_mvl/mxv
	.byte		BEND  , c_v+11
	.byte	W03
	.byte		VOL   , 90*seq_037_mvl/mxv
	.byte		BEND  , c_v+3
	.byte	W03
	.byte		VOL   , 82*seq_037_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W03
	.byte		VOL   , 71*seq_037_mvl/mxv
	.byte		BEND  , c_v-16
	.byte	W03
	.byte		VOL   , 58*seq_037_mvl/mxv
	.byte		BEND  , c_v-24
	.byte	W03
	.byte		VOL   , 45*seq_037_mvl/mxv
	.byte		BEND  , c_v-36
	.byte	W03
	.byte		VOL   , 36*seq_037_mvl/mxv
	.byte		BEND  , c_v-50
	.byte	W03
	.byte		VOL   , 11*seq_037_mvl/mxv
	.byte		BEND  , c_v-63
	.byte	W03
	.byte		VOL   , 3*seq_037_mvl/mxv
	.byte	FINE

@******************************************************@

	.align	2

seq_037:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_037_pri	@ Priority
	.byte	seq_037_rev	@ Reverb

	.word	seq_037_grp

	.word	seq_037_0

	.end
