@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_009_grp, bank_000
	.equ	seq_009_pri, 5
	.equ	seq_009_rev, 178
	.equ	seq_009_mvl, 127
	.equ	seq_009_key, 0

	.section .rodata
	.global	seq_009
	.align	2

@*********************** Track 01 ***********************@

seq_009_0:
	.byte	KEYSH , seq_009_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 126
	.byte		VOL   , 120*seq_009_mvl/mxv
	.byte		N02   , An2 , v068
	.byte	W02
	.byte		        Cn3 , v127
	.byte	W01
	.byte	W01
	.byte		        En4 , v068
	.byte	W02
	.byte	W03
	.byte	W03
	.byte		        An2 
	.byte	W02
	.byte		        Cn3 , v100
	.byte	W01
	.byte	W01
	.byte		        En4 , v068
	.byte	W02
	.byte	W03
	.byte	W03
	.byte		        An2 , v032
	.byte	W02
	.byte		        Cn3 , v052
	.byte	W01
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_009:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_009_pri	@ Priority
	.byte	seq_009_rev	@ Reverb

	.word	seq_009_grp

	.word	seq_009_0

	.end
