@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_097_grp, bank_002
	.equ	seq_097_pri, 5
	.equ	seq_097_rev, 178
	.equ	seq_097_mvl, 127
	.equ	seq_097_key, 0

	.section .rodata
	.global	seq_097
	.align	2

@*********************** Track 01 ***********************@

seq_097_0:
	.byte	KEYSH , seq_097_key+0
	.byte	TEMPO , 110/2
	.byte		VOICE , 66
	.byte		BENDR , 12
	.byte		VOL   , 90*seq_097_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N90   , Gs3 , v040
	.byte	W06
	.byte	W06
	.byte		BEND  , c_v+1
	.byte	W04
	.byte		        c_v+3
	.byte	W02
	.byte	W04
	.byte		        c_v+5
	.byte	W02
	.byte	W04
	.byte		        c_v+8
	.byte	W02
	.byte	W03
	.byte		        c_v+11
	.byte	W03
	.byte	W03
	.byte		        c_v+18
	.byte	W03
	.byte	W02
	.byte		        c_v+24
	.byte	W04
	.byte		        c_v+30
	.byte	W02
	.byte		        c_v+38
	.byte	W02
	.byte		        c_v+43
	.byte	W02
	.byte	W01
	.byte		        c_v+56
	.byte	W02
	.byte		        c_v+63
	.byte	W03
	.byte	W03
	.byte		VOL   , 83*seq_097_mvl/mxv
	.byte	W03
	.byte		        75*seq_097_mvl/mxv
	.byte	W04
	.byte		        68*seq_097_mvl/mxv
	.byte	W02
	.byte	W01
	.byte		        55*seq_097_mvl/mxv
	.byte	W04
	.byte		        42*seq_097_mvl/mxv
	.byte	W01
	.byte	W03
	.byte		        29*seq_097_mvl/mxv
	.byte	W03
	.byte		        17*seq_097_mvl/mxv
	.byte	W03
	.byte		        8*seq_097_mvl/mxv
	.byte	W03
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	FINE

@*********************** Track 02 ***********************@

seq_097_1:
	.byte	KEYSH , seq_097_key+0
	.byte		VOICE , 2
	.byte		VOL   , 14*seq_097_mvl/mxv
	.byte		PAN   , c_v-1
	.byte		BEND  , c_v+0
	.byte		TIE   , Gn3 , v100
	.byte	W01
	.byte		VOL   , 19*seq_097_mvl/mxv
	.byte	W01
	.byte		        30*seq_097_mvl/mxv
	.byte	W02
	.byte		        37*seq_097_mvl/mxv
	.byte	W02
	.byte	W02
	.byte		        44*seq_097_mvl/mxv
	.byte	W04
	.byte		        49*seq_097_mvl/mxv
	.byte	W04
	.byte		        53*seq_097_mvl/mxv
	.byte	W02
	.byte	W03
	.byte		        58*seq_097_mvl/mxv
	.byte	W03
	.byte	W02
	.byte		        64*seq_097_mvl/mxv
	.byte	W04
	.byte		        68*seq_097_mvl/mxv
	.byte	W03
	.byte		        74*seq_097_mvl/mxv
	.byte	W03
	.byte	W01
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		VOL   , 81*seq_097_mvl/mxv
	.byte	W04
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		VOL   , 90*seq_097_mvl/mxv
	.byte	W03
	.byte		BEND  , c_v+4
	.byte	W02
	.byte	W03
	.byte		        c_v+5
	.byte	W03
	.byte	W01
	.byte		        c_v+6
	.byte	W03
	.byte		        c_v+6
	.byte	W02
	.byte	W02
	.byte		        c_v+8
	.byte	W02
	.byte		        c_v+10
	.byte	W02
	.byte	W01
	.byte		        c_v+14
	.byte	W02
	.byte		        c_v+17
	.byte	W03
	.byte		        c_v+24
	.byte	W02
	.byte		        c_v+30
	.byte	W01
	.byte		        c_v+41
	.byte	W01
	.byte		        c_v+46
	.byte	W02
	.byte		        c_v+55
	.byte	W01
	.byte		        c_v+60
	.byte	W01
	.byte		        c_v+63
	.byte	W01
	.byte		VOL   , 87*seq_097_mvl/mxv
	.byte	W03
	.byte		        85*seq_097_mvl/mxv
	.byte		PAN   , c_v-4
	.byte	W02
	.byte		VOL   , 78*seq_097_mvl/mxv
	.byte		PAN   , c_v+4
	.byte	W02
	.byte		VOL   , 75*seq_097_mvl/mxv
	.byte		PAN   , c_v-6
	.byte	W02
	.byte	W01
	.byte		VOL   , 69*seq_097_mvl/mxv
	.byte		PAN   , c_v+6
	.byte	W02
	.byte		VOL   , 59*seq_097_mvl/mxv
	.byte		PAN   , c_v-20
	.byte	W03
	.byte		VOL   , 49*seq_097_mvl/mxv
	.byte		PAN   , c_v+22
	.byte	W02
	.byte		VOL   , 41*seq_097_mvl/mxv
	.byte		PAN   , c_v-37
	.byte	W02
	.byte		VOL   , 30*seq_097_mvl/mxv
	.byte		PAN   , c_v+37
	.byte	W02
	.byte	W01
	.byte		VOL   , 19*seq_097_mvl/mxv
	.byte		PAN   , c_v-48
	.byte	W02
	.byte		VOL   , 10*seq_097_mvl/mxv
	.byte		PAN   , c_v+48
	.byte	W01
	.byte		VOL   , 4*seq_097_mvl/mxv
	.byte	W02
	.byte		EOT
	.byte	FINE

@******************************************************@

	.align	2

seq_097:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_097_pri	@ Priority
	.byte	seq_097_rev	@ Reverb

	.word	seq_097_grp

	.word	seq_097_0
	.word	seq_097_1

	.end
