@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_202_grp, bank_002
	.equ	seq_202_pri, 4
	.equ	seq_202_rev, 178
	.equ	seq_202_mvl, 127
	.equ	seq_202_key, 0

	.section .rodata
	.global	seq_202
	.align	2

@*********************** Track 01 ***********************@

seq_202_0:
	.byte	KEYSH , seq_202_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 54
	.byte		VOL   , 100*seq_202_mvl/mxv
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+1
	.byte		N03   , As5 , v127
	.byte	W01
	.byte		PAN   , c_v+2
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+1
	.byte		N06   , Bn5 
	.byte	W01
	.byte		PAN   , c_v+0
	.byte	W02
	.byte	W03
	.byte		BEND  , c_v+1
	.byte		N03   , As5 , v104
	.byte	W01
	.byte		PAN   , c_v-2
	.byte		BEND  , c_v+2
	.byte	W02
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+1
	.byte		N06   , Bn5 
	.byte	W01
	.byte		PAN   , c_v+0
	.byte	W04
	.byte	W01
	.byte		BEND  , c_v+1
	.byte		N03   , As5 , v080
	.byte	W01
	.byte		PAN   , c_v+4
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+1
	.byte		N06   , Bn5 
	.byte	W02
	.byte		PAN   , c_v+0
	.byte	W04
	.byte		BEND  , c_v+1
	.byte		N03   , As5 , v048
	.byte	W02
	.byte		PAN   , c_v-5
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+1
	.byte		N06   , Bn5 
	.byte	W01
	.byte		PAN   , c_v+0
	.byte	W03
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_202:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_202_pri	@ Priority
	.byte	seq_202_rev	@ Reverb

	.word	seq_202_grp

	.word	seq_202_0

	.end
