@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_230_grp, bank_002
	.equ	seq_230_pri, 4
	.equ	seq_230_rev, 178
	.equ	seq_230_mvl, 127
	.equ	seq_230_key, 0

	.section .rodata
	.global	seq_230
	.align	2

@*********************** Track 01 ***********************@

seq_230_0:
	.byte		VOL   , 110*seq_230_mvl/mxv
	.byte	KEYSH , seq_230_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 61
	.byte		BENDR , 44
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N48   , Cn4 , v108
	.byte	W02
	.byte		BEND  , c_v-1
	.byte	W01
	.byte		        c_v+0
	.byte	W03
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+0
	.byte	W02
	.byte		PAN   , c_v-4
	.byte	W01
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		        c_v+1
	.byte	W02
	.byte		        c_v+1
	.byte	W02
	.byte		        c_v+1
	.byte	W02
	.byte		        c_v+1
	.byte	W01
	.byte		        c_v+1
	.byte	W03
	.byte		PAN   , c_v-10
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		        c_v+2
	.byte	W02
	.byte		        c_v+2
	.byte	W03
	.byte		        c_v+1
	.byte	W02
	.byte		        c_v+2
	.byte	W01
	.byte		        c_v+1
	.byte	W03
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		        c_v+1
	.byte	W02
	.byte		        c_v+1
	.byte	W01
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v-1
	.byte	W01
	.byte		        c_v-1
	.byte	W01
	.byte		        c_v-3
	.byte	W01
	.byte		        c_v-3
	.byte	W02
	.byte	FINE

@*********************** Track 02 ***********************@

seq_230_1:
	.byte	KEYSH , seq_230_key+0
	.byte		VOICE , 66
	.byte		BENDR , 44
	.byte		PAN   , c_v+1
	.byte		VOL   , 110*seq_230_mvl/mxv
	.byte		N48   , Dn3 , v020
	.byte	W24
	.byte	W03
	.byte		VOL   , 103*seq_230_mvl/mxv
	.byte	W04
	.byte		        96*seq_230_mvl/mxv
	.byte	W03
	.byte		        83*seq_230_mvl/mxv
	.byte	W04
	.byte		        67*seq_230_mvl/mxv
	.byte	W04
	.byte		        49*seq_230_mvl/mxv
	.byte	W03
	.byte		        23*seq_230_mvl/mxv
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_230:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_230_pri	@ Priority
	.byte	seq_230_rev	@ Reverb

	.word	seq_230_grp

	.word	seq_230_0
	.word	seq_230_1

	.end
