@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_320_grp, bank_060
	.equ	seq_320_pri, 5
	.equ	seq_320_rev, 178
	.equ	seq_320_mvl, 127
	.equ	seq_320_key, 0

	.section .rodata
	.global	seq_320
	.align	2

@*********************** Track 01 ***********************@

seq_320_0:
	.byte	KEYSH , seq_320_key+0
	.byte	TEMPO , 192/2
	.byte		VOICE , 1
	.byte		XCMD  , xIECV , 8
	.byte		        xIECL , 8
	.byte		PAN   , c_v+0
	.byte		VOL   , 81*seq_320_mvl/mxv
	.byte		BEND  , c_v+2
	.byte		N03   , Ds4 , v068
	.byte	W03
	.byte		        Dn4 , v032
	.byte	W03
	.byte		        Fn4 , v068
	.byte	W03
	.byte		        Ds4 , v032
	.byte	W03
	.byte		        Gn4 , v068
	.byte	W03
	.byte		        Fn4 , v032
	.byte	W03
	.byte		        As4 , v068
	.byte	W03
	.byte		        Gn4 , v032
	.byte	W03
	.byte		        Ds5 , v068
	.byte	W03
	.byte		        As4 , v032
	.byte	W03
	.byte		        Fn5 , v068
	.byte	W03
	.byte		        Dn5 , v032
	.byte	W03
	.byte		        Gn5 , v068
	.byte	W03
	.byte		        Ds5 , v032
	.byte	W03
	.byte		        As5 , v068
	.byte	W03
	.byte		        Gn5 , v032
	.byte	W03
	.byte		        Ds6 , v068
	.byte	W03
	.byte		        As5 , v056
	.byte	W03
	.byte		        Ds6 , v048
	.byte	W03
	.byte		        As5 , v040
	.byte	W03
	.byte		        Ds6 , v028
	.byte	W03
	.byte		        As5 , v024
	.byte	W03
	.byte		        Ds6 , v016
	.byte	W03
	.byte		        As5 , v008
	.byte	W03
	.byte		VOL   , 0*seq_320_mvl/mxv
	.byte	W24
	.byte		        0*seq_320_mvl/mxv
	.byte	FINE

@*********************** Track 02 ***********************@

seq_320_1:
	.byte	KEYSH , seq_320_key+0
	.byte		VOICE , 5
	.byte		XCMD  , xIECV , 8
	.byte		        xIECL , 8
	.byte		PAN   , c_v-32
	.byte		VOL   , 67*seq_320_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N03   , Gn4 , v068
	.byte	W03
	.byte		        Dn4 , v032
	.byte	W03
	.byte		        Gn4 , v068
	.byte	W03
	.byte		        Ds4 , v032
	.byte	W03
	.byte		        Gn4 , v068
	.byte	W03
	.byte		        Fn4 , v032
	.byte	W03
	.byte		        As4 , v068
	.byte	W03
	.byte		        Gn4 , v032
	.byte	W03
	.byte		        Ds5 , v068
	.byte	W03
	.byte		        As4 , v032
	.byte	W03
	.byte		        Fn5 , v068
	.byte	W03
	.byte		        Dn5 , v032
	.byte	W03
	.byte		        Gn5 , v068
	.byte	W03
	.byte		        Ds5 , v032
	.byte	W03
	.byte		        As5 , v068
	.byte	W03
	.byte		        Gn5 , v032
	.byte	W03
	.byte		        Ds6 , v068
	.byte	W03
	.byte		        As5 , v056
	.byte	W03
	.byte		        Ds6 , v048
	.byte	W03
	.byte		        As5 , v040
	.byte	W03
	.byte		        Ds6 , v028
	.byte	W03
	.byte		        As5 , v024
	.byte	W03
	.byte		        Ds6 , v016
	.byte	W03
	.byte		        As5 , v008
	.byte	W03
	.byte		VOL   , 1*seq_320_mvl/mxv
	.byte	W24
	.byte	FINE

@*********************** Track 03 ***********************@

seq_320_2:
	.byte	KEYSH , seq_320_key+0
	.byte		VOICE , 4
	.byte		XCMD  , xIECV , 8
	.byte		        xIECL , 8
	.byte		PAN   , c_v+32
	.byte		VOL   , 59*seq_320_mvl/mxv
	.byte		N03   , Ds3 , v068
	.byte	W03
	.byte		        Dn3 , v032
	.byte	W03
	.byte		        Fn3 , v068
	.byte	W03
	.byte		        Ds3 , v032
	.byte	W03
	.byte		        Gn3 , v068
	.byte	W03
	.byte		        Fn3 , v032
	.byte	W03
	.byte		        As3 , v068
	.byte	W03
	.byte		        Gn3 , v032
	.byte	W03
	.byte		        Ds4 , v068
	.byte	W03
	.byte		        As3 , v032
	.byte	W03
	.byte		        Fn4 , v068
	.byte	W03
	.byte		        Dn4 , v032
	.byte	W03
	.byte		        Gn4 , v068
	.byte	W03
	.byte		        Ds4 , v032
	.byte	W03
	.byte		        As4 , v068
	.byte	W03
	.byte		        Gn4 , v032
	.byte	W03
	.byte		        Ds5 , v068
	.byte	W03
	.byte		        As4 , v056
	.byte	W03
	.byte		        Ds5 , v048
	.byte	W03
	.byte		        As4 , v040
	.byte	W03
	.byte		        Ds5 , v028
	.byte	W03
	.byte		        As4 , v024
	.byte	W03
	.byte		        Ds5 , v016
	.byte	W03
	.byte		        As4 , v008
	.byte	W03
	.byte		VOL   , 1*seq_320_mvl/mxv
	.byte	W24
	.byte		        0*seq_320_mvl/mxv
	.byte	FINE

@*********************** Track 04 ***********************@

seq_320_3:
	.byte	KEYSH , seq_320_key+0
	.byte		VOICE , 127
	.byte		PAN   , c_v+0
	.byte		VOL   , 63*seq_320_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N01   , Cn5 , v112
	.byte	W02
	.byte		        An5 
	.byte	W14
	.byte		N03   , Gs5 , v120
	.byte	W08
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@*********************** Track 05 ***********************@

seq_320_4:
	.byte	KEYSH , seq_320_key+0
	.byte		VOICE , 126
	.byte		PAN   , c_v+0
	.byte		VOL   , 100*seq_320_mvl/mxv
	.byte		N02   , Cs3 , v127
	.byte	W10
	.byte		N01   , Bn3 , v116
	.byte	W06
	.byte		N02   , En4 , v127
	.byte	W08
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_320:
	.byte	5	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_320_pri	@ Priority
	.byte	seq_320_rev	@ Reverb

	.word	seq_320_grp

	.word	seq_320_0
	.word	seq_320_1
	.word	seq_320_2
	.word	seq_320_3
	.word	seq_320_4

	.end
