@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_033_grp, bank_000
	.equ	seq_033_pri, 4
	.equ	seq_033_rev, 178
	.equ	seq_033_mvl, 127
	.equ	seq_033_key, 0

	.section .rodata
	.global	seq_033
	.align	2

@*********************** Track 01 ***********************@

seq_033_0:
	.byte	KEYSH , seq_033_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 126
	.byte		VOL   , 127*seq_033_mvl/mxv
	.byte		N08   , An2 , v112
	.byte	W03
	.byte	W03
	.byte	W02
	.byte		N01   , Gs2 
	.byte	W01
	.byte	W01
	.byte		N08   , An2 , v096
	.byte	W02
	.byte	W03
	.byte	W03
	.byte	W01
	.byte		N01   , Gs2 , v092
	.byte	W01
	.byte		N08   , An2 , v080
	.byte	W01
	.byte	W03
	.byte	W03
	.byte	W02
	.byte		N01   , Gs2 , v076
	.byte	W01
	.byte		N08   , An2 , v064
	.byte	W03
	.byte	W03
	.byte	W03
	.byte		N01   , Gs2 , v060
	.byte	W02
	.byte		N09   , An2 , v048
	.byte	W01
	.byte	W03
	.byte	W03
	.byte	W02
	.byte		N01   , Gs2 , v040
	.byte	W01
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_033:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_033_pri	@ Priority
	.byte	seq_033_rev	@ Reverb

	.word	seq_033_grp

	.word	seq_033_0

	.end
