@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_016_grp, bank_000
	.equ	seq_016_pri, 5
	.equ	seq_016_rev, 178
	.equ	seq_016_mvl, 127
	.equ	seq_016_key, 0

	.section .rodata
	.global	seq_016
	.align	2

@*********************** Track 01 ***********************@

seq_016_0:
	.byte	KEYSH , seq_016_key+0
	.byte	TEMPO , 90/2
	.byte		VOICE , 90
	.byte		VOL   , 110*seq_016_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N09   , Cn4 , v100
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	FINE

@*********************** Track 02 ***********************@

seq_016_1:
	.byte	KEYSH , seq_016_key+0
	.byte		VOICE , 124
	.byte		BENDR , 12
	.byte		VOL   , 82*seq_016_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N05   , Gs4 , v060
	.byte	W03
	.byte		VOL   , 94*seq_016_mvl/mxv
	.byte	W03
	.byte		        103*seq_016_mvl/mxv
	.byte		N22
	.byte	W03
	.byte		VOL   , 110*seq_016_mvl/mxv
	.byte	W03
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	FINE

@*********************** Track 03 ***********************@

seq_016_2:
	.byte	KEYSH , seq_016_key+0
	.byte		VOICE , 0
	.byte		VOL   , 110*seq_016_mvl/mxv
	.byte		N06   , Cn3 , v080
	.byte	W06
	.byte		N18   , Cn3 , v092
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_016:
	.byte	3	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_016_pri	@ Priority
	.byte	seq_016_rev	@ Reverb

	.word	seq_016_grp

	.word	seq_016_0
	.word	seq_016_1
	.word	seq_016_2

	.end
