@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_115_grp, bank_002
	.equ	seq_115_pri, 4
	.equ	seq_115_rev, 178
	.equ	seq_115_mvl, 127
	.equ	seq_115_key, 0

	.section .rodata
	.global	seq_115
	.align	2

@*********************** Track 01 ***********************@

seq_115_0:
	.byte	KEYSH , seq_115_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 22
	.byte		VOL   , 110*seq_115_mvl/mxv
	.byte		BENDR , 12
	.byte		PAN   , c_v+16
	.byte		BEND  , c_v+46
	.byte		N09   , Cn3 , v127
	.byte	W03
	.byte		VOL   , 104*seq_115_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+23
	.byte	W03
	.byte		VOL   , 93*seq_115_mvl/mxv
	.byte		PAN   , c_v-16
	.byte		BEND  , c_v-15
	.byte	W03
	.byte		VOICE , 21
	.byte		VOL   , 110*seq_115_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N03   , Gn4 
	.byte	W06
	.byte		PAN   , c_v+16
	.byte		N03   , Cn5 
	.byte	W09
	.byte	FINE

@*********************** Track 02 ***********************@

seq_115_1:
	.byte	KEYSH , seq_115_key+0
	.byte		VOICE , 4
	.byte		VOL   , 110*seq_115_mvl/mxv
	.byte	W09
	.byte		PAN   , c_v+8
	.byte		N03   , Cn3 , v052
	.byte	W06
	.byte		PAN   , c_v-7
	.byte		N03
	.byte	W09
	.byte	FINE

@******************************************************@

	.align	2

seq_115:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_115_pri	@ Priority
	.byte	seq_115_rev	@ Reverb

	.word	seq_115_grp

	.word	seq_115_0
	.word	seq_115_1

	.end
