@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_235_grp, bank_002
	.equ	seq_235_pri, 4
	.equ	seq_235_rev, 178
	.equ	seq_235_mvl, 127
	.equ	seq_235_key, 0

	.section .rodata
	.global	seq_235
	.align	2

@*********************** Track 01 ***********************@

seq_235_0:
	.byte	KEYSH , seq_235_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 3
	.byte		VOL   , 100*seq_235_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N01   , Fn4 , v112
	.byte	W04
	.byte		PAN   , c_v+6
	.byte		N02   , Ds5 , v040
	.byte	W02
	.byte	W02
	.byte		PAN   , c_v-5
	.byte		N01   , Gn4 , v112
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		N01   , Ds5 
	.byte	W03
	.byte	W01
	.byte		PAN   , c_v+6
	.byte		N02   , Ds5 , v020
	.byte	W03
	.byte		PAN   , c_v-5
	.byte		N01   , Gn4 , v064
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		N01   , Ds5 
	.byte	W03
	.byte		PAN   , c_v+11
	.byte		N02   , Ds5 , v020
	.byte	W03
	.byte	W01
	.byte		PAN   , c_v-13
	.byte		N01   , Gn4 , v064
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		N01   , Ds5 
	.byte	W04
	.byte	FINE

@*********************** Track 02 ***********************@

seq_235_1:
	.byte	KEYSH , seq_235_key+0
	.byte		VOICE , 4
	.byte		VOL   , 100*seq_235_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N01   , Dn4 , v040
	.byte	W04
	.byte		        Bn3 
	.byte	W02
	.byte	W03
	.byte		        Dn4 
	.byte	W03
	.byte	W01
	.byte		        Bn3 , v032
	.byte	W05
	.byte		        Dn4 
	.byte	W03
	.byte		        Bn3 , v012
	.byte	W03
	.byte	W02
	.byte		        Dn4 
	.byte	W04
	.byte	FINE

@******************************************************@

	.align	2

seq_235:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_235_pri	@ Priority
	.byte	seq_235_rev	@ Reverb

	.word	seq_235_grp

	.word	seq_235_0
	.word	seq_235_1

	.end
