@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_197_grp, bank_002
	.equ	seq_197_pri, 4
	.equ	seq_197_rev, 178
	.equ	seq_197_mvl, 127
	.equ	seq_197_key, 0

	.section .rodata
	.global	seq_197
	.align	2

@*********************** Track 01 ***********************@

seq_197_0:
	.byte	KEYSH , seq_197_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 45
	.byte		BENDR , 24
	.byte		PAN   , c_v+0
	.byte		VOL   , 32*seq_197_mvl/mxv
	.byte		MOD   , 30
	.byte		BEND  , c_v+39
	.byte		N06   , Dn4 , v127
	.byte	W01
	.byte		BEND  , c_v+31
	.byte	W01
	.byte		VOL   , 49*seq_197_mvl/mxv
	.byte		PAN   , c_v+5
	.byte		BEND  , c_v+23
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		VOL   , 61*seq_197_mvl/mxv
	.byte		BEND  , c_v+8
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+35
	.byte		N06   , Cn4 , v116
	.byte	W01
	.byte		VOL   , 71*seq_197_mvl/mxv
	.byte		BEND  , c_v+27
	.byte	W01
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+19
	.byte	W01
	.byte		VOL   , 81*seq_197_mvl/mxv
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		        c_v+5
	.byte	W02
	.byte		VOL   , 95*seq_197_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+32
	.byte		N06   , Bn3 , v112
	.byte	W01
	.byte		BEND  , c_v+24
	.byte	W01
	.byte		PAN   , c_v+6
	.byte		BEND  , c_v+16
	.byte	W01
	.byte		        c_v+8
	.byte	W01
	.byte		        c_v+1
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+28
	.byte		N06   , An3 
	.byte	W01
	.byte		BEND  , c_v+20
	.byte	W01
	.byte		PAN   , c_v-6
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		        c_v+5
	.byte	W01
	.byte		        c_v-2
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+24
	.byte		N06   , Gn3 , v108
	.byte	W01
	.byte		BEND  , c_v+16
	.byte	W01
	.byte		PAN   , c_v+8
	.byte		BEND  , c_v+9
	.byte	W01
	.byte		        c_v+1
	.byte	W01
	.byte		        c_v-6
	.byte	W02
	.byte		VOL   , 82*seq_197_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+21
	.byte		N06   , Fn3 , v100
	.byte	W01
	.byte		BEND  , c_v+13
	.byte	W01
	.byte		VOL   , 71*seq_197_mvl/mxv
	.byte		PAN   , c_v-8
	.byte		BEND  , c_v+5
	.byte	W01
	.byte		        c_v-2
	.byte	W01
	.byte		VOL   , 61*seq_197_mvl/mxv
	.byte		BEND  , c_v-10
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+17
	.byte		N06   , En3 , v060
	.byte	W01
	.byte		BEND  , c_v+9
	.byte	W01
	.byte		PAN   , c_v+8
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		        c_v-6
	.byte	W01
	.byte		        c_v-13
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+14
	.byte		N06   , Dn3 , v040
	.byte	W01
	.byte		BEND  , c_v+6
	.byte	W01
	.byte		PAN   , c_v-8
	.byte		BEND  , c_v-2
	.byte	W01
	.byte		        c_v-10
	.byte	W01
	.byte		        c_v-17
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+12
	.byte		N06   , Cn3 , v020
	.byte	W01
	.byte		BEND  , c_v+4
	.byte	W01
	.byte		PAN   , c_v+8
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		        c_v-11
	.byte	W01
	.byte		        c_v-18
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_197:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_197_pri	@ Priority
	.byte	seq_197_rev	@ Reverb

	.word	seq_197_grp

	.word	seq_197_0

	.end
