@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_044_grp, bank_002
	.equ	seq_044_pri, 4
	.equ	seq_044_rev, 178
	.equ	seq_044_mvl, 127
	.equ	seq_044_key, 0

	.section .rodata
	.global	seq_044
	.align	2

@*********************** Track 01 ***********************@

seq_044_0:
	.byte	KEYSH , seq_044_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 10
	.byte		VOL   , 127*seq_044_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		TIE   , Cs3 , v127
	.byte	W09
	.byte		BEND  , c_v-9
	.byte	W09
	.byte		        c_v-18
	.byte	W06
	.byte	W09
	.byte		        c_v-26
	.byte	W09
	.byte		        c_v-34
	.byte	W06
	.byte	W06
	.byte		        c_v-43
	.byte	W05
	.byte		VOL   , 123*seq_044_mvl/mxv
	.byte	W04
	.byte		BEND  , c_v-54
	.byte	W02
	.byte		VOL   , 117*seq_044_mvl/mxv
	.byte	W06
	.byte		        110*seq_044_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-64
	.byte	W08
	.byte		VOL   , 101*seq_044_mvl/mxv
	.byte	W06
	.byte		        89*seq_044_mvl/mxv
	.byte	W09
	.byte		        77*seq_044_mvl/mxv
	.byte	W01
	.byte	W05
	.byte		        60*seq_044_mvl/mxv
	.byte	W09
	.byte		        48*seq_044_mvl/mxv
	.byte	W06
	.byte		        36*seq_044_mvl/mxv
	.byte	W04
	.byte	W03
	.byte		        23*seq_044_mvl/mxv
	.byte	W06
	.byte		        8*seq_044_mvl/mxv
	.byte	W09
	.byte		        0*seq_044_mvl/mxv
	.byte	W01
	.byte		EOT
	.byte	W05
	.byte	FINE

@*********************** Track 02 ***********************@

seq_044_1:
	.byte	KEYSH , seq_044_key+0
	.byte		VOICE , 13
	.byte		VOL   , 90*seq_044_mvl/mxv
	.byte	W06
	.byte		N09   , Gs6 , v024
	.byte	W18
	.byte	W05
	.byte		N15
	.byte	W19
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@*********************** Track 03 ***********************@

seq_044_2:
	.byte	KEYSH , seq_044_key+0
	.byte		VOICE , 12
	.byte		VOL   , 90*seq_044_mvl/mxv
	.byte	W06
	.byte		N09   , An6 , v024
	.byte	W18
	.byte	W05
	.byte		N15
	.byte	W19
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_044:
	.byte	3	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_044_pri	@ Priority
	.byte	seq_044_rev	@ Reverb

	.word	seq_044_grp

	.word	seq_044_0
	.word	seq_044_1
	.word	seq_044_2

	.end
