@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_050_grp, bank_002
	.equ	seq_050_pri, 4
	.equ	seq_050_rev, 178
	.equ	seq_050_mvl, 127
	.equ	seq_050_key, 0

	.section .rodata
	.global	seq_050
	.align	2

@*********************** Track 01 ***********************@

seq_050_0:
	.byte	KEYSH , seq_050_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 16
	.byte		VOL   , 100*seq_050_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		N12   , Fn4 , v100
	.byte	W12
	.byte	FINE

@*********************** Track 02 ***********************@

seq_050_1:
	.byte	KEYSH , seq_050_key+0
	.byte		VOICE , 17
	.byte		VOL   , 100*seq_050_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N09   , Fn4 , v088
	.byte	W12
	.byte	FINE

@******************************************************@

	.align	2

seq_050:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_050_pri	@ Priority
	.byte	seq_050_rev	@ Reverb

	.word	seq_050_grp

	.word	seq_050_0
	.word	seq_050_1

	.end
