@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_057_grp, bank_002
	.equ	seq_057_pri, 4
	.equ	seq_057_rev, 178
	.equ	seq_057_mvl, 127
	.equ	seq_057_key, 0

	.section .rodata
	.global	seq_057
	.align	2

@*********************** Track 01 ***********************@

seq_057_0:
	.byte	KEYSH , seq_057_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 48
	.byte		VOL   , 110*seq_057_mvl/mxv
	.byte		BEND  , c_v-7
	.byte		N12   , En5 , v112
	.byte	W06
	.byte	W06
	.byte		N06   , En5 , v040
	.byte	W06
	.byte	FINE

@*********************** Track 02 ***********************@

seq_057_1:
	.byte	KEYSH , seq_057_key+0
	.byte		VOICE , 17
	.byte		VOL   , 110*seq_057_mvl/mxv
	.byte		BEND  , c_v-7
	.byte		N12   , Bn5 , v060
	.byte	W06
	.byte	W06
	.byte		N06   , Bn5 , v032
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_057:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_057_pri	@ Priority
	.byte	seq_057_rev	@ Reverb

	.word	seq_057_grp

	.word	seq_057_0
	.word	seq_057_1

	.end
