@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_241_grp, bank_003
	.equ	seq_241_pri, 5
	.equ	seq_241_rev, 178
	.equ	seq_241_mvl, 127
	.equ	seq_241_key, 0

	.section .rodata
	.global	seq_241
	.align	2

@*********************** Track 01 ***********************@

seq_241_0:
	.byte	KEYSH , seq_241_key+0
	.byte	TEMPO , 110/2
	.byte		VOICE , 127
	.byte		VOL   , 100*seq_241_mvl/mxv
	.byte		N03   , Fn2 , v100
	.byte		N03   , As2 , v127
	.byte	W06
	.byte		N08   , Fs3 , v096
	.byte	W06
	.byte		VOL   , 88*seq_241_mvl/mxv
	.byte	W03
	.byte		        54*seq_241_mvl/mxv
	.byte	W03
	.byte		        68*seq_241_mvl/mxv
	.byte	W06
	.byte	FINE

@*********************** Track 02 ***********************@

seq_241_1:
	.byte	KEYSH , seq_241_key+0
	.byte		VOICE , 92
	.byte		BENDR , 12
	.byte		VOL   , 43*seq_241_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W04
	.byte		        c_v-50
	.byte		N10   , Bn5 , v052
	.byte	W02
	.byte		BEND  , c_v-45
	.byte	W01
	.byte		        c_v-23
	.byte	W01
	.byte		        c_v-2
	.byte	W01
	.byte		        c_v+22
	.byte	W01
	.byte		        c_v+28
	.byte	W01
	.byte		        c_v+41
	.byte	W01
	.byte		VOL   , 29*seq_241_mvl/mxv
	.byte		BEND  , c_v+53
	.byte	W01
	.byte		        c_v+60
	.byte	W02
	.byte		VOL   , 18*seq_241_mvl/mxv
	.byte		BEND  , c_v+63
	.byte	W09
	.byte	FINE

@******************************************************@

	.align	2

seq_241:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_241_pri	@ Priority
	.byte	seq_241_rev	@ Reverb

	.word	seq_241_grp

	.word	seq_241_0
	.word	seq_241_1

	.end
