@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_110_grp, bank_002
	.equ	seq_110_pri, 5
	.equ	seq_110_rev, 178
	.equ	seq_110_mvl, 127
	.equ	seq_110_key, 0

	.section .rodata
	.global	seq_110
	.align	2

@*********************** Track 01 ***********************@

seq_110_0:
	.byte	KEYSH , seq_110_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 28
	.byte		VOL   , 26*seq_110_mvl/mxv
	.byte		BENDR , 8
	.byte		BEND  , c_v+0
	.byte		N01   , En3 , v116
	.byte	W01
	.byte		VOL   , 105*seq_110_mvl/mxv
	.byte		BEND  , c_v-4
	.byte		N01   , Bn2 
	.byte	W01
	.byte		BEND  , c_v+3
	.byte		N01   , Cn3 
	.byte	W04
	.byte	W04
	.byte		BEND  , c_v+0
	.byte		N04   , Bn3 
	.byte	W02
	.byte		VOL   , 26*seq_110_mvl/mxv
	.byte		BEND  , c_v-7
	.byte	W01
	.byte		VOL   , 105*seq_110_mvl/mxv
	.byte		BEND  , c_v-13
	.byte	W01
	.byte		        c_v-23
	.byte	W04
	.byte	FINE

@******************************************************@

	.align	2

seq_110:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_110_pri	@ Priority
	.byte	seq_110_rev	@ Reverb

	.word	seq_110_grp

	.word	seq_110_0

	.end
