@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_031_grp, bank_000
	.equ	seq_031_pri, 4
	.equ	seq_031_rev, 178
	.equ	seq_031_mvl, 127
	.equ	seq_031_key, 0

	.section .rodata
	.global	seq_031
	.align	2

@*********************** Track 01 ***********************@

seq_031_0:
	.byte	KEYSH , seq_031_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 126
	.byte		VOL   , 120*seq_031_mvl/mxv
	.byte		N01   , Cn3 , v068
	.byte	W01
	.byte		        En3 , v064
	.byte	W01
	.byte		        Gn3 
	.byte	W03
	.byte		N02   , An2 , v048
	.byte	W08
	.byte		N01   , Cn3 , v068
	.byte	W01
	.byte		        En3 , v064
	.byte	W01
	.byte		        Gn3 
	.byte	W03
	.byte		N02   , An2 , v048
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_031:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_031_pri	@ Priority
	.byte	seq_031_rev	@ Reverb

	.word	seq_031_grp

	.word	seq_031_0

	.end
