@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_074_grp, bank_002
	.equ	seq_074_pri, 2
	.equ	seq_074_rev, 178
	.equ	seq_074_mvl, 127
	.equ	seq_074_key, 0

	.section .rodata
	.global	seq_074
	.align	2

@*********************** Track 01 ***********************@

seq_074_0:
	.byte	KEYSH , seq_074_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 36
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 15*seq_074_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N24   , Gn3 , v060
	.byte	W03
	.byte		VOL   , 27*seq_074_mvl/mxv
	.byte	W03
	.byte		        39*seq_074_mvl/mxv
	.byte	W03
	.byte		        44*seq_074_mvl/mxv
	.byte	W03
	.byte		        52*seq_074_mvl/mxv
	.byte	W03
	.byte		        59*seq_074_mvl/mxv
	.byte	W03
	.byte		        68*seq_074_mvl/mxv
	.byte	W03
	.byte		        80*seq_074_mvl/mxv
	.byte	W03
	.byte		N60   , Gn3 , v060
	.byte	W24
	.byte	W24
	.byte	W12
	.byte	GOTO
	 .word	seq_074_0 + 0x21
	.byte	FINE

@******************************************************@

	.align	2

seq_074:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_074_pri	@ Priority
	.byte	seq_074_rev	@ Reverb

	.word	seq_074_grp

	.word	seq_074_0

	.end
