@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_229_grp, bank_002
	.equ	seq_229_pri, 4
	.equ	seq_229_rev, 178
	.equ	seq_229_mvl, 127
	.equ	seq_229_key, 0

	.section .rodata
	.global	seq_229
	.align	2

@*********************** Track 01 ***********************@

seq_229_0:
	.byte	KEYSH , seq_229_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 61
	.byte		BENDR , 44
	.byte		PAN   , c_v+0
	.byte		VOL   , 110*seq_229_mvl/mxv
	.byte		BEND  , c_v+2
	.byte		N36   , En3 , v096
	.byte	W12
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+2
	.byte	W12
	.byte		PAN   , c_v-10
	.byte		BEND  , c_v+4
	.byte	W12
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+5
	.byte		N36   , Fn3 
	.byte	W12
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+6
	.byte	W12
	.byte		PAN   , c_v+6
	.byte		BEND  , c_v+7
	.byte	W12
	.byte		PAN   , c_v+9
	.byte		BEND  , c_v+8
	.byte		N36   , En3 , v088
	.byte	W12
	.byte		PAN   , c_v+5
	.byte		BEND  , c_v+8
	.byte	W12
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+9
	.byte	W12
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+10
	.byte		N60   , Fs3 , v056
	.byte	W12
	.byte		PAN   , c_v-10
	.byte		BEND  , c_v+11
	.byte	W12
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+12
	.byte	W04
	.byte		VOL   , 103*seq_229_mvl/mxv
	.byte	W04
	.byte		        97*seq_229_mvl/mxv
	.byte	W04
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		VOL   , 91*seq_229_mvl/mxv
	.byte	W05
	.byte		        81*seq_229_mvl/mxv
	.byte	W03
	.byte		        72*seq_229_mvl/mxv
	.byte	W03
	.byte		PAN   , c_v+6
	.byte		BEND  , c_v+13
	.byte	W01
	.byte		VOL   , 62*seq_229_mvl/mxv
	.byte	W02
	.byte		        51*seq_229_mvl/mxv
	.byte	W03
	.byte		        39*seq_229_mvl/mxv
	.byte	W02
	.byte		        24*seq_229_mvl/mxv
	.byte	W02
	.byte		        12*seq_229_mvl/mxv
	.byte	W02
	.byte	FINE

@*********************** Track 02 ***********************@

seq_229_1:
	.byte	KEYSH , seq_229_key+0
	.byte		VOICE , 22
	.byte		BENDR , 44
	.byte		PAN   , c_v+1
	.byte		VOL   , 38*seq_229_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		TIE   , Gn3 , v100
	.byte	W03
	.byte		VOL   , 50*seq_229_mvl/mxv
	.byte	W04
	.byte		        62*seq_229_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-1
	.byte	W01
	.byte		VOL   , 65*seq_229_mvl/mxv
	.byte	W04
	.byte		        74*seq_229_mvl/mxv
	.byte	W04
	.byte		        78*seq_229_mvl/mxv
	.byte		BEND  , c_v-2
	.byte	W03
	.byte		VOL   , 86*seq_229_mvl/mxv
	.byte	W03
	.byte		        95*seq_229_mvl/mxv
	.byte	W03
	.byte		        105*seq_229_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-4
	.byte	W03
	.byte		VOL   , 110*seq_229_mvl/mxv
	.byte	W13
	.byte		BEND  , c_v-2
	.byte	W04
	.byte	W10
	.byte		        c_v-1
	.byte	W10
	.byte		        c_v+0
	.byte	W04
	.byte	W03
	.byte		        c_v+1
	.byte	W10
	.byte		        c_v+1
	.byte	W11
	.byte	W02
	.byte		        c_v+2
	.byte	W14
	.byte		        c_v+3
	.byte	W08
	.byte		VOL   , 105*seq_229_mvl/mxv
	.byte	W03
	.byte		        101*seq_229_mvl/mxv
	.byte	W05
	.byte		        96*seq_229_mvl/mxv
	.byte	W04
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		VOL   , 91*seq_229_mvl/mxv
	.byte	W03
	.byte		        86*seq_229_mvl/mxv
	.byte	W05
	.byte		        78*seq_229_mvl/mxv
	.byte	W03
	.byte	W02
	.byte		        68*seq_229_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+1
	.byte	W04
	.byte		VOL   , 58*seq_229_mvl/mxv
	.byte	W03
	.byte		        48*seq_229_mvl/mxv
	.byte	W04
	.byte		        37*seq_229_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W04
	.byte		VOL   , 23*seq_229_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-1
	.byte	W02
	.byte		VOL   , 12*seq_229_mvl/mxv
	.byte	W03
	.byte		EOT
	.byte	FINE

@******************************************************@

	.align	2

seq_229:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_229_pri	@ Priority
	.byte	seq_229_rev	@ Reverb

	.word	seq_229_grp

	.word	seq_229_0
	.word	seq_229_1

	.end
