@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_100_grp, bank_002
	.equ	seq_100_pri, 5
	.equ	seq_100_rev, 178
	.equ	seq_100_mvl, 127
	.equ	seq_100_key, 0

	.section .rodata
	.global	seq_100
	.align	2

@*********************** Track 01 ***********************@

seq_100_0:
	.byte	KEYSH , seq_100_key+0
	.byte	TEMPO , 110/2
	.byte		VOICE , 15
	.byte		BENDR , 12
	.byte		VOL   , 100*seq_100_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+30
	.byte		TIE   , Cn4 , v100
	.byte	W01
	.byte		BEND  , c_v+24
	.byte	W01
	.byte		        c_v+19
	.byte	W01
	.byte		        c_v+14
	.byte	W01
	.byte		        c_v+8
	.byte	W02
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+2
	.byte	W01
	.byte		        c_v+0
	.byte	W04
	.byte	W04
	.byte		        c_v+1
	.byte	W02
	.byte	W06
	.byte		        c_v+1
	.byte	W06
	.byte		        c_v+1
	.byte	W06
	.byte		        c_v+2
	.byte	W06
	.byte		        c_v+3
	.byte	W06
	.byte		        c_v+3
	.byte	W06
	.byte		        c_v+4
	.byte	W06
	.byte		        c_v+4
	.byte	W06
	.byte		        c_v+5
	.byte	W06
	.byte		        c_v+6
	.byte	W06
	.byte		        c_v+8
	.byte	W06
	.byte		        c_v+10
	.byte	W06
	.byte		        c_v+12
	.byte	W06
	.byte		        c_v+14
	.byte	W06
	.byte		        c_v+16
	.byte	W06
	.byte		        c_v+18
	.byte	W06
	.byte		        c_v+20
	.byte	W06
	.byte		VOL   , 98*seq_100_mvl/mxv
	.byte		BEND  , c_v+22
	.byte	W03
	.byte		VOL   , 97*seq_100_mvl/mxv
	.byte	W03
	.byte		BEND  , c_v+24
	.byte	W01
	.byte		VOL   , 94*seq_100_mvl/mxv
	.byte	W03
	.byte		        91*seq_100_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+26
	.byte	W02
	.byte		VOL   , 88*seq_100_mvl/mxv
	.byte	W02
	.byte		        85*seq_100_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+28
	.byte	W02
	.byte		VOL   , 80*seq_100_mvl/mxv
	.byte	W02
	.byte		        73*seq_100_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+30
	.byte	W01
	.byte		VOL   , 68*seq_100_mvl/mxv
	.byte	W02
	.byte		        62*seq_100_mvl/mxv
	.byte	W03
	.byte		        55*seq_100_mvl/mxv
	.byte		BEND  , c_v+32
	.byte	W02
	.byte		VOL   , 47*seq_100_mvl/mxv
	.byte	W02
	.byte		        37*seq_100_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+36
	.byte	W01
	.byte		VOL   , 30*seq_100_mvl/mxv
	.byte	W01
	.byte		        20*seq_100_mvl/mxv
	.byte	W01
	.byte		        13*seq_100_mvl/mxv
	.byte	W01
	.byte		        4*seq_100_mvl/mxv
	.byte	W02
	.byte		EOT
	.byte	FINE

@*********************** Track 02 ***********************@

seq_100_1:
	.byte	KEYSH , seq_100_key+0
	.byte		VOICE , 25
	.byte		VOL   , 15*seq_100_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		TIE   , Gs2 , v060
	.byte	W01
	.byte		VOL   , 21*seq_100_mvl/mxv
	.byte	W01
	.byte		        33*seq_100_mvl/mxv
	.byte	W01
	.byte		        41*seq_100_mvl/mxv
	.byte	W01
	.byte		        49*seq_100_mvl/mxv
	.byte	W02
	.byte		        55*seq_100_mvl/mxv
	.byte	W01
	.byte		        61*seq_100_mvl/mxv
	.byte	W01
	.byte		        69*seq_100_mvl/mxv
	.byte	W01
	.byte		        76*seq_100_mvl/mxv
	.byte	W01
	.byte		        80*seq_100_mvl/mxv
	.byte	W02
	.byte		        86*seq_100_mvl/mxv
	.byte	W01
	.byte		        90*seq_100_mvl/mxv
	.byte	W01
	.byte		        100*seq_100_mvl/mxv
	.byte	W04
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W01
	.byte		BEND  , c_v+1
	.byte	W05
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W06
	.byte	W02
	.byte		        c_v+2
	.byte	W04
	.byte	W01
	.byte		        c_v+4
	.byte	W05
	.byte		        c_v+5
	.byte	W03
	.byte		VOL   , 97*seq_100_mvl/mxv
	.byte		BEND  , c_v+6
	.byte	W03
	.byte		VOL   , 94*seq_100_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+6
	.byte	W01
	.byte		VOL   , 87*seq_100_mvl/mxv
	.byte	W02
	.byte		        83*seq_100_mvl/mxv
	.byte		BEND  , c_v+8
	.byte	W02
	.byte	W01
	.byte		VOL   , 77*seq_100_mvl/mxv
	.byte		BEND  , c_v+10
	.byte	W02
	.byte		VOL   , 66*seq_100_mvl/mxv
	.byte		BEND  , c_v+14
	.byte	W03
	.byte		VOL   , 55*seq_100_mvl/mxv
	.byte		BEND  , c_v+17
	.byte	W02
	.byte		VOL   , 45*seq_100_mvl/mxv
	.byte		BEND  , c_v+24
	.byte	W02
	.byte		VOL   , 33*seq_100_mvl/mxv
	.byte		BEND  , c_v+30
	.byte	W02
	.byte		        c_v+41
	.byte	W01
	.byte		VOL   , 21*seq_100_mvl/mxv
	.byte		BEND  , c_v+46
	.byte	W01
	.byte		        c_v+55
	.byte	W01
	.byte		VOL   , 11*seq_100_mvl/mxv
	.byte		BEND  , c_v+60
	.byte	W01
	.byte		VOL   , 5*seq_100_mvl/mxv
	.byte		BEND  , c_v+63
	.byte	W02
	.byte		EOT
	.byte	FINE

@******************************************************@

	.align	2

seq_100:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_100_pri	@ Priority
	.byte	seq_100_rev	@ Reverb

	.word	seq_100_grp

	.word	seq_100_0
	.word	seq_100_1

	.end
