@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_049_grp, bank_002
	.equ	seq_049_pri, 4
	.equ	seq_049_rev, 178
	.equ	seq_049_mvl, 127
	.equ	seq_049_key, 0

	.section .rodata
	.global	seq_049
	.align	2

@*********************** Track 01 ***********************@

seq_049_0:
	.byte	KEYSH , seq_049_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 16
	.byte		VOL   , 100*seq_049_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		N12   , Fn4 , v112
	.byte	W12
	.byte	FINE

@*********************** Track 02 ***********************@

seq_049_1:
	.byte	KEYSH , seq_049_key+0
	.byte		VOICE , 17
	.byte		VOL   , 100*seq_049_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N09   , Fn4 , v100
	.byte	W12
	.byte	FINE

@******************************************************@

	.align	2

seq_049:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_049_pri	@ Priority
	.byte	seq_049_rev	@ Reverb

	.word	seq_049_grp

	.word	seq_049_0
	.word	seq_049_1

	.end
