@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_234_grp, bank_002
	.equ	seq_234_pri, 4
	.equ	seq_234_rev, 178
	.equ	seq_234_mvl, 127
	.equ	seq_234_key, 0

	.section .rodata
	.global	seq_234
	.align	2

@*********************** Track 01 ***********************@

seq_234_0:
	.byte	KEYSH , seq_234_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 60
	.byte		BENDR , 12
	.byte		VOL   , 25*seq_234_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N24   , Gs2 , v127
	.byte	W01
	.byte		PAN   , c_v+2
	.byte		VOL   , 51*seq_234_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v+5
	.byte		VOL   , 74*seq_234_mvl/mxv
	.byte	W01
	.byte		        89*seq_234_mvl/mxv
	.byte		BEND  , c_v+1
	.byte	W01
	.byte		PAN   , c_v+2
	.byte		VOL   , 100*seq_234_mvl/mxv
	.byte	W02
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		        c_v-2
	.byte		BEND  , c_v+4
	.byte	W01
	.byte		PAN   , c_v-4
	.byte	W02
	.byte		        c_v-2
	.byte		BEND  , c_v+5
	.byte	W02
	.byte		PAN   , c_v+0
	.byte	W01
	.byte		        c_v+2
	.byte	W01
	.byte		        c_v+5
	.byte	W02
	.byte		        c_v+2
	.byte	W02
	.byte		        c_v+0
	.byte	W01
	.byte		VOL   , 85*seq_234_mvl/mxv
	.byte		PAN   , c_v-2
	.byte	W01
	.byte		        c_v-4
	.byte		VOL   , 62*seq_234_mvl/mxv
	.byte	W01
	.byte		        33*seq_234_mvl/mxv
	.byte	W01
	.byte		PAN   , c_v-2
	.byte		VOL   , 11*seq_234_mvl/mxv
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_234:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_234_pri	@ Priority
	.byte	seq_234_rev	@ Reverb

	.word	seq_234_grp

	.word	seq_234_0

	.end
