@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_015_grp, bank_000
	.equ	seq_015_pri, 5
	.equ	seq_015_rev, 178
	.equ	seq_015_mvl, 127
	.equ	seq_015_key, 0

	.section .rodata
	.global	seq_015
	.align	2

@*********************** Track 01 ***********************@

seq_015_0:
	.byte	KEYSH , seq_015_key+0
	.byte	TEMPO , 90/2
	.byte		VOICE , 86
	.byte		VOL   , 100*seq_015_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N02   , Gn1 , v100
	.byte	W03
	.byte		N05   , Fn2 
	.byte	W03
	.byte	W03
	.byte		N06   , Fn2 , v052
	.byte	W03
	.byte	W03
	.byte	FINE

@*********************** Track 02 ***********************@

seq_015_1:
	.byte	KEYSH , seq_015_key+0
	.byte		VOICE , 0
	.byte		VOL   , 100*seq_015_mvl/mxv
	.byte		BENDR , 12
	.byte		BEND  , c_v+0
	.byte		N03   , Gn3 , v052
	.byte	W03
	.byte		        Cn2 , v112
	.byte	W03
	.byte	W03
	.byte		        Cn1 , v092
	.byte	W03
	.byte	W03
	.byte	FINE

@*********************** Track 03 ***********************@

seq_015_2:
	.byte	KEYSH , seq_015_key+0
	.byte		VOICE , 124
	.byte		VOL   , 100*seq_015_mvl/mxv
	.byte		N03   , Gn3 , v052
	.byte	W03
	.byte		N06   , Gs4 
	.byte	W03
	.byte	W03
	.byte		        Gs4 , v020
	.byte	W03
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_015:
	.byte	3	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_015_pri	@ Priority
	.byte	seq_015_rev	@ Reverb

	.word	seq_015_grp

	.word	seq_015_0
	.word	seq_015_1
	.word	seq_015_2

	.end
