@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_159_grp, bank_002
	.equ	seq_159_pri, 4
	.equ	seq_159_rev, 178
	.equ	seq_159_mvl, 127
	.equ	seq_159_key, 0

	.section .rodata
	.global	seq_159
	.align	2

@*********************** Track 01 ***********************@

seq_159_0:
	.byte	KEYSH , seq_159_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 21
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 110*seq_159_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		N01   , Bn5 , v127
	.byte	W02
	.byte		VOICE , 18
	.byte		N01   , Cn4 
	.byte	W02
	.byte		VOICE , 36
	.byte		N06   , Gn5 , v040
	.byte	W02
	.byte		VOL   , 58*seq_159_mvl/mxv
	.byte		PAN   , c_v+16
	.byte		BEND  , c_v+5
	.byte	W01
	.byte		VOL   , 71*seq_159_mvl/mxv
	.byte		PAN   , c_v-14
	.byte		BEND  , c_v+13
	.byte	W01
	.byte		VOL   , 84*seq_159_mvl/mxv
	.byte		PAN   , c_v+16
	.byte		BEND  , c_v+21
	.byte	W01
	.byte		VOL   , 97*seq_159_mvl/mxv
	.byte		PAN   , c_v-14
	.byte		BEND  , c_v+33
	.byte	W01
	.byte		VOL   , 110*seq_159_mvl/mxv
	.byte	W14
	.byte	FINE

@******************************************************@

	.align	2

seq_159:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_159_pri	@ Priority
	.byte	seq_159_rev	@ Reverb

	.word	seq_159_grp

	.word	seq_159_0

	.end
