@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_198_grp, bank_002
	.equ	seq_198_pri, 4
	.equ	seq_198_rev, 178
	.equ	seq_198_mvl, 127
	.equ	seq_198_key, 0

	.section .rodata
	.global	seq_198
	.align	2

@*********************** Track 01 ***********************@

seq_198_0:
	.byte	KEYSH , seq_198_key+0
	.byte	TEMPO , 180/2
	.byte		VOICE , 38
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 110*seq_198_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N02   , Gn4 , v127
	.byte	W01
	.byte		VOL   , 74*seq_198_mvl/mxv
	.byte		BEND  , c_v-11
	.byte	W01
	.byte		VOICE , 31
	.byte		VOL   , 40*seq_198_mvl/mxv
	.byte		BEND  , c_v-1
	.byte		N03   , Cs5 
	.byte	W01
	.byte		VOL   , 64*seq_198_mvl/mxv
	.byte		PAN   , c_v-6
	.byte		BEND  , c_v-12
	.byte	W01
	.byte		VOL   , 86*seq_198_mvl/mxv
	.byte		PAN   , c_v+4
	.byte		BEND  , c_v-16
	.byte	W02
	.byte		VOL   , 110*seq_198_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N02   , As5 
	.byte	W01
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		VOL   , 0*seq_198_mvl/mxv
	.byte	W04
	.byte	FINE

@******************************************************@

	.align	2

seq_198:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_198_pri	@ Priority
	.byte	seq_198_rev	@ Reverb

	.word	seq_198_grp

	.word	seq_198_0

	.end
