@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_068_grp, bank_002
	.equ	seq_068_pri, 4
	.equ	seq_068_rev, 178
	.equ	seq_068_mvl, 127
	.equ	seq_068_key, 0

	.section .rodata
	.global	seq_068
	.align	2

@*********************** Track 01 ***********************@

seq_068_0:
	.byte	KEYSH , seq_068_key+0
	.byte	TEMPO , 240/2
	.byte		VOICE , 2
	.byte		BENDR , 12
	.byte		VOL   , 105*seq_068_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N03   , Gn4 , v127
	.byte	W04
	.byte		N01   , Gn4 , v112
	.byte	W02
	.byte	W02
	.byte		        Gs3 , v052
	.byte	W04
	.byte		VOICE , 23
	.byte		N02   , Fn3 , v112
	.byte	W04
	.byte		N01   , Cn4 , v072
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_068:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_068_pri	@ Priority
	.byte	seq_068_rev	@ Reverb

	.word	seq_068_grp

	.word	seq_068_0

	.end
