@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_145_grp, bank_002
	.equ	seq_145_pri, 4
	.equ	seq_145_rev, 178
	.equ	seq_145_mvl, 127
	.equ	seq_145_key, 0

	.section .rodata
	.global	seq_145
	.align	2

@*********************** Track 01 ***********************@

seq_145_0:
	.byte	KEYSH , seq_145_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 2
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 105*seq_145_mvl/mxv
	.byte		BEND  , c_v-48
	.byte		N10   , Gn0 , v127
	.byte	W02
	.byte		PAN   , c_v+7
	.byte		BEND  , c_v-32
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		PAN   , c_v+11
	.byte		BEND  , c_v+0
	.byte	W02
	.byte		        c_v+15
	.byte	W01
	.byte		PAN   , c_v+14
	.byte	W01
	.byte		BEND  , c_v+32
	.byte	W01
	.byte		PAN   , c_v+19
	.byte	W03
	.byte		        c_v+0
	.byte		VOL   , 105*seq_145_mvl/mxv
	.byte		BEND  , c_v-32
	.byte		N10
	.byte	W02
	.byte		PAN   , c_v-8
	.byte		BEND  , c_v-16
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		PAN   , c_v-11
	.byte		BEND  , c_v+16
	.byte	W02
	.byte		        c_v+32
	.byte	W01
	.byte		PAN   , c_v-15
	.byte	W01
	.byte		BEND  , c_v+48
	.byte	W01
	.byte		PAN   , c_v-20
	.byte	W03
	.byte		        c_v+0
	.byte		VOL   , 105*seq_145_mvl/mxv
	.byte		BEND  , c_v-16
	.byte		N10
	.byte	W02
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		        c_v+16
	.byte	W01
	.byte		        c_v+32
	.byte	W02
	.byte		        c_v+47
	.byte	W02
	.byte		        c_v+63
	.byte	W16
	.byte	FINE

@******************************************************@

	.align	2

seq_145:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_145_pri	@ Priority
	.byte	seq_145_rev	@ Reverb

	.word	seq_145_grp

	.word	seq_145_0

	.end
