@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_208_grp, bank_002
	.equ	seq_208_pri, 4
	.equ	seq_208_rev, 178
	.equ	seq_208_mvl, 127
	.equ	seq_208_key, 0

	.section .rodata
	.global	seq_208
	.align	2

@*********************** Track 01 ***********************@

seq_208_0:
	.byte	KEYSH , seq_208_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 18
	.byte		VOL   , 110*seq_208_mvl/mxv
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N02   , En3 , v127
	.byte	W03
	.byte		N01   , As3 
	.byte	W03
	.byte		N02   , Gn3 
	.byte	W03
	.byte		N01   , Cs4 
	.byte	W03
	.byte		PAN   , c_v+7
	.byte		N02   , En3 , v072
	.byte	W03
	.byte		N01   , As3 
	.byte	W03
	.byte		PAN   , c_v-7
	.byte		N02   , Gn3 , v040
	.byte	W03
	.byte		N01   , Cs4 
	.byte	W03
	.byte	FINE

@*********************** Track 02 ***********************@

seq_208_1:
	.byte	KEYSH , seq_208_key+0
	.byte		VOICE , 5
	.byte		VOL   , 110*seq_208_mvl/mxv
	.byte		N01   , Cn3 , v040
	.byte	W02
	.byte		N01
	.byte	W04
	.byte		N01
	.byte	W02
	.byte		N01
	.byte	W04
	.byte		N01   , Cn3 , v020
	.byte	W02
	.byte		N01
	.byte	W04
	.byte	PEND
	.byte	PATT
	 .word	seq_208_1 + 0x10
	.byte	FINE

@******************************************************@

	.align	2

seq_208:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_208_pri	@ Priority
	.byte	seq_208_rev	@ Reverb

	.word	seq_208_grp

	.word	seq_208_0
	.word	seq_208_1

	.end
