@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_319_grp, bank_059
	.equ	seq_319_pri, 5
	.equ	seq_319_rev, 178
	.equ	seq_319_mvl, 127
	.equ	seq_319_key, 0

	.section .rodata
	.global	seq_319
	.align	2

@*********************** Track 01 ***********************@

seq_319_0:
	.byte	KEYSH , seq_319_key+0
	.byte	TEMPO , 64/2
	.byte		VOICE , 60
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		VOL   , 59*seq_319_mvl/mxv
	.byte		PAN   , c_v-48
	.byte		BEND  , c_v+1
	.byte	W12
	.byte	TEMPO , 136/2
	.byte		N06   , En3 , v096
	.byte	W06
	.byte		        En3 , v040
	.byte	W06
	.byte		        Fs3 , v096
	.byte	W06
	.byte		        Fs3 , v040
	.byte	W06
	.byte		        Gs3 , v096
	.byte	W06
	.byte		        Gs3 , v040
	.byte	W06
	.byte		N03   , Gs3 , v096
	.byte	W03
	.byte		        Gs3 , v040
	.byte	W03
	.byte		        Gs3 , v096
	.byte	W03
	.byte		        Gs3 , v040
	.byte	W03
	.byte		N06   , Bn3 , v096
	.byte	W06
	.byte		        Bn3 , v040
	.byte	W06
	.byte		        Cs4 , v096
	.byte	W06
	.byte		        Cs4 , v040
	.byte	W06
	.byte		        Ds4 , v096
	.byte	W06
	.byte		        Bn3 , v040
	.byte	W06
	.byte		N03   , Ds4 , v096
	.byte	W03
	.byte		        Ds4 , v040
	.byte	W03
	.byte		        Ds4 , v096
	.byte	W03
	.byte		        Ds4 , v040
	.byte	W03
	.byte		VOL   , 25*seq_319_mvl/mxv
	.byte		N48   , En4 , v096
	.byte	W06
	.byte		VOL   , 29*seq_319_mvl/mxv
	.byte	W03
	.byte		        31*seq_319_mvl/mxv
	.byte	W03
	.byte		MOD   , 5
	.byte		VOL   , 34*seq_319_mvl/mxv
	.byte	W03
	.byte		        38*seq_319_mvl/mxv
	.byte	W03
	.byte		        41*seq_319_mvl/mxv
	.byte	W03
	.byte		        44*seq_319_mvl/mxv
	.byte	W03
	.byte		        50*seq_319_mvl/mxv
	.byte	W03
	.byte		        55*seq_319_mvl/mxv
	.byte	W03
	.byte		        64*seq_319_mvl/mxv
	.byte	W03
	.byte		        71*seq_319_mvl/mxv
	.byte	W15
	.byte		MOD   , 0
	.byte		N06   , En4 , v040
	.byte	W24
	.byte	FINE

@*********************** Track 02 ***********************@

seq_319_1:
	.byte	KEYSH , seq_319_key+0
	.byte		VOICE , 56
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		VOL   , 94*seq_319_mvl/mxv
	.byte		PAN   , c_v-18
	.byte		BEND  , c_v+0
	.byte	W12
	.byte		N06   , Gs4 , v127
	.byte	W03
	.byte		MOD   , 6
	.byte	W03
	.byte		        0
	.byte		N06   , Gs4 , v052
	.byte	W06
	.byte		N03   , Gs4 , v120
	.byte	W03
	.byte		        Gs4 , v052
	.byte	W03
	.byte		        Gs4 , v120
	.byte	W03
	.byte		        Gs4 , v052
	.byte	W03
	.byte		N06   , En4 , v127
	.byte	W03
	.byte		MOD   , 6
	.byte	W03
	.byte		        0
	.byte		N06   , En4 , v052
	.byte	W06
	.byte		N03   , En4 , v120
	.byte	W03
	.byte		        En4 , v052
	.byte	W03
	.byte		        En4 , v120
	.byte	W03
	.byte		        En4 , v052
	.byte	W03
	.byte		N06   , Bn4 , v127
	.byte	W03
	.byte		MOD   , 6
	.byte	W03
	.byte		        0
	.byte		N06   , Bn4 , v052
	.byte	W06
	.byte		N03   , Bn4 , v120
	.byte	W03
	.byte		        Bn4 , v052
	.byte	W03
	.byte		        Bn4 , v120
	.byte	W03
	.byte		        Bn4 , v052
	.byte	W03
	.byte		N06   , An4 , v127
	.byte	W03
	.byte		MOD   , 6
	.byte	W03
	.byte		        0
	.byte		N06   , An4 , v052
	.byte	W06
	.byte		N03   , An4 , v120
	.byte	W03
	.byte		        An4 , v052
	.byte	W03
	.byte		        An4 , v120
	.byte	W03
	.byte		        An4 , v052
	.byte	W03
	.byte		VOL   , 31*seq_319_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N48   , Gs4 , v127
	.byte	W03
	.byte		VOL   , 34*seq_319_mvl/mxv
	.byte	W03
	.byte		        38*seq_319_mvl/mxv
	.byte	W03
	.byte		        43*seq_319_mvl/mxv
	.byte	W03
	.byte		MOD   , 6
	.byte		VOL   , 49*seq_319_mvl/mxv
	.byte	W03
	.byte		        56*seq_319_mvl/mxv
	.byte	W03
	.byte		        67*seq_319_mvl/mxv
	.byte	W03
	.byte		        74*seq_319_mvl/mxv
	.byte	W03
	.byte		        82*seq_319_mvl/mxv
	.byte	W03
	.byte		        91*seq_319_mvl/mxv
	.byte	W03
	.byte		        94*seq_319_mvl/mxv
	.byte	W18
	.byte		N06   , Gs4 , v048
	.byte	W09
	.byte		MOD   , 0
	.byte	W15
	.byte	FINE

@*********************** Track 03 ***********************@

seq_319_2:
	.byte	KEYSH , seq_319_key+0
	.byte		VOICE , 87
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		VOL   , 47*seq_319_mvl/mxv
	.byte		PAN   , c_v+63
	.byte	W12
	.byte		BEND  , c_v+0
	.byte		N24   , Bn3 , v120
	.byte	W12
	.byte		MOD   , 4
	.byte	W12
	.byte		        0
	.byte		N24   , Cs4 
	.byte	W12
	.byte		MOD   , 4
	.byte	W12
	.byte		        0
	.byte		N24   , Ds4 
	.byte	W12
	.byte		MOD   , 4
	.byte	W12
	.byte		        0
	.byte		N06   , An4 
	.byte	W12
	.byte		N03   , Fs4 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		VOL   , 28*seq_319_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N48   , Gs4 
	.byte	W12
	.byte		MOD   , 4
	.byte		VOL   , 38*seq_319_mvl/mxv
	.byte	W12
	.byte		        47*seq_319_mvl/mxv
	.byte	W12
	.byte		        59*seq_319_mvl/mxv
	.byte	W12
	.byte		MOD   , 0
	.byte	W24
	.byte	FINE

@*********************** Track 04 ***********************@

seq_319_3:
	.byte	KEYSH , seq_319_key+0
	.byte		VOICE , 80
	.byte		BENDR , 12
	.byte		LFOS  , 44
	.byte		PAN   , c_v+0
	.byte		VOL   , 94*seq_319_mvl/mxv
	.byte	W12
	.byte		BEND  , c_v+0
	.byte		N09   , Bn1 , v096
	.byte	W12
	.byte		N03   , En2 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		N24   , An1 
	.byte	W06
	.byte		MOD   , 6
	.byte	W18
	.byte		        0
	.byte		N06   , Gs1 
	.byte	W12
	.byte		N03   , Bn1 
	.byte	W06
	.byte		        Gs1 
	.byte	W06
	.byte		N09   , Fs1 
	.byte	W06
	.byte		BEND  , c_v+6
	.byte	W03
	.byte		        c_v+0
	.byte	W03
	.byte		N03
	.byte	W06
	.byte		        Ds1 
	.byte	W06
	.byte		VOL   , 28*seq_319_mvl/mxv
	.byte		N48   , En1 , v127
	.byte	W03
	.byte		VOL   , 31*seq_319_mvl/mxv
	.byte	W03
	.byte		        32*seq_319_mvl/mxv
	.byte	W03
	.byte		        35*seq_319_mvl/mxv
	.byte	W03
	.byte		        40*seq_319_mvl/mxv
	.byte		MOD   , 6
	.byte	W03
	.byte		VOL   , 48*seq_319_mvl/mxv
	.byte	W03
	.byte		        53*seq_319_mvl/mxv
	.byte	W03
	.byte		        62*seq_319_mvl/mxv
	.byte	W03
	.byte		        66*seq_319_mvl/mxv
	.byte	W03
	.byte		        70*seq_319_mvl/mxv
	.byte	W03
	.byte		        77*seq_319_mvl/mxv
	.byte	W03
	.byte		        88*seq_319_mvl/mxv
	.byte	W03
	.byte		        94*seq_319_mvl/mxv
	.byte	W14
	.byte		MOD   , 0
	.byte	W22
	.byte	FINE

@*********************** Track 05 ***********************@

seq_319_4:
	.byte	KEYSH , seq_319_key+0
	.byte		VOICE , 81
	.byte		LFOS  , 44
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 71*seq_319_mvl/mxv
	.byte	W12
	.byte		N06   , Bn3 , v127
	.byte	W06
	.byte		MOD   , 4
	.byte		N06   , Bn3 , v052
	.byte	W06
	.byte		N03   , Bn3 , v120
	.byte	W03
	.byte		        Bn3 , v052
	.byte	W03
	.byte		        Bn3 , v120
	.byte	W03
	.byte		        Bn3 , v052
	.byte	W03
	.byte		MOD   , 0
	.byte		N06   , Gs3 , v127
	.byte	W06
	.byte		MOD   , 4
	.byte		N06   , Gs3 , v052
	.byte	W06
	.byte		N03   , Gs3 , v120
	.byte	W03
	.byte		        Gs3 , v052
	.byte	W03
	.byte		        Gs3 , v120
	.byte	W03
	.byte		        Gs3 , v052
	.byte	W03
	.byte		MOD   , 0
	.byte		N06   , En4 , v127
	.byte	W06
	.byte		MOD   , 4
	.byte		N06   , En4 , v052
	.byte	W06
	.byte		N03   , En4 , v120
	.byte	W03
	.byte		        En4 , v052
	.byte	W03
	.byte		        En4 , v120
	.byte	W03
	.byte		        En4 , v052
	.byte	W03
	.byte		MOD   , 0
	.byte		N06   , Bn3 , v127
	.byte	W06
	.byte		        Bn3 , v052
	.byte	W06
	.byte		N03   , Bn3 , v120
	.byte	W03
	.byte		        Bn3 , v052
	.byte	W03
	.byte		        Bn3 , v120
	.byte	W03
	.byte		        Bn3 , v052
	.byte	W03
	.byte		VOL   , 19*seq_319_mvl/mxv
	.byte		N48   , En4 , v127
	.byte	W03
	.byte		VOL   , 22*seq_319_mvl/mxv
	.byte	W03
	.byte		        25*seq_319_mvl/mxv
	.byte	W03
	.byte		MOD   , 4
	.byte		VOL   , 26*seq_319_mvl/mxv
	.byte	W03
	.byte		        28*seq_319_mvl/mxv
	.byte	W03
	.byte		        34*seq_319_mvl/mxv
	.byte	W03
	.byte		        40*seq_319_mvl/mxv
	.byte	W03
	.byte		        46*seq_319_mvl/mxv
	.byte	W03
	.byte		        51*seq_319_mvl/mxv
	.byte	W03
	.byte		        59*seq_319_mvl/mxv
	.byte	W03
	.byte		        68*seq_319_mvl/mxv
	.byte	W03
	.byte		        82*seq_319_mvl/mxv
	.byte	W15
	.byte		MOD   , 0
	.byte		N06   , En4 , v040
	.byte	W24
	.byte	FINE

@*********************** Track 06 ***********************@

seq_319_5:
	.byte	KEYSH , seq_319_key+0
	.byte		VOICE , 2
	.byte		PAN   , c_v+32
	.byte		VOL   , 65*seq_319_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W12
	.byte		N06   , Gs3 , v127
	.byte	W06
	.byte		        Gs3 , v052
	.byte	W06
	.byte		N03   , Gs3 , v120
	.byte	W03
	.byte		        Gs3 , v052
	.byte	W03
	.byte		        Gs3 , v120
	.byte	W03
	.byte		        Gs3 , v052
	.byte	W03
	.byte		N06   , En3 , v127
	.byte	W06
	.byte		        En3 , v052
	.byte	W06
	.byte		N03   , En3 , v120
	.byte	W03
	.byte		        En3 , v052
	.byte	W03
	.byte		        En3 , v120
	.byte	W03
	.byte		        En3 , v052
	.byte	W03
	.byte		N06   , Bn3 , v127
	.byte	W06
	.byte		        Bn3 , v052
	.byte	W06
	.byte		N03   , Bn3 , v120
	.byte	W03
	.byte		        Bn3 , v052
	.byte	W03
	.byte		        Bn3 , v120
	.byte	W03
	.byte		        Bn3 , v052
	.byte	W03
	.byte		N06   , An3 , v127
	.byte	W06
	.byte		        An3 , v052
	.byte	W06
	.byte		N03   , An3 , v120
	.byte	W03
	.byte		        An3 , v052
	.byte	W03
	.byte		        An3 , v120
	.byte	W03
	.byte		        An3 , v052
	.byte	W03
	.byte		N48   , Gs3 , v127
	.byte	W72
	.byte	FINE

@*********************** Track 07 ***********************@

seq_319_6:
	.byte	KEYSH , seq_319_key+0
	.byte		VOICE , 0
	.byte		VOL   , 82*seq_319_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W12
	.byte		N12   , Cn1 , v127
	.byte	W12
	.byte		N06   , Cn1 , v096
	.byte	W06
	.byte		N06
	.byte	W06
	.byte		N12   , Dn1 , v092
	.byte	W18
	.byte		N06   , Cn1 , v076
	.byte	W06
	.byte		N12   , Cn1 , v096
	.byte	W12
	.byte		N06
	.byte	W06
	.byte		N06
	.byte	W06
	.byte		VOL   , 94*seq_319_mvl/mxv
	.byte		N06   , Dn2 , v088
	.byte	W06
	.byte		N05   , An1 , v104
	.byte	W06
	.byte		N06   , Gn1 , v112
	.byte	W06
	.byte		        Fn1 
	.byte	W06
	.byte		VOL   , 71*seq_319_mvl/mxv
	.byte		N06   , En1 , v120
	.byte		N42   , An2 
	.byte	W06
	.byte		N03   , En1 , v064
	.byte	W03
	.byte		        En1 , v048
	.byte	W03
	.byte		        En1 , v064
	.byte	W03
	.byte		        En1 , v048
	.byte	W03
	.byte		        En1 , v064
	.byte	W03
	.byte		        En1 , v048
	.byte	W03
	.byte		VOL   , 74*seq_319_mvl/mxv
	.byte		N03   , En1 , v064
	.byte	W03
	.byte		VOL   , 81*seq_319_mvl/mxv
	.byte		N03   , En1 , v048
	.byte	W03
	.byte		VOL   , 82*seq_319_mvl/mxv
	.byte		N03   , En1 , v088
	.byte	W03
	.byte		VOL   , 86*seq_319_mvl/mxv
	.byte		N03   , En1 , v056
	.byte	W03
	.byte		VOL   , 88*seq_319_mvl/mxv
	.byte		N03   , En1 , v088
	.byte	W03
	.byte		VOL   , 92*seq_319_mvl/mxv
	.byte		N03   , En1 , v060
	.byte	W03
	.byte		        En1 , v104
	.byte		N03   , Cn2 
	.byte	W03
	.byte		        En1 , v072
	.byte		N03   , An1 , v092
	.byte	W03
	.byte		VOL   , 82*seq_319_mvl/mxv
	.byte		N06   , En1 , v064
	.byte		N06   , Fn1 , v112
	.byte		N24   , Cs2 , v080
	.byte	W06
	.byte		VOL   , 71*seq_319_mvl/mxv
	.byte	W03
	.byte		        65*seq_319_mvl/mxv
	.byte	W03
	.byte		        59*seq_319_mvl/mxv
	.byte	W03
	.byte		        47*seq_319_mvl/mxv
	.byte	W03
	.byte		        41*seq_319_mvl/mxv
	.byte	W03
	.byte		        35*seq_319_mvl/mxv
	.byte	W03
	.byte	FINE

@*********************** Track 08 ***********************@

seq_319_7:
	.byte	KEYSH , seq_319_key+0
	.byte		VOICE , 1
	.byte		VOL   , 71*seq_319_mvl/mxv
	.byte	W12
	.byte	W72
	.byte		PAN   , c_v-32
	.byte		N12   , Bn4 , v052
	.byte	W12
	.byte		PAN   , c_v+32
	.byte		N36   , Bn4 , v080
	.byte	W12
	.byte	W72
	.byte	FINE

@******************************************************@

	.align	2

seq_319:
	.byte	8	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_319_pri	@ Priority
	.byte	seq_319_rev	@ Reverb

	.word	seq_319_grp

	.word	seq_319_0
	.word	seq_319_1
	.word	seq_319_2
	.word	seq_319_3
	.word	seq_319_4
	.word	seq_319_5
	.word	seq_319_6
	.word	seq_319_7

	.end
