@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_205_grp, bank_002
	.equ	seq_205_pri, 4
	.equ	seq_205_rev, 178
	.equ	seq_205_mvl, 127
	.equ	seq_205_key, 0

	.section .rodata
	.global	seq_205
	.align	2

@*********************** Track 01 ***********************@

seq_205_0:
	.byte	KEYSH , seq_205_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 37
	.byte		BENDR , 24
	.byte		PAN   , c_v+0
	.byte		VOL   , 25*seq_205_mvl/mxv
	.byte		BEND  , c_v+11
	.byte		N02   , Fn4 , v127
	.byte	W01
	.byte		VOL   , 42*seq_205_mvl/mxv
	.byte		PAN   , c_v+4
	.byte		BEND  , c_v+5
	.byte	W01
	.byte		VOL   , 62*seq_205_mvl/mxv
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+0
	.byte		N15
	.byte	W01
	.byte		VOL   , 77*seq_205_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+5
	.byte	W01
	.byte		VOL   , 84*seq_205_mvl/mxv
	.byte		PAN   , c_v+4
	.byte		BEND  , c_v+12
	.byte	W02
	.byte		VOL   , 96*seq_205_mvl/mxv
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+20
	.byte	W01
	.byte		VOL   , 100*seq_205_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+25
	.byte	W01
	.byte		PAN   , c_v+4
	.byte		BEND  , c_v+30
	.byte	W01
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+34
	.byte	W01
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+40
	.byte	W02
	.byte		VOL   , 94*seq_205_mvl/mxv
	.byte		PAN   , c_v+4
	.byte	W01
	.byte		VOL   , 85*seq_205_mvl/mxv
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+37
	.byte	W01
	.byte		VOL   , 66*seq_205_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+36
	.byte	W01
	.byte		VOL   , 49*seq_205_mvl/mxv
	.byte		PAN   , c_v+4
	.byte		BEND  , c_v+34
	.byte	W01
	.byte		VOL   , 32*seq_205_mvl/mxv
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+32
	.byte	W02
	.byte	FINE

@******************************************************@

	.align	2

seq_205:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_205_pri	@ Priority
	.byte	seq_205_rev	@ Reverb

	.word	seq_205_grp

	.word	seq_205_0

	.end
