@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_083_grp, bank_000
	.equ	seq_083_pri, 3
	.equ	seq_083_rev, 178
	.equ	seq_083_mvl, 127
	.equ	seq_083_key, 0

	.section .rodata
	.global	seq_083
	.align	2

@*********************** Track 01 ***********************@

seq_083_0:
	.byte	KEYSH , seq_083_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 15
	.byte		XCMD  , xIECV , 10
	.byte		        xIECL , 8
	.byte		VOL   , 100*seq_083_mvl/mxv
	.byte		BEND  , c_v+17
	.byte		N12   , Dn4 , v080
	.byte	W12
	.byte		BEND  , c_v+31
	.byte		N12   , An3 
	.byte	W12
	.byte	W12
	.byte	GOTO
	 .word	seq_083_0 + 0x2
	.byte	FINE

@******************************************************@

	.align	2

seq_083:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_083_pri	@ Priority
	.byte	seq_083_rev	@ Reverb

	.word	seq_083_grp

	.word	seq_083_0

	.end
