@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_007_grp, bank_000
	.equ	seq_007_pri, 2
	.equ	seq_007_rev, 178
	.equ	seq_007_mvl, 127
	.equ	seq_007_key, 0

	.section .rodata
	.global	seq_007
	.align	2

@*********************** Track 01 ***********************@

seq_007_0:
	.byte	KEYSH , seq_007_key+0
	.byte	TEMPO , 220/2
	.byte		VOICE , 89
	.byte		VOL   , 80*seq_007_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N18   , Gn1 , v127
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_007:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_007_pri	@ Priority
	.byte	seq_007_rev	@ Reverb

	.word	seq_007_grp

	.word	seq_007_0

	.end
