@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_162_grp, bank_002
	.equ	seq_162_pri, 4
	.equ	seq_162_rev, 178
	.equ	seq_162_mvl, 127
	.equ	seq_162_key, 0

	.section .rodata
	.global	seq_162
	.align	2

@*********************** Track 01 ***********************@

seq_162_0:
	.byte	KEYSH , seq_162_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 18
	.byte		BENDR , 12
	.byte		VOL   , 55*seq_162_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+1
	.byte		N01   , Cn6 , v100
	.byte	W01
	.byte		VOL   , 110*seq_162_mvl/mxv
	.byte	W01
	.byte		VOICE , 36
	.byte		VOL   , 55*seq_162_mvl/mxv
	.byte		N02   , Gn6 , v080
	.byte	W01
	.byte		VOL   , 110*seq_162_mvl/mxv
	.byte	W04
	.byte		PAN   , c_v+20
	.byte		N01   , Gn6 , v024
	.byte	W03
	.byte		        Gn6 , v016
	.byte	W02
	.byte		PAN   , c_v-21
	.byte	W12
	.byte	FINE

@******************************************************@

	.align	2

seq_162:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_162_pri	@ Priority
	.byte	seq_162_rev	@ Reverb

	.word	seq_162_grp

	.word	seq_162_0

	.end
