@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_066_grp, bank_000
	.equ	seq_066_pri, 5
	.equ	seq_066_rev, 178
	.equ	seq_066_mvl, 127
	.equ	seq_066_key, 0

	.section .rodata
	.global	seq_066
	.align	2

@*********************** Track 01 ***********************@

seq_066_0:
	.byte	KEYSH , seq_066_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 15
	.byte		BENDR , 2
	.byte		VOL   , 90*seq_066_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		N24   , Ds4 , v092
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte		BEND  , c_v+15
	.byte		N36   , Bn3 
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	FINE

@*********************** Track 02 ***********************@

seq_066_1:
	.byte	KEYSH , seq_066_key+0
	.byte		VOICE , 14
	.byte		VOL   , 90*seq_066_mvl/mxv
	.byte		BEND  , c_v+1
	.byte		N24   , Ds4 , v072
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte		BEND  , c_v+15
	.byte		N36   , Bn3 
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_066:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_066_pri	@ Priority
	.byte	seq_066_rev	@ Reverb

	.word	seq_066_grp

	.word	seq_066_0
	.word	seq_066_1

	.end
