@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_217_grp, bank_002
	.equ	seq_217_pri, 4
	.equ	seq_217_rev, 178
	.equ	seq_217_mvl, 127
	.equ	seq_217_key, 0

	.section .rodata
	.global	seq_217
	.align	2

@*********************** Track 01 ***********************@

seq_217_0:
	.byte	KEYSH , seq_217_key+0
	.byte		VOICE , 19
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		VOL   , 12*seq_217_mvl/mxv
	.byte		BEND  , c_v+49
	.byte		N06   , Gn4 , v080
	.byte	W01
	.byte		VOL   , 44*seq_217_mvl/mxv
	.byte		BEND  , c_v+22
	.byte	W01
	.byte		VOL   , 62*seq_217_mvl/mxv
	.byte		PAN   , c_v+8
	.byte		VOL   , 75*seq_217_mvl/mxv
	.byte		BEND  , c_v+20
	.byte	W01
	.byte		VOL   , 87*seq_217_mvl/mxv
	.byte		BEND  , c_v+33
	.byte	W01
	.byte		VOL   , 96*seq_217_mvl/mxv
	.byte		PAN   , c_v-7
	.byte		VOL   , 100*seq_217_mvl/mxv
	.byte		BEND  , c_v+54
	.byte	W01
	.byte		        c_v+63
	.byte	W01
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		N04   , Gn4 , v040
	.byte	W01
	.byte	W03
	.byte	W03
	.byte		VOICE , 45
	.byte		MOD   , 30
	.byte		BENDR , 24
	.byte		VOL   , 54*seq_217_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N06   , Gn3 , v108
	.byte	W01
	.byte		VOL   , 70*seq_217_mvl/mxv
	.byte		BEND  , c_v+4
	.byte	W01
	.byte		PAN   , c_v+5
	.byte		VOL   , 80*seq_217_mvl/mxv
	.byte		BEND  , c_v+9
	.byte	W01
	.byte		VOL   , 100*seq_217_mvl/mxv
	.byte		BEND  , c_v+16
	.byte	W01
	.byte		        c_v+24
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+2
	.byte		N06   , An3 , v100
	.byte	W01
	.byte		BEND  , c_v+7
	.byte	W01
	.byte		PAN   , c_v-4
	.byte		BEND  , c_v+12
	.byte	W01
	.byte		        c_v+18
	.byte	W01
	.byte		        c_v+27
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+4
	.byte		N06   , Bn3 , v060
	.byte	W01
	.byte		BEND  , c_v+9
	.byte	W01
	.byte		PAN   , c_v+6
	.byte		BEND  , c_v+14
	.byte	W01
	.byte		        c_v+20
	.byte	W01
	.byte		        c_v+29
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+6
	.byte		N06   , Cn4 , v040
	.byte	W01
	.byte		BEND  , c_v+11
	.byte	W01
	.byte		PAN   , c_v-6
	.byte		BEND  , c_v+15
	.byte	W01
	.byte		        c_v+22
	.byte	W01
	.byte		        c_v+31
	.byte	W02
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+9
	.byte		N06   , Dn4 , v020
	.byte	W01
	.byte		BEND  , c_v+14
	.byte	W01
	.byte		PAN   , c_v+8
	.byte		BEND  , c_v+18
	.byte	W01
	.byte		        c_v+25
	.byte	W01
	.byte		        c_v+34
	.byte	W02
	.byte	FINE

@*********************** Track 02 ***********************@

seq_217_1:
	.byte	KEYSH , seq_217_key+0
	.byte		VOICE , 57
	.byte		VOL   , 59*seq_217_mvl/mxv
	.byte		N06   , Gs4 , v052
	.byte	W01
	.byte		VOL   , 72*seq_217_mvl/mxv
	.byte	W01
	.byte		        90*seq_217_mvl/mxv
	.byte	W01
	.byte		        100*seq_217_mvl/mxv
	.byte	W03
	.byte	W02
	.byte		N04   , Gs4 , v024
	.byte	W01
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_217:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_217_pri	@ Priority
	.byte	seq_217_rev	@ Reverb

	.word	seq_217_grp

	.word	seq_217_0
	.word	seq_217_1

	.end
