@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_059_grp, bank_002
	.equ	seq_059_pri, 4
	.equ	seq_059_rev, 178
	.equ	seq_059_mvl, 127
	.equ	seq_059_key, 0

	.section .rodata
	.global	seq_059
	.align	2

@*********************** Track 01 ***********************@

seq_059_0:
	.byte	KEYSH , seq_059_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 48
	.byte		VOL   , 110*seq_059_mvl/mxv
	.byte		BEND  , c_v-7
	.byte		N12   , Gn5 , v112
	.byte	W06
	.byte	W06
	.byte		N06   , Gn5 , v040
	.byte	W06
	.byte	FINE

@*********************** Track 02 ***********************@

seq_059_1:
	.byte	KEYSH , seq_059_key+0
	.byte		VOICE , 17
	.byte		VOL   , 110*seq_059_mvl/mxv
	.byte		BEND  , c_v-7
	.byte		N12   , Dn6 , v060
	.byte	W06
	.byte	W06
	.byte		N06   , Dn6 , v032
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_059:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_059_pri	@ Priority
	.byte	seq_059_rev	@ Reverb

	.word	seq_059_grp

	.word	seq_059_0
	.word	seq_059_1

	.end
