#define VAR_FARBKUGEL_RAETSEL 0x5060
#define VALUE_FARBEN_ERLOSCHEN 0x0
#define VALUE_FARBEN_BLAU_PINK_GELB 0x1
#define VALUE_FARBEN_BLAU_GELB_PINK 0x2
#define VALUE_FARBEN_PINK_BLAU_GELB 0x3
#define VALUE_FARBEN_PINK_GELB_BLAU 0x4
#define VALUE_FARBEN_GELB_BLAU_PINK 0x5
#define VALUE_FARBEN_GELB_PINK_BLAU 0x6
