#define MAPID_URBANCENTER 0x0
#define MAPID_URBANVERBINDUNGSHAUS12 0x1
#define MAPID_URBANBIB 0x2
#define MAPID_URBANCAFEREST 0x3
#define MAPID_WALDHAIN 0x4
#define MAPID_INDOOR17EG 0x5
#define MAPID_INDOOR16OG 0x6
#define MAPID_INDOOR7OGS 0x7
