#define MAPID_CARCENTER 0x0
#define MAPID_CARSCHULEOD 0x1
#define MAPID_CARSCHULEID 0x2
#define MAPID_CARLABORVB 0x3
#define MAPID_CARLABORHB 0x4
#define MAPID_CARVERBINDUNGSHAUS12 0x5
#define MAPID_CARHAUS14EG 0x6
#define MAPID_CARHAUS14OG 0x7
