#define MAPID_HESPERIAGRABEN_1 0x0
#define MAPID_HESPERIAGRABEN_2 0x1
#define MAPID_HESPERIAGRABEN_3 0x2
#define MAPID_HESPERIAGRABEN_4 0x3
#define MAPID_HESPERIAGRABEN_5 0x4
#define MAPID_REBERATUNNEL 0x5
