#define NPC_ARKTOS 0x0
#define NPC_ZAPDOS 0x1
#define NPC_LAVADOS 0x2
#define NPC_MEWTU 0x3
#define NPC_MEW 0x4
#define NPC_RAIKOU 0x5
#define NPC_ENTEI 0x6
#define NPC_SUICUNE 0x7
#define NPC_LUGIA 0x8
#define NPC_HO_OH 0x9
#define NPC_CELEBIE 0xa
#define NPC_REGIROCK 0xb
#define NPC_REGICE 0xc
#define NPC_REGISTEEL 0xd
#define NPC_LATIAS 0xe
#define NPC_LATIOS 0xf
#define NPC_KYOGRE 0x10
#define NPC_GROUDON 0x11
#define NPC_RAYQUAZA 0x12
#define NPC_JIRACHI 0x13
#define NPC_DEOXYS_NORMALFORM 0x14
#define NPC_SELFE 0x15
#define NPC_VESPRIT 0x16
#define NPC_TOBUTZ 0x17
#define NPC_DIALGA 0x18
#define NPC_PALKIA 0x19
#define NPC_HEATARAN 0x1a
#define NPC_REGIGIGAS 0x1b
#define NPC_GIRATINA 0x1c
#define NPC_CRESSELIA 0x1d
#define NPC_PHIONE 0x1e
#define NPC_MANAPHY 0x1f
#define NPC_DARKAI 0x20
#define NPC_SHAYMIN 0x21
#define NPC_ARCEUS 0x22
#define NPC_VICTINI 0x23
#define NPC_KOBALIUM 0x24
#define NPC_TERRAKIUM 0x25
#define NPC_VIRIDIUM 0x26
#define NPC_BOREOS 0x27
#define NPC_VOLTOLOS 0x28
#define NPC_DEMETREOS 0x29
#define NPC_RESHIRAM 0x2a
#define NPC_ZEKROM 0x2b
#define NPC_KYUREM 0x2c
#define NPC_KELDEO 0x2d
#define NPC_MELOETTA 0x2e
#define NPC_GENESECT 0x2f
#define NPC_XERENEAS 0x30
#define NPC_YVETEL 0x31
#define NPC_ZYGARDE 0x32
#define NPC_DIANCIE 0x33
#define NPC_HOOPA 0x34
#define NPC_VOLCANION 0x35
