#ifndef STATS_IDS
#define STATS_IDS
#include <pkmn_items.h>
#include <pkmn_abilities_de.h>

/* POKEMON TYPEN */
#define STATS_TYP_NORMAL 0
#define STATS_TYP_KAMPF 1
#define STATS_TYP_FLUG 2
#define STATS_TYP_GIFT 3
#define STATS_TYP_BODEN 4
#define STATS_TYP_GESTEIN 5
#define STATS_TYP_KAEFER 6
#define STATS_TYP_GEIST 7
#define STATS_TYP_STAHL 8
#define STATS_TYP_NULL 9
#define STATS_TYP_FEUER 10
#define STATS_TYP_WASSER 11
#define STATS_TYP_PFLANZE 12
#define STATS_TYP_ELEKTRO 13
#define STATS_TYP_PSYCHO 14
#define STATS_TYP_EIS 15
#define STATS_TYP_DRACHE 16
#define STATS_TYP_UNLICHT 17
#define STATS_TYP_FEE 23

/* POKEMON EI_GRUPPEN */
#define STATS_EGG_GROUP_NONE 1
#define STATS_EGG_GROUP_MONSTER 1
#define STATS_EGG_GROUP_WASSER_1 2
#define STATS_EGG_GROUP_KAEFER 3
#define STATS_EGG_GROUP_FLUG 4
#define STATS_EGG_GROUP_FELD 5
#define STATS_EGG_GROUP_FEE 6
#define STATS_EGG_GROUP_GRASS 7
#define STATS_EGG_GROUP_HUMANOTYP 8
#define STATS_EGG_GROUP_WASSER_3 9
#define STATS_EGG_GROUP_MINERAL 10
#define STATS_EGG_GROUP_AMORPH 11
#define STATS_EGG_GROUP_WASSER_2 12
#define STATS_EGG_GROUP_DITTO 13
#define STATS_EGG_GROUP_DRACHE 14
#define STATS_EGG_GROUP_UNBEKANNT 15

/* POKEMON DEX FARBE */
#define STATS_DEX_COLOR_ROT 0
#define STATS_DEX_COLOR_BLAU 1
#define STATS_DEX_COLOR_GELB 2
#define STATS_DEX_COLOR_GRUEN 3
#define STATS_DEX_COLOR_SCHWARZ 4
#define STATS_DEX_COLOR_BRAUN 5
#define STATS_DEX_COLOR_VIOLETT 6
#define STATS_DEX_COLOR_GRAU 7
#define STATS_DEX_COLOR_WEISS 8
#define STATS_DEX_COLOR_ROSA 9

/* POKEMON EP ERFAHRUNG LEVEL_UP */
#define STATS_EP_LEVEL_UP_SCHNELL 0
#define STATS_EP_LEVEL_UP_SEHR_LANGSAM 1
#define STATS_EP_LEVEL_UP_SEHR_SCHNELL 2
#define STATS_EP_LEVEL_UP_NORMAL 3
#define STATS_EP_LEVEL_UP_SCHNELLER 4
#define STATS_EP_LEVEL_UP_LANGSAM 5

/* POKEMON GESCHLECHTER RATE */
#define STATS_GENDER_RATE_BOY_100_PROCENT 0
#define STATS_GENDER_RATE_BOY_87_5_PROCENT_GIRL_12_5_PROCENT 31
#define STATS_GENDER_RATE_BOY_75_PROCENT_GIRL_25_PROCENT 63
#define STATS_GENDER_RATE_BOY_50_PROCENT_GIRL_50_PROCENT 127
#define STATS_GENDER_RATE_BOY_25_PROCENT_GIRL_75_PROCENT 191
#define STATS_GENDER_RATE_BOY_12_5_PROCENT_GIRL_87_5_PROCENT 223
#define STATS_GENDER_RATE_GIRL_100_PROCENT 254
#define STATS_GENDER_RATE_OHNE_GESCHLECHT 255

#endif /* #define STATS_IDS_H */