#ifndef __PYMAP_CONSTANTS__
#define __PYMAP_CONSTANTS__
#include <constants/pymap/banks.h>
#include <constants/pymap/difficulty_variables.h>
#include <constants/pymap/engine_flags.h>
#include <constants/pymap/engine_variables.h>
#include <constants/pymap/farbkugel_raetsel.h>
#include <constants/pymap/items.h>
#include <constants/pymap/level_types.h>
#include <constants/pymap/main_story_variables.h>
#include <constants/pymap/map_adjacency_types.h>
#include <constants/pymap/map_battle_styles.h>
#include <constants/pymap/map_carun_city_maps.h>
#include <constants/pymap/map_connections.h>
#include <constants/pymap/map_flash_types.h>
#include <constants/pymap/map_heilige_orte.h>
#include <constants/pymap/map_hesperia_maps.h>
#include <constants/pymap/map_hoehle_gebirge.h>
#include <constants/pymap/map_namespaces.h>
#include <constants/pymap/map_outdoor.h>
#include <constants/pymap/map_route.h>
#include <constants/pymap/map_show_name_types.h>
#include <constants/pymap/map_types.h>
#include <constants/pymap/map_urbania_city_maps.h>
#include <constants/pymap/map_wald_suempfe.h>
#include <constants/pymap/map_weathers.h>
#include <constants/pymap/npc_sprite_table1.h>
#include <constants/pymap/npc_sprite_table2.h>
#include <constants/pymap/npc_sprite_table3.h>
#include <constants/pymap/npc_sprite_table4.h>
#include <constants/pymap/person_behaviours.h>
#include <constants/pymap/riddle_variables.h>
#include <constants/pymap/rival_pokemon_variables.h>
#include <constants/pymap/save_variables.h>
#include <constants/pymap/sidequest_flags.h>
#include <constants/pymap/signpost_types.h>
#include <constants/pymap/songs.h>
#include <constants/pymap/starter_variables.h>
#include <constants/pymap/story_flags.h>
#include <constants/pymap/worldmap_flags.h>
#endif
