@ARM Assembly macro definitions for important_flag


.equ FLAG_ORDEN_1, 0x820
.equ FLAG_ORDEN_2, 0x821
.equ FLAG_ORDEN_3, 0x822
.equ FLAG_ORDEN_4, 0x823
.equ FLAG_ORDEN_5, 0x824
.equ FLAG_ORDEN_6, 0x825
.equ FLAG_ORDEN_7, 0x826
.equ FLAG_ORDEN_8, 0x827
.equ FLAG_PKMN_MENU, 0x828
.equ FLAG_POKEDEX, 0x829
.equ FLAG_TURBOTRETER, 0x830



@ARM Assembly macro definitions for worldmap_flag


.equ WORLDMAP_FLAG_HESPERIA, 0x6ff
.equ WORLDMAP_FLAG_CARUN_CITY, 0x6fe
.equ WORLDMAP_FLAG_URBANIA_CITY, 0x6fd



@ARM Assembly macro definitions for sidequest_flag


.equ VERSTECKTES_ITEM_X, 0x700



@ARM Assembly macro definitions for story_flag


.equ FLAG_HIDDENALL, 0x500
.equ FLAG_SCHOOL_MOVESPRITE, 0x501
.equ FLAG_HIDE_RIVAL_SCHOOL, 0x502
.equ FLAG_HIDE_RIVAL_SCHOOL_OUT, 0x503
.equ FLAG_LABOR_MOVESPRITE1, 0x504
.equ FLAG_HIDE_IDAN_LABOR, 0x505
.equ FLAG_HIDE_ACHIM_LABOR, 0x506
.equ FLAG_HIDE_RIVALE_LABOR, 0x507
.equ FLAG_LABOR_MOVESPRITE2, 0x508
.equ FLAG_HIDE_IDAN_HES_OD, 0x509
.equ FLAG_HIDE_ACHIM_HES_OD, 0x50a
.equ FLAG_HIDE_TUNDRA_RUEPEL_HES, 0x59b



@ARM Assembly macro definitions for important_var


.equ VAR_LASTTALKED, 0x800f
.equ VAR_LASTRESULT, 0x800d
.equ VAR_PLAYERFACING, 0x800c
.equ VAR_NOTSET, 0x4050



@ARM Assembly macro definitions for game_mod_var


.equ VAR_MODI, 0x5050
.equ MODI_LEICHT, 0x0
.equ MODI_MITTEL, 0x1
.equ MODI_SCHWER, 0x2



@ARM Assembly macro definitions for starter_pokemon_var


.equ VAR_STARTER_PLAYER_POKEMON, 0x5052
.equ VALUE_STARTER_BISASAM, 0x1
.equ VALUE_STARTER_GLUMANDA, 0x2
.equ VALUE_STARTER_SCHIGGY, 0x3
.equ VALUE_STARTER_ENDIVIE, 0x4
.equ VALUE_STARTER_FEURIGEL, 0x5
.equ VALUE_STARTER_KARNIMANI, 0x6
.equ VALUE_STARTER_GECKARBOR, 0x7
.equ VALUE_STARTER_FLEMMLI, 0x8
.equ VALUE_STARTER_HYDROPI, 0x9
.equ VALUE_STARTER_CHELAST, 0xa
.equ VALUE_STARTER_PANFLAM, 0xb
.equ VALUE_STARTER_PLINFA, 0xc
.equ VALUE_STARTER_SERPIFEU, 0xd
.equ VALUE_STARTER_FLOINK, 0xe
.equ VALUE_STARTER_OTTARO, 0xf
.equ VALUE_STARTER_IGAMARO, 0x10
.equ VALUE_STARTER_FYNX, 0x11
.equ VALUE_STARTER_FROXY, 0x12
.equ VALUE_STARTER_BAUZ, 0x13
.equ VALUE_STARTER_FLAMIAU, 0x14
.equ VALUE_STARTER_ROBBALL, 0x15



@ARM Assembly macro definitions for rivale_pokemon_var


.equ VAR_STARTER_RIVALE_POKEMON, 0x5053
.equ VALUE_STARTER_GLUMANDA, 0x1
.equ VALUE_STARTER_SCHIGGY, 0x2
.equ VALUE_STARTER_BISASAM, 0x3
.equ VALUE_STARTER_FEURIGEL, 0x4
.equ VALUE_STARTER_KRANIMANI, 0x5
.equ VALUE_STARTER_ENDIVIE, 0x6
.equ VALUE_STARTER_FLEMMLI, 0x7
.equ VALUE_STARTER_HYDROPI, 0x8
.equ VALUE_STARTER_GECKARBOR, 0x9
.equ VALUE_STARTER_PANFLAM, 0xa
.equ VALUE_STARTER_PLINFA, 0xb
.equ VALUE_STARTER_CHELAST, 0xc
.equ VALUE_STARTER_FLOINK, 0xd
.equ VALUE_STARTER_OTTARO, 0xe
.equ VALUE_STARTER_SERPIFEU, 0xf
.equ VALUE_STARTER_FYNX, 0x10
.equ VALUE_STARTER_FROXY, 0x11
.equ VALUE_STARTER_IGAMARO, 0x12
.equ VALUE_STARTER_FLAMIAU, 0x13
.equ VALUE_STARTER_ROBBALL, 0x14
.equ VALUE_STARTER_BAUZ, 0x15



@ARM Assembly macro definitions for story_var


.equ VAR_STORYVERLAUF, 0x5051
.equ VALUE_UNTERRICHT_SCHULE, 0x0
.equ VALUE_RIVALE_SCHULE_INDOOR, 0x1
.equ VALUE_RIVALE_SCHULE_OUTDOOR, 0x2
.equ VALUE_ZUM_LABOR, 0x3
.equ VALUE_ERSTES_MAL_LABOR, 0x4
.equ VALUE_OHNE_POKE_LABOR, 0x5
.equ VALUE_MIT_POKE_LABOR, 0x6
.equ VALUE_RIVALKAMPF_HESPERIAPFAD, 0x7
.equ VALUE_HESPERIA_BRUECKE, 0x8
.equ VALUE_MAPSCRIPT_HESPERIAGRABEN, 0x9
.equ VALUE_VOR_DEM_REBERARUNNEL, 0xa
.equ VALUE_MAPSCRIPT_OST_REBERA_GEB, 0xb



@ARM Assembly macro definitions for save_var


.equ VAR_XPOS, 0x5054
.equ VAR_YPOS, 0x5055
.equ VAR_LASTPLAYERFACE, 0x5056
.equ VAR_LASTBANK, 0x5057
.equ VAR_LASTMAP, 0x5058
.equ VAR_LASTWARP, 0x5059



@ARM Assembly macro definitions for raetsel_var


.equ VAR_HESGRABEN_SCHALTER_1, 0x505a
.equ VAR_HESGRABEN_SCHALTER_2, 0x505b
.equ VAR_HESGRABEN_SCHALTER_3, 0x505c
.equ VAR_HESGRABEN_SCHALTER_4, 0x505d
.equ VAR_HESGRABEN_SCHALTER_5, 0x505e
.equ VAR_HESGRABEN_SCHALTER_6, 0x505f



@ARM Assembly macro definitions for npc1


.equ NPC_SPIELER, 0x0
.equ NPC_SPIELER_RAD, 0x1
.equ NPC_SPIELER_SITZT, 0x2
.equ NPC_SPIELER_NUTZT, 0x3
.equ NPC_SPIELER_ANGEL, 0x4
.equ NPC_SPIELER_NUTZT_2, 0x5
.equ NPC_SPIELER_NUTZT_RAD, 0x6
.equ NPC_SPIELERIN, 0x7
.equ NPC_SPIELERIN_RAD, 0x8
.equ NPC_SPIELERIN_SITZT, 0x9
.equ NPC_SPIELERIN_NUTZT, 0xa
.equ NPC_SPIELERIN_ANGEL, 0xb
.equ NPC_SPIELERIN_NUTZT_2, 0xc
.equ NPC_SPIELERIN_NUTZT_RAD, 0xd
.equ NPC_PSYCHO_M, 0xe
.equ NPC_PSYCHO_W, 0xf
.equ NPC_ASS_TRAINER_M, 0x10
.equ NPC_ASS_TRAINER_W, 0x11
.equ NPC_CAMPER, 0x12
.equ NPC_PICKNICKER, 0x13
.equ NPC_VOGELFAENGER_M, 0x14
.equ NPC_VOGELFAENGER_W, 0x15
.equ NPC_EXPERTE_M, 0x16
.equ NPC_EXPERTE_W, 0x17
.equ NPC_SCHNOESEL, 0x18
.equ NPC_LADY, 0x19
.equ NPC_SCHWARZGURT, 0x1a
.equ NPC_KAEMPFERIN, 0x1b
.equ NPC_GITARRIST_M, 0x1c
.equ NPC_GITARRIST_W, 0x1d
.equ NPC_BIKER_M, 0x1e
.equ NPC_BIKER_W, 0x1f
.equ NPC_GENTLEMAN, 0x20
.equ NPC_DAME, 0x21
.equ NPC_PKMN_ZUECHTER_M, 0x22
.equ NPC_PKMN_ZUECHTER_W, 0x23
.equ NPC_PKMN_RANGER_M, 0x24
.equ NPC_PKMN_RANGER_W, 0x25
.equ NPC_SCHUELER_M, 0x26
.equ NPC_SCHUELER_W, 0x27
.equ NPC_TEENAGER, 0x28
.equ NPC_GOERE, 0x29
.equ NPC_SCHIRMDAME, 0x2a
.equ NPC_MODEL, 0x2b
.equ NPC_SCHOENHEIT, 0x2c
.equ NPC_HEXE, 0x2d
.equ NPC_FARMER, 0x2e
.equ NPC_COWGIRL, 0x2f
.equ NPC_SKIFAHRER_M, 0x30
.equ NPC_JOGGER_W, 0x31
.equ NPC_FORSCHER_M, 0x32
.equ NPC_FORSCHER_W, 0x33
.equ NPC_POKEFAN_M, 0x34
.equ NPC_POKEFAN_W, 0x35
.equ NPC_VETERAN_M, 0x36
.equ NPC_VETERAN_W, 0x37
.equ NPC_ANGESTELLTER_W, 0x38
.equ NPC_ANGESTELLTER_M, 0x39
.equ NPC_BACKPACKER_M, 0x3a
.equ NPC_BACKPACKER_W, 0x3b
.equ NPC_PFLEGER_M, 0x3c
.equ NPC_PFLEGER_W, 0x3d
.equ NPC_VORSCHULKIND_M, 0x3e
.equ NPC_VORSCHULKIND_W, 0x3f
.equ NPC_INTERVIEWER_M, 0x40
.equ NPC_INTERVIEWER_W, 0x41
.equ NPC_SCHWIMMER_M, 0x42
.equ NPC_SCHWIMMER_W, 0x43
.equ NPC_SCHWIMMER_M_WASSER, 0x44
.equ NPC_SCHWIMMER_W_WASSER, 0x45
.equ NPC_KIND1, 0x46
.equ NPC_ZWILLING, 0x47
.equ NPC_PLANSCHER_M_WASSER, 0x48
.equ NPC_PLANSCHER_W_WASSER, 0x49
.equ NPC_SNOWBOARDER, 0x4a
.equ NPC_SKIFAHRER_W, 0x4b
.equ NPC_RAUFBOLD, 0x4c
.equ NPC_ROWDY, 0x4d
.equ NPC_HITZKOPF, 0x4e
.equ NPC_FEUERSPUCKER, 0x4f
.equ NPC_JUNGES_GLUECK_M, 0x50
.equ NPC_JUNGES_GLUECK_W, 0x51
.equ NPC_KAEFERSAMMLER, 0x52
.equ NPC_AROMALADY, 0x53
.equ NPC_NINJAJUNGE, 0x54
.equ NPC_PLANSCHER_M, 0x55
.equ NPC_PLANSCHER_W, 0x56
.equ NPC_WANDERER, 0x57
.equ NPC_ANGLER, 0x58
.equ NPC_ARBEITER1, 0x59
.equ NPC_ARBEITER2, 0x5a
.equ NPC_POLIZIST, 0x5b
.equ NPC_WACHE, 0x5c
.equ NPC_ELEKTRIKER, 0x5d
.equ NPC_MATROSE, 0x5e
.equ NPC_DRACHENPROFI, 0x5f
.equ NPC_POKEMANIAC, 0x60
.equ NPC_SAMMLER, 0x61
.equ NPC_JONGLEUR, 0x62
.equ NPC_DIEB, 0x63
.equ NPC_INFORMATIKER, 0x64
.equ NPC_JOGGER_M, 0x65
.equ NPC_ZOFFE, 0x66
.equ NPC_SERVIERER_W, 0x67
.equ NPC_SERVIERER_M, 0x68
.equ NPC_MALER, 0x69
.equ NPC_BAECKER, 0x6a
.equ NPC_ERZIEHERIN, 0x6b
.equ NPC_TAENZER, 0x6c
.equ NPC_LOCKFUEHRER, 0x6d
.equ NPC_PILOT, 0x6e
.equ NPC_HAUSMEISTER, 0x6f
.equ NPC_CLOWN, 0x70
.equ NPC_GITARRIST2, 0x71
.equ NPC_ANHAENGER_M, 0x72
.equ NPC_ANHAENGER_W, 0x73
.equ NPC_BASEBALLER, 0x74
.equ NPC_KORBLEGER, 0x75
.equ NPC_FOOTBALLER, 0x76
.equ NPC_FUSSBALLER, 0x77
.equ NPC_TENNIS_ASS, 0x78
.equ NPC_RUINENMANIAC, 0x79
.equ NPC_TEENEGER2, 0x7a
.equ NPC_MAEDCHEN1, 0x7b
.equ NPC_MAEDCHEN2, 0x7c
.equ NPC_VATER1, 0x7d
.equ NPC_MUTTER1, 0x7e
.equ NPC_OMA1, 0x7f
.equ NPC_AGENT, 0x80
.equ NPC_MUTTER2, 0x81
.equ NPC_MUTTER3, 0x82
.equ NPC_AFRO_GELBE_HAARE, 0x83
.equ NPC_FORSCHER2, 0x84
.equ NPC_VATER2, 0x85
.equ NPC_OPA1, 0x86
.equ NPC_OPA2, 0x87
.equ NPC_OPA3, 0x88
.equ NPC_VATER3, 0x89
.equ NPC_TEENAGER3, 0x8a
.equ NPC_TEENAGER4, 0x8b
.equ NPC_MAEDCHEN3, 0x8c
.equ NPC_TEENAGER5, 0x8d
.equ NPC_VATER3, 0x8e
.equ NPC_KLEINES_MAEDCHEN, 0x8f
.equ NPC_TEENAGER6, 0x90
.equ NPC_MANN1, 0x91
.equ NPC_MANN2, 0x92
.equ NPC_MANN3, 0x93
.equ NPC_CAPITAN_SCHWARZ, 0x94
.equ NPC_KOCH, 0x95
.equ NPC_TEENAGER7, 0x96
.equ NPC_TEENAGER2, 0x97
.equ NPC_OMA4, 0x98
.equ NPC_OPA_GELBE_HAARE, 0x99
.equ NPC_CAPITAN_WEISS, 0x9a
.equ NPC_FORSCHER3, 0x9b
.equ NPC_VERBINDUNGSHAUS_M, 0x9c
.equ NPC_VERBINDUNGSHAUS_W, 0x9d
.equ NPC_HEADSET1_W, 0x9e
.equ NPC_HEADSET1_M, 0x9f
.equ NPC_EMPFANGSDAME_GRUEN, 0xa0
.equ NPC_EMPFANGSDAME_ROT, 0xa1
.equ NPC_HEADSET2_W, 0xa2
.equ NPC_HEADSET3_W, 0xa3
.equ NPC_PACKETBOTE, 0xa4
.equ NPC_WAECHTER2, 0xa5
.equ NPC_VERKAEUFER, 0xa6
.equ NPC_SCHWESTER_JOY, 0xa7
.equ NPC_GAMER, 0xa8
.equ NPC_SACHSOFON, 0xa9
.equ NPC_FLOETIST_W, 0xaa
.equ NPC_FLOETIST_M, 0xab
.equ NPC_GEIGE, 0xac
.equ NPC_GITARRIST3, 0xad
.equ NPC_IDAN, 0xae
.equ NPC_LINDA, 0xaf
.equ NPC_ACHIM, 0xb0
.equ NPC_TUNDRA_RUEPEL_M, 0xb1
.equ NPC_TUNDRA_RUEPEL_W, 0xb2
.equ NPC_MARKUS, 0xb3
.equ NPC_NADINE, 0xb4
.equ NPC_JANA, 0xb5
.equ NPC_NORMAN, 0xb6
.equ NPC_LEVIN, 0xb7
.equ NPC_DIANA, 0xb8
.equ NPC_FLORIAN, 0xb9
.equ NPC_DAMIAN, 0xba
.equ NPC_JASMINE, 0xbb
.equ NPC_LENA, 0xbc
.equ NPC_PAUL, 0xbd
.equ NPC_HEILO, 0xbe
.equ NPC_FABIOLA, 0xbf
.equ NPC_AARON, 0xc0
.equ NPC_PROFESSOR1_M, 0xc1
.equ NPC_PROFESSOR2_M, 0xc2
.equ NPC_TUNDRA_SPION, 0xc3
.equ NPC_PROFESSOR1_W, 0xc4
.equ NPC_RIVALE, 0xee



@ARM Assembly macro definitions for npc2


.equ NPC_LAPRAS, 0x0
.equ NPC_GENGAR, 0x1
.equ NPC_STALOBOR, 0x2
.equ NPC_LUCARIO, 0x3
.equ NPC_GUARDEVOIR, 0x4
.equ NPC_ABSOL, 0x5
.equ NPC_GLURAK, 0x6
.equ NPC_PINSIR, 0x7
.equ NPC_AERODACTYL, 0x8
.equ NPC_NAGELLOTZ, 0x9
.equ NPC_YORKLEFF, 0xa
.equ NPC_OHRDOCH, 0xb
.equ NPC_GRILLMARK, 0xc
.equ NPC_SODAMARK, 0xd
.equ NPC_VEGIMARK, 0xe
.equ NPC_FELILOU, 0xf
.equ NPC_KLEOPARDA, 0x10
.equ NPC_MILZA, 0x11
.equ NPC_ZORUA, 0x12
.equ NPC_BISASAM, 0x13
.equ NPC_GLUMANDA, 0x14
.equ NPC_SCHIGGY, 0x15
.equ NPC_RATTFRATZ, 0x16
.equ NPC_TAUBSI, 0x17
.equ NPC_HABITAK, 0x18
.equ NPC_PIKACHU, 0x19
.equ NPC_RAICHU, 0x1a
.equ NPC_NIDORAN_W, 0x1b
.equ NPC_NIDORAN_M, 0x1c
.equ NPC_PUMMELLUF, 0x1d
.equ NPC_PIEPI, 0x1e
.equ NPC_VULPIX, 0x1f
.equ NPC_MAUZI, 0x20
.equ NPC_ENTON, 0x21
.equ NPC_FURKANO, 0x22
.equ NPC_QUAPSEL, 0x23
.equ NPC_MACHOLO, 0x24
.equ NPC_FLEGMON, 0x25
.equ NPC_PORENTA, 0x26
.equ NPC_MAGNETILO, 0x27
.equ NPC_CHANEIRA, 0x28
.equ NPC_TRAGOSSO, 0x29
.equ NPC_EVOLI, 0x2a
.equ NPC_AQUANA, 0x2b
.equ NPC_BLITZA, 0x2c
.equ NPC_FLAMARA, 0x2d
.equ NPC_PSIANA, 0x2e
.equ NPC_NACHTARA, 0x2f
.equ NPC_FOLIPURBA, 0x30
.equ NPC_GLAZIOLA, 0x31
.equ NPC_ISSO, 0x32
.equ NPC_MAMPFAXO, 0x33
.equ NPC_DRATINI, 0x34
.equ NPC_HOOTHOOT, 0x35
.equ NPC_PICHU, 0x36
.equ NPC_TOGEPI, 0x37
.equ NPC_NATU, 0x38
.equ NPC_VOLTILAMM, 0x39
.equ NPC_WAATY, 0x3a
.equ NPC_AMPHAROS, 0x3b
.equ NPC_AZURILL, 0x3c
.equ NPC_MARIL, 0x3d
.equ NPC_AZUMARILL, 0x3e
.equ NPC_QUAXO, 0x3f
.equ NPC_GRIFFEL, 0x40
.equ NPC_FELINO, 0x41
.equ NPC_HUNDUSTER, 0x42
.equ NPC_HUNDEMON, 0x43
.equ NPC_FIFFYEN, 0x44
.equ NPC_MAGNAYEN, 0x45
.equ NPC_ZIGZACHS, 0x46
.equ NPC_GERADACHS, 0x47
.equ NPC_LARVITAR, 0x48
.equ NPC_GECKARBOR, 0x49
.equ NPC_FLEMMLI, 0x4a
.equ NPC_HYDROPI, 0x4b
.equ NPC_LOTURZEL, 0x4c
.equ NPC_SAMURZEL, 0x4d
.equ NPC_SCHWALBINI, 0x4e
.equ NPC_WINGULL, 0x4f
.equ NPC_PELIPPER, 0x50
.equ NPC_BUMMELZ, 0x51
.equ NPC_ENECO, 0x52
.equ NPC_ENECORO, 0x53
.equ NPC_PLUSLE, 0x54
.equ NPC_MINUN, 0x55
.equ NPC_WATTZAPF, 0x56
.equ NPC_VOLTULA, 0x57
.equ NPC_RAUPY, 0x58
.equ NPC_SMETTPO, 0x59
.equ NPC_HORNLIU, 0x5a
.equ NPC_BIBOR, 0x5b
.equ NPC_WEBARAK, 0x5c
.equ NPC_ARIADOS, 0x5d
.equ NPC_WAUMPEL, 0x5e
.equ NPC_PAPINELLA, 0x5f
.equ NPC_PUDOX, 0x60
.equ NPC_GEHWEIEHER, 0x61
.equ NPC_MASKEREGEN, 0x62
.equ NPC_SANDAN, 0x63
.equ NPC_SANAMER, 0x64
.equ NPC_DIGDA, 0x65
.equ NPC_DIGDRI, 0x66
.equ NPC_SMOGON, 0x67
.equ NPC_SMOGMOG, 0x68
.equ NPC_NEBULAK, 0x69
.equ NPC_ALPOLLO, 0x6a
.equ NPC_KRABBY, 0x6b
.equ NPC_KREBSCOURPS, 0x6c
.equ NPC_RIHORN, 0x6d
.equ NPC_ELEKTEK, 0x6e
.equ NPC_MAGMAR, 0x6f
.equ NPC_TAUROS, 0x70
.equ NPC_SCHEROX, 0x71
.equ NPC_TUSKA, 0x72
.equ NPC_WABLU, 0x73
.equ NPC_SENGO, 0x74
.equ NPC_TRASLA, 0x75
.equ NPC_KNILZ, 0x76
.equ NPC_KAPILZ, 0x77
.equ NPC_KNACKRACK, 0x78
.equ NPC_CAMAUB, 0x79
.equ NPC_CAMERUPT, 0x7a
.equ NPC_KINDWURM, 0x7b
.equ NPC_DRACHSEL, 0x7c
.equ NPC_BRUTALANDA, 0x7d
.equ NPC_TANHEL, 0x7e
.equ NPC_METANG, 0x7f
.equ NPC_METAGROSS, 0x80
.equ NPC_STARALILI, 0x81
.equ NPC_STARAVIA, 0x82
.equ NPC_BIDIZA, 0x83
.equ NPC_BIDIFAS, 0x84
.equ NPC_SHEINUX, 0x85
.equ NPC_LUXIO, 0x86
.equ NPC_LUXTRA, 0x87
.equ NPC_KOKNODON, 0x88
.equ NPC_SCHILTERUS, 0x89
.equ NPC_WADRIBE, 0x8a
.equ NPC_HONWEISEL, 0x8b
.equ NPC_PACHIRUSU, 0x8c
.equ NPC_BAMELIN, 0x8d
.equ NPC_AMBIDIFFEL, 0x8e
.equ NPC_HASPIROR, 0x8f
.equ NPC_CHARMIAN, 0x90
.equ NPC_SCHNURRGAST, 0x91
.equ NPC_WONNEIRA, 0x92
.equ NPC_PLAUDAGEI, 0x93
.equ NPC_RIOLU, 0x94
.equ NPC_HIPPOTAS_W, 0x95
.equ NPC_HIPPOTAS_M, 0x96
.equ NPC_HIPPOTERUS_W, 0x97
.equ NPC_HIPPOTERUS_M, 0x98
.equ NPC_GLIBUNKEL, 0x99
.equ NPC_STOLLUNUIOR, 0x9a
.equ NPC_FIRTZELBLITZ, 0x9b
.equ NPC_ZUBAT, 0x9c
.equ NPC_GOLBAT, 0x9d
.equ NPC_IKSBAT, 0x9e
.equ NPC_QUICKEL, 0x9f
.equ NPC_KEIFEL, 0xa0
.equ NPC_MAMUTEL, 0xa1
.equ NPC_SEEMOPS, 0xa2
.equ NPC_SEEJONG, 0xa3
.equ NPC_WALRAISA, 0xa4
.equ NPC_SCHNEPKE, 0xa5
.equ NPC_FIRNONTOR, 0xa6
.equ NPC_FROSDEDJE, 0xa7
.equ NPC_SHNEBEDECK, 0xa8
.equ NPC_RESBILSAR, 0xa9
.equ NPC_SNIEBEL, 0xaa
.equ NPC_SNIBUNNA, 0xab
.equ NPC_SEEJONG, 0xac
.equ NPC_AUSTOSS, 0xad
.equ NPC_KIRLIA, 0xae
.equ NPC_GALAGLADI, 0xaf
.equ NPC_GANOVIL, 0xb0
.equ NPC_ROKKAIMAN, 0xb1
.equ NPC_RABIGATOR, 0xb2
.equ NPC_LATAERNCO, 0xb3
.equ NPC_GARAOS, 0xb4
.equ NPC_SNUBULL, 0xb5
.equ NPC_TEDIURSA, 0xb6
.equ NPC_PHANPY, 0xb7
.equ NPC_MILTANK, 0xb8



@ARM Assembly macro definitions for npc3


.equ NPC_ARKTOS, 0x0
.equ NPC_ZAPDOS, 0x1
.equ NPC_LAVADOS, 0x2
.equ NPC_MEWTU, 0x3
.equ NPC_MEW, 0x4
.equ NPC_RAIKOU, 0x5
.equ NPC_ENTEI, 0x6
.equ NPC_SUICUNE, 0x7
.equ NPC_LUGIA, 0x8
.equ NPC_HO_OH, 0x9
.equ NPC_CELEBIE, 0xa
.equ NPC_REGIROCK, 0xb
.equ NPC_REGICE, 0xc
.equ NPC_REGISTEEL, 0xd
.equ NPC_LATIAS, 0xe
.equ NPC_LATIOS, 0xf
.equ NPC_KYOGRE, 0x10
.equ NPC_GROUDON, 0x11
.equ NPC_RAYQUAZA, 0x12
.equ NPC_JIRACHI, 0x13
.equ NPC_DEOXYS_NORMALFORM, 0x14
.equ NPC_SELFE, 0x15
.equ NPC_VESPRIT, 0x16
.equ NPC_TOBUTZ, 0x17
.equ NPC_DIALGA, 0x18
.equ NPC_PALKIA, 0x19
.equ NPC_HEATARAN, 0x1a
.equ NPC_REGIGIGAS, 0x1b
.equ NPC_GIRATINA, 0x1c
.equ NPC_CRESSELIA, 0x1d
.equ NPC_PHIONE, 0x1e
.equ NPC_MANAPHY, 0x1f
.equ NPC_DARKAI, 0x20
.equ NPC_SHAYMIN, 0x21
.equ NPC_ARCEUS, 0x22
.equ NPC_VICTINI, 0x23
.equ NPC_KOBALIUM, 0x24
.equ NPC_TERRAKIUM, 0x25
.equ NPC_VIRIDIUM, 0x26
.equ NPC_BOREOS, 0x27
.equ NPC_VOLTOLOS, 0x28
.equ NPC_DEMETREOS, 0x29
.equ NPC_RESHIRAM, 0x2a
.equ NPC_ZEKROM, 0x2b
.equ NPC_KYUREM, 0x2c
.equ NPC_KELDEO, 0x2d
.equ NPC_MELOETTA, 0x2e
.equ NPC_GENESECT, 0x2f
.equ NPC_XERENEAS, 0x30
.equ NPC_YVETEL, 0x31
.equ NPC_ZYGARDE, 0x32
.equ NPC_DIANCIE, 0x33
.equ NPC_HOOPA, 0x34
.equ NPC_VOLCANION, 0x35



@ARM Assembly macro definitions for npc4


.equ NPC_ZERSCHNEIDERBAUM_ARENA, 0x0
.equ NPC_ZERTRUEMMERERSTEIN, 0x1
.equ NPC_ZERTRUEMMERERWAND, 0x2
.equ NPC_STAERKESTEIN, 0x3
.equ NPC_STAERKESTAHLSTEIN, 0x4
.equ NPC_METEORIT, 0x5
.equ NPC_POKEDEX, 0x6
.equ NPC_MEGASTEINFUNKEL, 0x7
.equ NPC_SEELENTAU_GANZ, 0x8
.equ NPC_POKEBALL, 0x9
.equ NPC_POKEBALL_FUER_TM, 0xa
.equ NPC_SEGELBOOT, 0xb
.equ NPC_SCHIFF, 0xc
.equ NPC_WIBELWIND, 0xd
.equ NPC_BLITZ, 0xe
.equ NPC_FEUEREXPLOSION, 0xf
.equ NPC_FEUERANGRIFF, 0x10
.equ NPC_RACKETE_UNTEN, 0x11
.equ NPC_RACKETE_OBEN, 0x12
.equ NPC_XERENEAS_VERSTEINERT, 0x13
.equ NPC_LATIOS_IM_KRISTALL, 0x14
.equ NPC_LATIAS_IM_KRISTALL, 0x15
.equ NPC_ZERSCHNEIDERBAUM, 0x16
.equ NPC_GROSSER_ZERSCHNEIDERBAUM, 0x17
.equ NPC_ZERSCHNEIDER_ANIMATION, 0x18



@ARM Assembly macro definitions for bank_table


.equ BANKID_OUTDOOR, 0x0
.equ BAMKID_ROUTE, 0x1
.equ BANKID_UNTERWASSER, 0x2
.equ BANKID_WAELDER_SUEMPFE, 0x3
.equ BANKID_HOEHLE_GEBIRGE, 0x4
.equ BANKID_LEGENDAERE, 0x5
.equ BANKID_HEILIGE_ORTE, 0x6
.equ BANKID_WICHTIGE_INDOOR, 0x7
.equ BANKID_HESSPERIA_INDOOR, 0x8
.equ BANKID_CARUN_CITY_INDOOR, 0x9
.equ BANKID_URBANIA_CITY_INDOOR, 0xa
.equ BANKID_DEBUG_TEST_START, 0x78



@ARM Assembly macro definitions for bank1


.equ MAPID_HESPERIA_NORD, 0x0
.equ MAPID_HESPERIA_SUED, 0x1
.equ MAPID_CARUN_CITY, 0x2
.equ MAPID_URBANIA_CITY_OST, 0x3
.equ MAPID_URBANIA_CITY_WEST, 0x4



@ARM Assembly macro definitions for bank2


.equ MAPID_HESPERIAPFAD, 0x0
.equ MAPID_HESPERIAZWEIG, 0x1
.equ MAPID_CARUNPFAD, 0x2
.equ MAPID_YELNIAPFAD, 0x3



@ARM Assembly macro definitions for bank3


.equ MAPID_LEBENDERWALD_YELNIA_1, 0x0
.equ MAPID_LEBENDERWALD_YELNIA_2, 0x1
.equ MAPID_LEBENDERWALD_YELNIA_3, 0x2
.equ MAPID_LEBENDERWALD_YELNIA_4, 0x3
.equ MAPID_LEBENDERWALD_YELNIA_5, 0x4
.equ MAPID_LEBENDERWALD_YELNIA_6, 0x5
.equ MAPID_LEBENDERWALD_YELNIA_7, 0x6
.equ MAPID_LEBENDERWALD_YELNIA_8, 0x7
.equ MAPID_LEBENDERWALD_YELNIA_9, 0x8
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_1, 0x9
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_2, 0xa
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_3, 0xb
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_4, 0xc
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_5, 0xd
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_6, 0xe
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_7, 0xf
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_8, 0x10
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_9, 0x11
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_10, 0x12
.equ MAPID_LEBENDERWALD_YELNIA_RAETSEL_11, 0x13
.equ MAPID_LEBENDERWALD_YELNIA_EINGANG_BAUM_DES_LEBENS, 0x14
.equ MAPID_LEBENDERWALD_YELNIA_EINGANG_BAUM_DES_LEBENS_ERWACHT, 0x15
.equ MAPID_TOTERWALD_YELNIA_1, 0x16
.equ MAPID_TOTERWALD_YELNIA_2, 0x17
.equ MAPID_TOTERWALD_YELNIA_AUSGANG, 0x18
.equ MAPID_YELNIA_WALDHUETTE_EG, 0x19
.equ MAPID_YELNIA_WALDHUETTE_SZ, 0x1a



@ARM Assembly macro definitions for bank4


.equ MAPID_HESPERIAGRABEN_1, 0x0
.equ MAPID_HESPERIAGRABEN_2, 0x1
.equ MAPID_HESPERIAGRABEN_3, 0x2
.equ MAPID_HESPERIAGRABEN_4, 0x3
.equ MAPID_HESPERIAGRABEN_5, 0x4
.equ MAPID_REBERATUNNEL, 0x5



@ARM Assembly macro definitions for bank6


.equ MAPID_BAUM_DES_LEBENS_EINGANG, 0x0
.equ MAPID_BAUM_DES_LEBENS_EBENE_1, 0x1
.equ MAPID_BAUM_DES_LEBENS_EBENE_2, 0x2
.equ MAPID_BAUM_DES_LEBENS_EBENE_3, 0x3
.equ MAPID_BAUM_DES_LEBENS_EBENE_4, 0x4
.equ MAPID_BAUM_DES_LEBENS_EBENE_5, 0x5
.equ MAPID_BAUM_DES_LEBENS_EBENE_6, 0x6
.equ MAPID_BAUM_DES_LEBENS_EBENE_7, 0x7
.equ MAPID_BAUM_DES_LEBENS_EBENE_8, 0x8
.equ MAPID_REBERA_GEBIRGE_OST_1, 0x9
.equ MAPID_REBERA_GEBIRGE_OST_2, 0xa
.equ MAPID_REBERA_GEBIRGE_OST_3, 0xb
.equ MAPID_RUINE_DER_WAECHTER_1, 0xc
.equ MAPID_RUINE_DER_WAECHTER_2, 0xd
.equ MAPID_RUINE_DER_WAECHTER_3, 0xe
.equ MAPID_RUINE_DER_WAECHTER_4, 0xf
.equ MAPID_RUINE_DER_WAECHTER_5, 0x10
.equ MAPID_RUINE_DER_WAECHTER_6, 0x11
.equ MAPID_RUINE_DER_WAECHTER_7, 0x12
.equ MAPID_RUINE_DER_WAECHTER_8, 0x13



@ARM Assembly macro definitions for bank8


.equ MAPID_SPIELERHAUS_EG, 0x0
.equ MAPID_SPIELERHAUS_OG, 0x1
.equ MAPID_HES_HAUS_1_EG, 0x2
.equ MAPID_HES_HAUS_1_UG, 0x3
.equ MAPID_HES_HAUS_2_EG, 0x4
.equ MAPID_HES_HAUS_2_UG, 0x5
.equ MAPID_HES_HAUS_3_EG, 0x6
.equ MAPID_HES_HAUS_3_UG, 0x7
.equ MAPID_HES_HAUS_4_EG, 0x8
.equ MAPID_HES_HAUS_4_UG, 0x9
.equ MAPID_HES_HAUS_5_EG, 0xa
.equ MAPID_HES_HAUS_5_UG, 0xb
.equ MAPID_HES_CENTER, 0xc



@ARM Assembly macro definitions for bank9


.equ MAPID_CAR_TRAINERSCHULE_OD, 0x0
.equ MAPID_CAR_LABOR_VORDERRAUM, 0x1
.equ MAPID_CAR_LABOR_HINTERRAUM, 0x2
.equ MAPID_CAR_HAUS_1_EG, 0x3
.equ MAPID_CAR_HAUS_1_UG, 0x4
.equ MAPID_CAR_HAUS_2_EG, 0x5
.equ MAPID_CAR_HAUS_2_UG, 0x6
.equ MAPID_CAR_HAUS_3_EG, 0x7
.equ MAPID_CAR_HAUS_3_UG, 0x8
.equ MAPID_CAR_HAUS_4_EG, 0x9
.equ MAPID_CAR_HAUS_4_UG, 0xa
.equ MAPID_CAR_CENTER, 0xb
.equ MAPID_CAR_TRAINERSCHULE_ID, 0xc
.equ MAPID_CAR_VERBINDUNGSHAUS_CARUNPFAD, 0xd
.equ MAPID_CAR_VERBINDUNGSHAUS_YELNIAPFAD, 0xe



@ARM Assembly macro definitions for bank10


.equ MAPID_URBANI_CENTER, 0x0
.equ MAPID_VERBINDUNGSHAUS_URBANIA_CITY, 0x1
.equ MAPID_HAUS_1_EG, 0x2
.equ MAPID_HAUS_1_OG_1, 0x3
.equ MAPID_HAUS_1_OG_2, 0x4
.equ MAPID_HAUS_1_OG_3, 0x5
.equ MAPID_HAUS_2_EG, 0x6
.equ MAPID_HAUS_2_OG, 0x7
.equ MAPID_HAUS_3_EG, 0x8
.equ MAPID_HAUS_3_OG, 0x9
.equ MAPID_HAUS_4_EG, 0xa
.equ MAPID_HAUS_4_OG, 0xb
.equ MAPID_HAUS_5_EG, 0xc
.equ MAPID_HAUS_5_OG_1, 0xd
.equ MAPID_HAUS_5_OG_2, 0xe
.equ MAPID_HAUS_6_EG, 0xf
.equ MAPID_HAUS_6_OG, 0x10
.equ MAPID_HAUS_7_EG, 0x11
.equ MAPID_HAUS_7_OG_1, 0x12
.equ MAPID_HAUS_7_OG_2, 0x13
.equ MAPID_HAUS_7_OG_3, 0x14
.equ MAPID_HAUS_7_OG_4, 0x15
.equ MAPID_URBANIA_BIB_EG, 0x16
.equ MAPID_URBANIA_BIB_OG, 0x17
.equ MAPID_URBANIA_CAFE, 0x18
.equ MAPID_URBANIA_RESTERAUNT, 0x19
.equ MAPID_URBANIA_ARENA_1, 0x1a
.equ MAPID_URBANIA_ARENA_2, 0x1b
.equ MAPID_URBANIA_ARENA_3, 0x1c



@ARM Assembly macro definitions for bank120


.equ MAPID_STARTMAP_INTRO, 0x0



@ARM Assembly macro definitions for ebene_type


.equ EBENE_IMMER, 0x0
.equ EBENE_SUFER, 0x1
.equ EBENE_NORMAL, 0x3
.equ EBENE_BRUECKE, 0x4



@ARM Assembly macro definitions for signpost_type


.equ SIGN_IMMER, 0x0
.equ SIGN_OBEN, 0x1
.equ SIGN_UNTEN, 0x2
.equ SIGN_RECHTS, 0x3
.equ SIGN_LINKS, 0x4
.equ SIGN_VERSTECKTES_ITEM, 0x7



@ARM Assembly macro definitions for map_connections


.equ ANB_KEINS, 0x0
.equ ANB_UNTEN, 0x1
.equ ANB_OBEN, 0x2
.equ ANB_LINKS, 0x3
.equ ANB_RECHTS, 0x4
.equ ANB_ABTAUCHEN, 0x5
.equ ANB_AUFTAUCHEN, 0x6



@ARM Assembly macro definitions for music


.equ SEQ_BGM_TOWN_HESPERIA, 0x10b
.equ SEQ_BGM_CITY_CARUN, 0x110
.equ SEQ_BGM_CITY_URBANIA, 0x111
.equ SEQ_BGM_ROUTE_1, 0x12e
.equ SEQ_BGM_ROUTE_2, 0x12f
.equ SEQ_BGM_PC, 0x15b
.equ SEQ_BGM_LAB, 0x17e
.equ SEQ_BGM_P_FOY, 0x160
.equ SEQ_BGM_CAVE_GUARDIAN, 0x186
.equ SEQ_BGM_P_TOL, 0x1b4
.equ SEQ_BGM_P_DFOY, 0x1b5
.equ SEQ_BGM_EYE_TT, 0x1e2
.equ SEQ_BGM_EYE_TT_BOSS, 0x1e3
.equ SEQ_BGM_EYE_GUARDIAN, 0x1e6
.equ SEQ_BGM_EVENT_TT_RAID, 0x1f4
.equ SEQ_BGM_INTRO, 0x1f5
.equ SEQ_BGM_EVENT_DEOXYS, 0x1f8
.equ SEQ_BGM_EVENT_TT_DANCE, 0x1f9
.equ SEQ_BGM_SURF, 0x1fa
.equ SEQ_BGM_EYE_RIVF, 0x1de
.equ SEQ_BGM_EYE_RIVM, 0x1df



@ARM Assembly macro definitions for behaviours


.equ BEH_KEINE_BEWEGUNG, 0x0
.equ BEH_UMHERBLICKEN, 0x1
.equ BEH_HERUMGEHEN, 0x2
.equ BEH_GEHE_AUF_AB, 0x3
.equ BEH_GEHE_AUF_AB2, 0x4
.equ BEH_GEHE_HIN_HER, 0x5
.equ BEH_GEHE_HIN_HER2, 0x6
.equ BEH_BLICKE_OBEN, 0x7
.equ BEH_BLICKE_UNTEN, 0x8
.equ BEH_BLICKE_LINKS, 0x9
.equ BEH_BLICKE_RECHTS, 0xa
.equ BEH_ERROR, 0xb
.equ BEH_VERSTECKT, 0xc
.equ BEH_BLICKE_OBEN_UNTEN, 0xd
.equ BEH_BLICKE_LINKS_RECHTS, 0xe
.equ BEH_BLICKE_OBEN_LINKS, 0xf
.equ BEH_BLICKE_OBEN_RECHTS, 0x10
.equ BEH_BLICKE_UNTEN_LINKS, 0x11
.equ BEH_BLICKE_UNTEN_RECHTS, 0x12
.equ BEH_BLICKE_OBEN_UNTEN_LINKS, 0x13
.equ BEH_BLICKE_OBEN_UNTEN_RECHTS, 0x14
.equ BEH_BLICKE_OBEN_LINKS_RECHTS, 0x15
.equ BEH_BLICKE_UNTEN_LINKS_RECHTS, 0x16
.equ BEH_BLICKE_GEGEN_UHRZEIGERSINN, 0x17
.equ BEH_BLICKE_IM_UHRZEIGERSINN, 0x18
.equ BEH_LAUFE_AUF_AB, 0x19
.equ BEH_LAUFE_AUF_AB2, 0x1a
.equ BEH_LAUFE_HIN_HER, 0x1b
.equ BEH_LAUFE_HIN_HER2, 0x1c
.equ BEH_LAUFE_HOCH_RECHTS_LINKS_RUNTER, 0x1d
.equ BEH_LAUFE_RECHTS_LINKS_HOCH_RUNTER, 0x1e
.equ BEH_LAUFE_RUNTER_HOCH_RECHTS_LINKS, 0x1f
.equ BEH_LAUFE_LINKS_RUNTER_HOCH_RECHTS, 0x20
.equ BEH_LAUFE_HOCH_LINKS_RECHTS_RUNTER, 0x21
.equ BEH_LAUFE_LINKS_RECHTS_RUNTER_HOCH, 0x22
.equ BEH_LAUFE_RUNTER_HOCH_LINKS_RECHTS, 0x23
.equ BEH_LAUFE_RECHTS_RUNTER_HOCH_LINKS, 0x24
.equ BEH_LAUFE_LINKS_HOCH_RUNTER_RECHTS, 0x25
.equ BEH_LAUFE_HOCH_RUNTER_RECHTS_LINKS, 0x26
.equ BEH_LAUFE_RECHTS_LINKS_HOCH_RUNTER2, 0x27
.equ BEH_LAUFE_RUNTER_RECHTS_LINKS_HOCH, 0x28
.equ BEH_LAUFE_RECHTS_HOCH_RUNTER_LINKS, 0x29
.equ BEH_LAUFE_HOCH_RUNTER_LINKS_RECHTS, 0x2a
.equ BEH_LAUFE_LINKS_RECHTS_HOCH_RUNTER, 0x2b
.equ BEH_LAUFE_RUNTER_LINKS_RECHTS_HOCH, 0x2c
.equ BEH_LAUFE_GEGEN_UHRZEIGERSINN, 0x2d
.equ BEH_LAUFE_GEGEN_UHRZEIGERSINN2, 0x2e
.equ BEH_LAUFE_GEGEN_UHRZEIGERSINN3, 0x2f
.equ BEH_LAUFE_GEGEN_UHRZEIGERSINN4, 0x30
.equ BEH_LAUFE_GEGEN_UHRZEIGERSINN5, 0x31
.equ BEH_LAUFE_UHRZEIGERSINN, 0x32
.equ BEH_LAUFE_UHRZEIGERSINN2, 0x33
.equ BEH_LAUFE_UHRZEIGERSINN3, 0x34
.equ BEH_SPIELER_KOPIEREN, 0x35
.equ BEH_SPIELER_SPIEGELN, 0x36
.equ BEH_SPIELER_SPIEGELN2, 0x37
.equ BEH_SPIELER_SPIEGELN3, 0x38
.equ BEH_BAUM_WAND_VERKLEIDUNG, 0x39
.equ BEH_FELS_WAND_VERKLEIDUNG, 0x3a
.equ BEH_SPIELER_SPIEGELN_STAND, 0x3b
.equ BEH_SPIELER_KOPIEREN_STAND2, 0x3c
.equ BEH_SPIELER_SPIEGELN_STAND3, 0x3d
.equ BEH_SPIELER_SPIEGELN_STAND4, 0x3e
.equ BEH_VERSTECKT2, 0x3f
.equ BEH_STELLE_GEHEN_UNTEN, 0x40
.equ BEH_STELLE_GEHEN_OBEN, 0x41
.equ BEH_STELLE_GEHEN_LINKS, 0x42
.equ BEH_STELLE_GEHEN_RECHTS, 0x43
.equ BEH_STELLE_JOGGEN_UNTEN, 0x44
.equ BEH_STELLE_JOGGEN_OBEN, 0x45
.equ BEH_STELLE_JOGGEN_LINKS, 0x46
.equ BEH_STELLE_JOGGEN_RECHTS, 0x47
.equ BEH_STELLE_LAUFEN_UNTEN, 0x48
.equ BEH_STELLE_LAUFEN_OBEN, 0x49
.equ BEH_STELLE_LAUFEN_LINKS, 0x4a
.equ BEH_STELLE_LAUFEN_RECHTS, 0x4b
.equ BEH_VERSTECKT_THREE, 0x4c
.equ BEH_STELLE_GEHEN_UNTEN2, 0x4d
.equ BEH_STELLE_GEHEN_OBEN2, 0x4e
.equ BEH_STELLE_GEHEN_LINKS2, 0x4f
.equ BEH_STELLE_GEHEN_RECHTS2, 0x50



@ARM Assembly macro definitions for map_namespaces


.equ MAP_HESPERIA, 0x58
.equ MAP_CARUN_CITY, 0x59
.equ MAP_URBANIA_CITY, 0x5a
.equ MAP_HESPERIAPFAD, 0x5b
.equ MAP_HESPERIAZWEIG, 0x5c
.equ MAP_CARUNPFAD, 0x5d
.equ MAP_YELNIAPFAD, 0x5e
.equ MAP_WALD_VON_YELNIA, 0x5f
.equ MAP_HESPERIAGRABEN, 0x60
.equ MAP_REBERATUNNEL, 0x61
.equ MAP_BAUM_DES_LEBENS, 0x62
.equ MAP_REBERA_GEBIRGE_OST, 0x63
.equ MAP_RUINE_DER_WAECHTER, 0x64
.equ MAP_TRAINERSCHULE, 0x65
.equ MAP_WALDHAIN, 0x66



@ARM Assembly macro definitions for map_showname


.equ NAMEN_NICHT_ANZEIGEN, 0x0
.equ NAMEN_ANZEIGEN, 0x1
.equ NAMEN_DORF_ANZEIGEN, 0x6
.equ NAMEN_ORT_ANZEIGEN, 0x7
.equ NAMEN_STADT_ANZEIGEN, 0xd



@ARM Assembly macro definitions for flash_types


.equ BLITZ_NEIN, 0x0
.equ BLITZ_EINSETZBAR, 0x1
.equ BLITZ_NICHT_EINSETZBAR, 0x2



@ARM Assembly macro definitions for map_weather


.equ WEATHER_INNEN, 0x0
.equ WEATHER_SONNIG_MIT_WOLKEN_IM_WASSER, 0x1
.equ WEATHER_DRAUSSEN, 0x2
.equ WEATHER_REGEN, 0x3
.equ WEATHER_DREI_SCHNEEFLOCKEN, 0x4
.equ WEATHER_GEWITTER, 0x5
.equ WEATHER_NEBEL, 0x6
.equ WEATHER_SCHNEE, 0x7
.equ WEATHER_SANDSTURM, 0x8
.equ WEATHER_NEBEL_RECHTS, 0x9
.equ WEATHER_HELLER_NEBEL, 0xa
.equ WEATHER_DUNKEL, 0xb
.equ WEATHER_UNTERGRUND_BINKT, 0xc
.equ WEATHER_STARKES_GEWITTER, 0xd
.equ WEATHER_UNTWERWASSER, 0xe
.equ WEATHER_0F, 0xf



@ARM Assembly macro definitions for map_type


.equ MAP_TYPE_NORMAL, 0x0
.equ MAP_TYPE_DORF, 0x1
.equ MAP_TYPE_STADT, 0x2
.equ MAP_TYPE_ROUTE, 0x3
.equ MAP_TYPE_HOEHLE, 0x4
.equ MAP_TYPE_UNTERWASSER, 0x5
.equ MAP_TYPE_TYPE_06, 0x6
.equ MAP_TYPE_TYPE_07, 0x7
.equ MAP_TYPE_INNEN, 0x8
.equ MAP_TYPE_GEHEIMBASIS, 0x9



@ARM Assembly macro definitions for battle_types


.equ BATTLE_TYPE_ZUFALL, 0x0
.equ BATTLE_TYPE_ARENA, 0x1
.equ BATTLE_TYPE_TEAM_ROCKET, 0x2
.equ BATTLE_TYPE_03, 0x3
.equ BATTLE_TYPE_TOP_VIER1, 0x4
.equ BATTLE_TYPE_TOP_VIER2, 0x5
.equ BATTLE_TYPE_TOP_VIER3, 0x6
.equ BATTLE_TYPE_TOP_VIER4, 0x7
.equ BATTLE_TYPE_GROSSER_POKEBALL, 0x8
